Logflare/logflare

lib/logflare/table_bigquery_schema_builder.ex
mix.exs
test/logflare/table_bigquery_schema_builder_test.exs

`Logflare.BigQuery.TableSchemaBuilder` implements the following features:
- creates new schema from event params metadata
- deep merges new table schema overwriting the fields schema values if a conflict happens and keeping fields schemas present only in the previously existing table schema
- deeply sorts all fields schemas by name
This pull request also includes tests and some utility functions for easier testing.

BigQuery Table Schema Builder module

---

assets/package.json
assets/yarn.lock
config/dev.exs

node-sass build fails:
```
.node-gyp/16.0.0/include/node/v8-internal.h:452:38: error: no template named
'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
```
Solution: upgrade node-sass and everything that's required
Turns out, the version of node-sass used does not work on Node.js 16:
https://stackoverflow.com/questions/67241196/error-no-template-named-remove-cv-t-in-namespace-std-did-you-mean-remove
Surely, an earlier version can be used, however it may come with a bit
more hassle since Node.js did not ship Apple Silicon binaries prior to v16:
https://github.com/asdf-vm/asdf-nodejs/issues/189#issuecomment-848432339
There's a pull request for ASDF to fall back to source code builds,
but it hasn't been merged yet.
https://github.com/asdf-vm/asdf-nodejs/pull/207
So, to get around …

Problem: can't build assets on Apple Silicon

---

lib/logflare/endpoint/cache.ex
lib/logflare/endpoint/query.ex
lib/logflare/sql.ex
lib/logflare_web/controllers/endpoint_controller.ex
priv/repo/migrations/20210715022534_add_source_mapping_to_endpoint_queries.exs
sql/src/main/kotlin/app/logflare/sql/DatabaseSourceResolver.kt
sql/src/main/kotlin/app/logflare/sql/Main.kt
sql/src/main/kotlin/app/logflare/sql/QueryProcessor.kt
sql/src/main/kotlin/app/logflare/sql/Source.kt
sql/src/main/kotlin/app/logflare/sql/SourceMappingVisitor.kt
sql/src/main/kotlin/app/logflare/sql/SourceResolver.kt
sql/src/test/kotlin/app/logflare/sql/QueryProcessorTest.kt

There is a problem with queries relying on names of sources, as those
can be easily renamed and the query will become erroneous as it won't
be possible to map them to sources anymore and they will need to be
manually updated.
Solution: record source name <-> token mapping when saving queries
and use it when loading query to ensure the query is up-to-date.
---
This will conflict with #880 upon its merge but I'll resolve it when we get there.

Problem: endpoint queries keeping up with source renaming

---

lib/logflare/application.ex
lib/logflare/sql.ex

Cachex seem to fail starting up.
Logflare.SQL crashes with the {:EXIT, :nodistribution} error
in some cases.
Solution: ensure distribution is started before caches
and Logflare.SQL
Cachex doesn't accommodate distribution status changes after it has been
started.

Problem: can't start application without distribution

---

sql/src/main/kotlin/app/logflare/sql/SourceMappingVisitor.kt

Not all source names are valid table identifiers. So, for example,
if one was to rename a source to something that, say, contains a whitespace,
it'll end up verbatim in the query:
```
SELECT something FROM my awesome query
```
Solution: quote source names that are not valid table identifiers
The above query will now look like this:
```
SELECT something FROM `my awesome query`
```

Problem: updating endpoint queries with invalid source names

---

lib/logflare/endpoint/query.ex

Solution: don't try to map sources if there are errors
Because if we do, it will result in an error that'll get added.

Problem: endpoint errors are reported twice

---

lib/logflare_web/templates/endpoint/show.html.eex

It is shown as a oneliner instead of what was entered by the user.
Solution: ensure formatting is respected (using pre tag)

Problem: endpoint query formatting in the UI

---

sql/src/main/kotlin/app/logflare/sql/QueryProcessor.kt
sql/src/main/kotlin/app/logflare/sql/SourceMappingVisitor.kt
sql/src/main/kotlin/app/logflare/sql/TableVisitor.kt
sql/src/main/kotlin/app/logflare/sql/TransformerVisitor.kt
sql/src/test/kotlin/app/logflare/sql/QueryProcessorTest.kt

Source names used in UNNEST functions are not being translated
to their tokens. This makes queries unexecutable as BigQuery
won't get the rigth table to query.
Solution: handle UNNESTing by processing the unnesting clause
It definitely works well if the source name is an alias, but it might
be limited in types of (complex) expressions it will take if source name
is used as is.

Problem: UNNEST source name in endpoint queries

---

lib/logflare_web/templates/endpoint/show.html.eex

When one is looking at endpoint details, it is not convenient
to edit it. One must go back to the list of endpoints, find it there
and click the edit icon.
Solution: add an edit icon in the sub-navigation
for detailed endpoint view.
This follows the design pattern used in Sources.

Problem: inconvenient editing of endpoints

---

lib/logflare/endpoint/cache.ex
lib/logflare/sql.ex
sql/src/main/kotlin/app/logflare/sql/Main.kt

When there's no Mix, these will fail as there is no Mix.env or MIX_ENV
Solution: don't rely on Mix, but logflare's own config

Problem: Logflare SQL and endpoint caching in absence of Mix

---

lib/logflare_web/controllers/endpoint_controller.ex
lib/logflare_web/router.ex
lib/logflare_web/templates/endpoint/edit.html.eex

There is no way to change them (for example, if we no longer want to
share them with somebody)
Solution: allow resetting the token
This exposes resetting functionality in the editing view. Cache
is preserved during the reset as the actual query doesn't change
and caches are named after unchangeable IDs rather than changeable
tokens.

Problem: endpoint query URLs are static

---

assets/js/endpoint.js
lib/logflare_web/templates/endpoint/index.html.eex

This requires extra steps, such as going into the detailed
view of an endpoint and selecting-copying the URL out of cURL example.
Solution: show copiable URL in the list of endpoints
(similarly to sources)

Problem: finding endpoint query URL is inconvenient

---

lib/logflare_web/templates/endpoint/show.html.eex

Looks like the closing bracket went into an incorrect place.
Solution: make it valid

Problem: invalid HTML in endpoint query params form

---

sql/src/main/kotlin/app/logflare/sql/TableVisitor.kt
sql/src/test/kotlin/app/logflare/sql/QueryProcessorTest.kt

Solution: ensure we don't try to update a token that doesn't exist
(the one that's may hold the table name)

Problem: UNNEST(metadata) throws a NullPointerException

---

sql/src/main/kotlin/app/logflare/sql/QueryParseError.kt
sql/src/main/kotlin/app/logflare/sql/QueryProcessor.kt

What does (x,y) mean there? what is in "near"?
Solution: rewrite error messages to provide more context
This change indicates line and column explicitly and tries
to extract more of the query's context surrounding the error.
It also removes some error messaging that is not very useful
for end users, such as "state: some_number".

Problem: sql parser's error messages are somewhat cryptic

---

lib/logflare_web/router.ex

There's one for Elixir, but is it suitable for Erlang?
Solution: designate /erlang/logger to Erlang logger
It is still the same handler, though (Elixir one)

Problem: which logging API should Erlang client use?

---

docker-compose.yml
lib/logflare/application.ex
lib/logflare/sql.ex

I currently use docker compose to run different versions of postgresql
on my development machine. This means I have to use different ports.
Solution: ensure Logflare is able to handle :port config setting
I've also included docker-compose.yml if anybody wants to use this setup.

Problem: running postgresql on a non-standard port

---

.tool-versions

I noticed that when I have asset/node_modules installed, iex -S mix phx.server
takes close to forever to start.
Solution: update elixir and erlang
Not sure what's the cause of this but at this point, going for later versions
gets rid of the problem I experienced, and I don't want to spend too much time
trying to figure this out at this moment.

Problem: experiencing major slowdown upon node startup

---

lib/logflare/endpoint/cache.ex
lib/logflare/endpoint/query.ex
lib/logflare/sql.ex
lib/logflare_web/controllers/endpoint_controller.ex
lib/logflare_web/templates/endpoint/new.html.eex
lib/logflare_web/templates/endpoint/show.html.eex
priv/repo/migrations/20211123192744_sandboxable_endpoint_queries.exs
sql/src/main/kotlin/app/logflare/sql/Main.kt
sql/src/main/kotlin/app/logflare/sql/QueryProcessor.kt
sql/src/main/kotlin/app/logflare/sql/RestrictedPatternVisitor.kt
sql/src/main/kotlin/app/logflare/sql/SandboxRestrictionViolated.kt
sql/src/main/kotlin/app/logflare/sql/SandboxVisitor.kt
sql/src/main/kotlin/app/logflare/sql/SelectQueryRequired.kt
sql/src/main/kotlin/app/logflare/sql/SingularQueryRequired.kt
sql/src/main/kotlin/app/logflare/sql/TableVisitor.kt
sql/src/main/kotlin/app/logflare/sql/TransformerVisitor.kt
sql/src/test/kotlin/app/logflare/sql/QueryProcessorTest.kt

Parametrized queries help filtering data a bit but they don't alow for a better
precision and joining of data being queried.
Solution: allow execution of sandboxed queries in endpoints
The idea here is that passing `sql` parameter in an endpoint will replace the
`SELECT` query in the pre-defined query but will *only* allow CTEs defined in
the pre-defined query to be used a source of data.
This change also makes Logflare.Endpoint.Cache instances partition by a pair of
`(Query, Params)` as opposed to just `Query`. This allows us to cache all
parameterized queries.

Problem: querying specific data from endpoints

---

lib/logflare/endpoint/cache.ex
lib/logflare_web/controllers/endpoint_controller.ex

It's trying to lookup a specific endpoint query cache with no given parameters,
so it'll only invalidate the no-parameters cache. But it will not invalidate
parameterized instances.
Solution: iterate over all matching registered cache instances
The implementation is not highly efficient as we're iterating over all
`global`ly-registered names, but it works for the time being and current load (at least
it should). Switching to a registry where a more efficient pattern lookup is possible
will fix this problem.

Problem: endpoint query cache invalidation is broken

---

sql/src/main/kotlin/app/logflare/sql/TableVisitor.kt
sql/src/test/kotlin/app/logflare/sql/QueryProcessorTest.kt

```
Unexpected exception thrown: java.lang.NullPointerException: Cannot invoke
"gudusoft.gsqlparser.TSourceToken.setString(String)" because the return value
of "gudusoft.gsqlparser.nodes.TObjectName.getObjectToken()" is null
```
Solution: ensure implicit columns do not require object token
as there's none.

Problem: UNNEST(column) query fails with an exception

---

sql/src/main/kotlin/app/logflare/sql/TableVisitor.kt
sql/src/main/kotlin/app/logflare/sql/TransformerVisitor.kt
sql/src/test/kotlin/app/logflare/sql/QueryProcessorTest.kt

SQL component omits translating some names from table names to source names
when they are backquoted.
Solution: ensure full table name is used for comparison and quotes aren't
There's a particularly important aspect of doing the former. A case like this:
```sql
WITH src as (
SELECT
name
FROM `first.src`
)
SELECT value FROM src
```
resulted in `first.src` treated as `src` and effectively not processed because
it matches CTE's name.

Problem: some quoted table names are not translated to sources

---

sql/src/main/kotlin/app/logflare/sql/ParameterExtractor.kt
sql/src/test/kotlin/app/logflare/sql/QueryProcessorTest.kt

This prevents use of parameters in CTEs in general and, in particular,
impacts the usefuless of sandboxed queries as those rely on CTEs for
sandboxing.
Solution: make ParameterExtractor go deeper on CTEs
It turns out, TCTE's acceptChildren stops at TCTE and does not go into
the subquery.

Problem: parameters in CTE subqueries don't get translated

---

lib/logflare/endpoint/cache.ex
lib/logflare/endpoint/query.ex
lib/logflare_web/templates/endpoint/edit.html.eex
priv/repo/migrations/20211130201505_configurable_endpoint_caching.exs

Solution: make endpoint query caching intervals configurable
`cache_duration_seconds` -- how long to cache the value for (default: 1800 secs, 0 turns caching off)
`proactive_requerying_seconds` -- how often to refresh proactively (default: 1800 secs, 0 turns requerying off)

Problem: no way to control caching intervals for endpoint queries

---

sql/src/main/kotlin/app/logflare/sql/ParameterExtractor.kt
sql/src/test/kotlin/app/logflare/sql/QueryProcessorTest.kt

For example, here it won't pick up @c:
```
SELECT a, @a FROM b WHERE d > timestamp_sub(@c, interval 7 day)
```
Solution: ensure GSP traverses node `args`
As GSP is scarcely documented, my exploration through debugging
showed that `args` property contains parameter names we're looking for,
so we should extract them.
Currently, we'll handle this inside of function calls.

Problem: SQL parser doesn't pick up parameters in certain cases

---

sql/src/main/kotlin/app/logflare/sql/ParameterExtractor.kt

```
"
Cannot invoke \"gudusoft.gsqlparser.nodes.TExpressionList.acceptChildren(gudusoft.gsqlparser.nodes.TParseTreeVisitor)\" because the return value of \"gudusoft.gsqlparser.nodes.TFunctionCall.getArgs()\" is null
"
```
Solution: ensure we don't execute `acceptChildren` on a null expression list

Problem: parameter extraction failing

---

lib/logflare/endpoint/cache.ex

Logs indicate that there was on occurrence of endpoint query execution
being terminated with `crash_reason` of `shutdown` which indicates that
the endpoint cache process terminated while `query` call was being processed.
Solution: reset expiration timer upon endpoint process resolution
My working theory of what could have happened there:
1. We have a running endpoint E.
2. E approaches cache expiration time.
3. We resolve query to the endpoint E.
4. We start making a query call to E.
5. Just before gen_server sends a message for the call, its internal timeout is processed and the process is stopped.
6. gen_server doesn't get a response but gets a termination notice.
Essentially, a race condition.
In an attempt to resolve it, if endpoint resolution points us to an existing
process, we make …

Problem: endpoint termination during query

---

sql/src/main/kotlin/app/logflare/sql/TransformerVisitor.kt

It seems as if table names are mapped twice.
Solution: ensure visitor visits tables only once
This might not be a perfect fix, but it might serve
as a temporary mitigation for the problem. Time will show.

Problem: gsp 2.5.0.8 fails tests

---

sql/src/main/kotlin/app/logflare/sql/TableVisitor.kt

Solution: manage `CTEList.cteNames` ourselves
as sqlparser seem to have abandonded it.

Problem: sqlparser 2.5.2.5 breaks CTE parsing

---

.github/workflows/tests.yml

yaml indentation when I previously uncommented a new step was causing the whole action to fail.

chore: indentation fix for github actions

---

lib/logflare_web/controllers/plugs/verify_api_access.ex
lib/logflare_web/router.ex
test/logflare_web/plugs/verify_api_access_test.exs

Adds in the `/api/endpoints/query/:token` route, with the `/endpoints/query/:token` route to be considered deprecated.

feat: add in /api/endpoints/query route

---

lib/logflare/auth.ex

Adds docs + specs to remaining auth functions, removes an unused email-related function.
Tests have been deferred to [backlog](https://www.notion.so/supabase/AuthTest-tests-for-email-tokens-move-gravatar-cfa030fe66f4415997a4861282ec9158)

chore: add docs & specs to functions, remove unused code

---

lib/logflare_web/controllers/plugs/verify_api_access.ex

Bugfix for the following error for api requests to `/endpoints/query`
```
#PID<0.10604.37> running LogflareWeb.Endpoint (connection #PID<0.32396.4>, stream id 175) terminated Server: logflare.app:80 (http) Request: GET /endpoints/query/[REDACTED]?project=[REDACTED]&sql=SELECT+count%28*%29+as+count+FROM+postgres_logs&iso_timestamp_start=2022-06-09T17%3A28%3A15.904Z&project_tier=PAYG ** 
(exit) an exception was raised: ** 
(Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, LQueue, DBConnection.PrepareStream, DBConnection.Stream, Timex.Interval, Flow, Floki.HTMLTree, Scrivener.Page, Jason.OrderedObject, Iteraptor.Array, Function, GenEvent.Stream, List, MapSet, …
```

fix: plug init options not passed as opts to each plug call.

---

.github/workflows/tests.yml
lib/logflare/logs/lql/lql.ex
lib/logflare/source/recent_logs_server.ex
lib/logflare/sources/rule.ex
lib/logflare_web/live/sources/source_rules_live.ex
test/logflare/logs/ingest/ingest_transformer_test.exs
test/logflare/logs/rejected_logs_test.exs
test/logflare/lql/lql_parser_test.exs
test/logflare/source/recent_logs_server_test.exs
test/logflare/sources/source_routing_test.exs
test/logflare/users_api_integration_test.exs
test/logflare/validator/bq_schema_change_validator_test.exs
test/logflare_web/admin/admin_search_dashboard_live_test.exs
test/logflare_web/controllers/log_controller_test.exs
test/logflare_web/controllers/source_controller_test.exs
test/logflare_web/controllers/user_controller_test.exs
test/logflare_web/live_views/source_rules_lv_test.exs

Enables compilation warning checks on each PR, so that bugs like #1136 will get caught earlier.

chore: enable compilation warnings check

---

config/config.exs
lib/logflare/application.ex
lib/logflare_web/controllers/marketing_controller.ex
lib/logflare_web/router.ex
lib/logflare_web/templates/marketing/pricing.html.eex
test/logflare_web/controllers/marketing_controller_test.exs
test/support/factory.ex

Fixes a bug where marketing page references in templates were stale, leading to pricing page erroring out. Removes a few unused routes/actions.
Also adds controller test coverage for templates, to prevent such regressions.
Cleanup of code in separate PR.

fix: linking to contact page, add test coverage for marketing pages

---

lib/logflare/application.ex
lib/logflare/billing.ex
lib/logflare/billing/stripe.ex
lib/logflare/source/billing_writer.ex
lib/logflare_web/controllers/plugs/check_source_count.ex
lib/logflare_web/live/access_tokens_live.ex
test/logflare/billing_test.exs
test/logflare/logs/logs_test.exs
test/logflare/source/billing_writer_test.exs
test/support/conn_case.ex
test/support/factory.ex
test/test_helper.exs

Fixes for the following bug, currently blocking prod release. This bugfix also adds test coverage for BillingWriter module
```
GenServer :"2ab8cead-8956-4f37-b3f7-b9163e4891c3-bw" terminating
** (WithClauseError) no with clause matching: nil 
(logflare 1.0.0) lib/logflare/source/billing_writer.ex:57: Logflare.Source.BillingWriter.record_to_stripe/2 
(logflare 1.0.0) lib/logflare/source/billing_writer.ex:31: Logflare.Source.BillingWriter.handle_info/2 
(stdlib 3.17.2) gen_server.erl:695: :gen_server.try_dispatch/4 
(stdlib 3.17.2) gen_server.erl:771: :gen_server.handle_msg/6 
(stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :write_count
```

fix: BillingWriter record_to_stripe get sub item id bug

---

lib/logflare/ecto/bigquery/bq_repo.ex
lib/logflare/endpoint/cache.ex
lib/logflare/endpoint/resolver.ex
lib/logflare_web/controllers/endpoint_controller.ex
test/logflare_web/controllers/endpoint_controller_test.exs

Previously Endpoints would block when queries were running even when they were cached. 
Now It doesn't block except for the first response, and if queries are not cached at all.
Need some feedback with the tests I created here too, but I got one to work!

Timeout endpoint queries

---

lib/logflare/source/billing_writer.ex

@chasers for billing accounts without stripe sub item attached, I'm just going to ignore recording the stripe usage.
FYI.

fix: emit warning for no subscription item for attached billing account

---

lib/logflare/billing.ex
lib/logflare/source/billing_writer.ex
test/support/factory.ex

Closer investigation when comparing unnesting code used prior to refactor showed that the post-refactor code attempted to do an additional list unnest. I've updated the code to match the stripe api response payload
Reference code prior to refactor
https://github.com/Logflare/logflare/blob/57062df2f1b9133c88117907671b1a7f1b5af0e8/lib/logflare/billing_accounts.ex
Tests have been updated.

fix: Stripe payload unnesting for stripe subscription item bug

---

lib/logflare/application.ex
test/logflare_web/controllers/marketing_controller_test.exs

Fixes flaky tests where SystemMetricsSup dies somehow and brings everything down with it.
This fix starts the supervisor on demand in test

chore: fix flaky ci tests relating to SystemMetrics

---

.tool-versions
README.md

gradle 7.1 does not supoprt openjdk versions >=17. Since java LTS version is now 17, we should shift to it.
If developer has other jdk versions >=17 when using gradle 7.1, the following error will appear on compilation:
```
projects/logflare [staging●] » mix sql                    
> Task :compileKotlin
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :startScripts FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':startScripts'.
> BUG! exception in phase 'semantic analysis' in source unit 'SimpleTemplateScript8.groovy' Unsupported class file major version 63
* Try:
> Run with --stacktrace option …
```

fix: set the java/gradle build env with asdf

---

README.md
lib/logflare_web/controllers/auth/oauth_controller.ex
test/logflare_web/controllers/oauth_controller_tests.exs

This PR adds handling and logging for unrecognized Oauth providers, which should let us better track these random auth errors that keep popping up.
Reference ticket: [link](https://www.notion.so/supabase/bug-OauthController-undefined-function-858073f81a1c410ea9b5123dc2014956)

fix: Adds handling for unrecognized oauth handling for OauthController

---

test/logflare/lql/lql_parser_test.exs

This PR fixes the LQL parser tests, and removes lots of redundant and irregular tests. 
Key improvement involves cutting down LOC from >1.5k to ~500, which makes tests drastically easier to grok
part of #1178

chore: fix lql parser tests

---

lib/logflare/logs/log_event.ex
test/logflare/log_event_test.exs

Adds some testing for LogEvent functions, as #1178 requires removal of the LogEvent.Body for more payload flexibility.

chore: add log event testing

---

lib/logflare/logs/log_event.ex
lib/logflare_web/live/search_live/templates/logs_list.html.leex
test/logflare/log_event_test.exs

Removes the `:ephemeral` key from the `LogEvent` struct, as it is unused.
Depends on #1184

chore: remove ephemeral logevent key

---

lib/logflare/endpoints.ex
lib/logflare/endpoints/query.ex
lib/logflare/users/users.ex
lib/logflare_web/controllers/api/endpoint_controller.ex
lib/logflare_web/router.ex
test/logflare_web/controllers/api/endpoint_controller_test.exs
test/logflare_web/controllers/api/source_controller_test.exs
test/support/factory.ex

Adds multiple operations to an accounts query endpoint API
* GET /api/endpoints - Lists all queries for a given user
* GET /api/endpoints/:token - Show single query for a given user
* POST /api/endpoints - Create a new query entry
* PUT /api/endpoints/:token - Updates an existing query
* DELETE /api/endpoints/:token - Deletes an existing query

Acount query endpoint API

---

lib/logflare/logs/lql/lql_parser_helpers.ex

removes the undocumented and unused `_includes` lql operator. Tests containing it has already been refactored and removed in a previous PR.

chore: remove _includes lql operator

---

lib/logflare/logs/ingest_transformers.ex
test/logflare/logs/ingest/ingest_transformer_test.exs
test/logflare/logs/logs_test.exs

Bugfix with ingestion transformers only applying to the `metadata` key and assuming that it is always a map.
This PR adjusts this behaviour and applies the transformers on all parameters, which is the desired behaviour for top-level keys ingestion.
Reference [ticket](https://www.notion.so/supabase/bug-log-ingestion-do_transform-no-matching-function-clause-error-953faff4efda40e2940ff3ad9059d294)

fix: allow non-map values for metadata key ingestion transformers

---

Dockerfile

To facilitate current deployment, we'll add JQ temporarily until a better solution is found

Add JQ to base image

---

run.sh

Due to a typo, it will use the wrong file

Fix to use .secrets.env instead of .staging.env

---

lib/logflare/release.ex

Due to the way we were starting our migrations, :ssl was not being started throwing an error when we tried to run migrations

Adjust Release migration task

---

lib/logflare/release.ex

For some reason SSL is not starting as expected, this will try to force that startup during the migration stage

Explicit :ssl library startup during migration

---

Dockerfile
config/runtime.exs
docker/staging.app.Dockerfile

For some reason storing the JSON as an env var is presenting problems, this moves back to the option of using a file.

Move back to Google JSON file for auth

---

config/runtime.exs

We were using Mix.env() which is not available on runtime.

Fix config issue

---

Dockerfile
docker/staging.app.Dockerfile

Docker images were built with content being saved on the root user. It seems that this might have caused issues with our deployment and static assets.

Move content out of root user in Docker

---

.dockerignore
Dockerfile

Due to the fact that we're using an older version of phoenix we still require to run the assets pipeline via webpack

Fix static file digest

---

Dockerfile

Due to the fact that we're using gzip compression we need to run mix.digest on the newly deployed webpack output.

Use mix digest to properly setup static files

---

lib/logflare_web/endpoint.ex

To reduce potential deployment issues, removed gzip as a variable.

Remove gzip usage

---

Dockerfile
docker-compose.yml
lib/logflare_web/endpoint.ex

Changed the location where generated static files will be moved into.
The issue until now was the location of the static files. The application has the starting script at `/opt/app/rel/logflare/bin/` but the `Application.app_dir(:logflare)` it's actually `/opt/app/rel/logflare/lib/` and this was the folder that Plug.Static is expected to have the static content to be served.
Also enabled gzip to enable compressed assets to be served in a more performant way.

Fix Static serving

---

.github/workflows/pipeline.yml

Due to the fact that now we build Docker images on GH we need to change the way we trigger Cloud Build. From now on we'll use a Webhook to trigger Cloud Build instead of the merges to staging.

Trigger Cloudbuild via Webhook

---

.github/workflows/pipeline.yml

* Getting secrets should be enough but to have extra insurance we're adding a mask to avoid leaking secrets
* Currently a bad response is returning no error code, adding --fail-with-body so we can fail the build step and have some feedback

Ensure that a mask is added to secrets; make curl fail on bad response

---

lib/logflare/source/bigquery/schema.ex
test/logflare/source/bigquery/schema_test.exs
test/support/factory.ex

Fixes schema throttling logic, which results in schemas getting updated too frequently and then not at all.
ref [ticket](https://www.notion.so/supabase/deno-subhosting-events-schema-change-not-registering-32cd8104ab834af2acd4f81a825965f3)

fix: schema update throttling bug

---

.github/workflows/pipeline.yml

Due to the fact that curl was using oauth2 credentials we were not able to make this step repeatable without messing around with oauth2 authentication due to temporary tokens.
This will move the job to use gcloud beta features

Move from curl to gcloud

---

config/staging.exs
lib/logflare_web/controllers/admin_controller.ex
lib/logflare_web/controllers/auth/email_controller.ex
lib/logflare_web/router.ex
mix.exs

Adds some refactoring based on sobelow recommendations:
- Removes String.to_atom/1 usage  in admin_controller
- ignore https check (done outside of release)
- add CSP for oauth public routes.
- get rid of CSRF warning by having separate controller action, even though logic is the same.
Ref [ticket](https://www.notion.so/supabase/WIP-Add-in-Logflare-to-Quality-Gate-2ba0d013846f413f97a17ba22e52f06a)

chore: partial refactoring for sobelow recommendations

---

config/runtime.exs

conditionally overwrites configs at runtime based on whether the configs are provided (not a `nil` value). kv pairs are filtered out accordingly.
This bridges the two config loading methods until the `.env` loading scripts are ironed out.

fix: conditional overwriting of compile-time configs

---

lib/logflare/logs/log_event.ex

Once the prod api gateway has been updated to send top level project, we can safely remove the cloudflare hack.
Postgres logs is already sending top level project key, as can be [seen here](https://github.com/supabase/infrastructure/blob/d5a08873610ad0755aa0ec5e981608bdbd0da154/init-scripts/postgres/vector.toml#L79)

chore: remove clustering keys hack

---

lib/logflare/source/bigquery/schema_builder.ex
test/logflare/google/bigquery/schema_builder_test.exs
test/logflare/lql/lql_parser_test.exs

Removes the `top_level` option from the `SchemaBuilder.build_table_schema/3` and converts it to two arity, which as top-level keys are now the default behaviour for ingestion and schema comparisons

chore: remove top-level option from build_table_schema

---

config/runtime.exs
mix.exs

This PR removes config defaults, which should already be handled by config.exs and friends at compiletime. The defaults interfere with the nil filtering at runtime.
Also move db seeding to `mix setup`, which would only apply to the dev database now.

fix: move dev seeding to setup alias, remove runtime config defaults

---

config/config.exs

Due to the way logflare_agent starts up the application, we need to set an empty list as a default so it doesn't fail with an attempt of iterating over a nil value.

Set default value for logflare_agent sources list.

---

.github/workflows/pipeline.yml

We want to rebuild from scratch each time, stale build cache might result in compilation conflicts.

chore: remove build cache

---

Dockerfile

Due to the way we fetch node ips we need to add curl to our docker image to be deployed

Add curl to our application docker image

---

test/logflare/lql/lql_parser_test.exs

update test to remove flakiness, which is causing ci tests to fail due to millisecond time diff

chore: update timestamp comparison tests to reduce flakiness

---

lib/logflare/logs/vector.ex

The top level `project` key is missing from the Postgres logs. We pulled out some special handling of that now that Logflare fully supports top level fields.
But the Vector ingest endpoint currently takes the whole payload and puts it in the `metadata` key before doing anything else. 
So we need to add a new v2 Vector endpoint which doesn't do this, and then update the infra vector config to point to this new Vector ingest Endpoint. 
This PR contains a temp fix until the above happens. 
Infra Vector config is here: https://github.com/supabase/infrastructure/blob/f02e65790b89050c2b97953aa8fd233237825b95/init-scripts/project/vector.yaml

fix: add docs and handle special case for project key temporarily

---

lib/logflare/logs/vector.ex

`@doc` tag was overriding docs for the same function and since we compile with --warnings-as-errors we ended up triggering a failure in the CI.

Fix doc override compilation warning

---

config/runtime.exs

Fixes misnamed env var, users are unable to use the vercel integration due to misnamed secret env var
ticket [here](https://www.notion.so/supabase/Adding-in-vercel-integration-results-in-500-error-ee953a9187514ca3b85e363fd6137dfd)

fix: VERCEL_CLIENT_SECRET env var typo fix for vercel integration

---

cloudbuild/prod/cloudbuild.yaml

To avoid issues of pushing unwanted revisions, production will only used the versioned image. The version is set using the VERSION file in the root of the project.

Cloudbuild in prod only uses versioned docker image

---

lib/logflare/team_users/team_user.ex
lib/logflare/teams.ex
lib/logflare/teams/team.ex
lib/logflare/user.ex
lib/logflare_web/controllers/api/team_controller.ex
lib/logflare_web/router.ex
priv/repo/migrations/20221210010955_add_token_to_team.exs
priv/repo/migrations/20221210011115_set_token_default_values.exs
priv/repo/migrations/20230206155428_add_team_token_index.exs
test/logflare/teams_test.exs
test/logflare_web/controllers/api/endpoint_controller_test.exs
test/logflare_web/controllers/api/source_controller_test.exs
test/logflare_web/controllers/api/team_controller_test.exs

* Add token field to Team
* Add List Teams endpoint
* Add Show Team endpoint
* Add Create team endpoint
* Add Update team endpoint
* Add Delete endpoint
* Fix assertions on other endpoint tests
When listing or showing teams, we will consider the team the user is owner of and the ones he is part of via Team User.
Create, Update and Delete can only be done to the team they are owner of.

Add Teams / Teams User management API

---

README.md
assets/css/homepage.scss
assets/css/marketing.scss
assets/css/marketing_pricing.scss
assets/css/marketing_responsive.scss
assets/css/media_queries.scss
assets/css/mixins.scss
lib/logflare_web/templates/marketing/homepage_cta.html.eex
lib/logflare_web/templates/marketing/index.html.eex
lib/logflare_web/templates/source/no_logs_modal.html.eex
lib/logflare_web/templates/source/show.html.eex

Fix for broken cloudflare integration links throughout the app, now navigating directly to https://cloudflare.com/apps/logflare/install
I've also done a big-ish refactor for the marketing pages styling and removed a lot of duplicate code.
Might have some tiny styling changes on the home page here and there but i don't think it is very noticable.
Main large change in styling is the addition of 3 different fixed point media query mixins, which help to make all media query styling customizations consistent across the app. These are in `mixins.scss`. These responsiveness mixins are to be used for overriding from mobile upwards, as shown in example comments.
- `@include mobile { ...}` for backwards compat with setting max-width for mobile-only rules
- `@include tablet { ...}`  for tablet and …

Fix/logflare cloudflare links, refactor of homepage styling

---

lib/logflare_web/controllers/auth/auth_controller.ex

For some weird reason, cond was trying to match on the content of the session improperly which made the oauth for google fail, reverted to use the old code.

Fix Google Sign In

---

lib/logflare/sql_v2.ex
test/logflare/sql_test.exs

fixed order by in sandboxed queries being broken, adds in relevant testing

fix: order by in sandboxed queries are not replaced correctly

---

lib/logflare/google/resource_manager.ex
test/logflare/google/resource_manager_test.exs

Editor wasn't enough to make the builds work and according to this docs https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers/run what we need is create.

Change from editor to build in Cloudbuild SA

---

assets/js/admin_dashboard_charts.jsx
assets/js/source_log_chart.jsx

Due to the update of nivo, theme of tooltips are applied using ThemeProvider but we still require the theme attribute to set the theme of the bar chart.

(fix) Fix tooltip missing background

---

.github/workflows/docker-ci.yml

To avoid extra garbage while testing we won't push the new built images

Remove pushing on new darwin images

---

.github/workflows/docker-ci.yml

The Elixir base image we're using does not have a darwin architecture so we need to switch to arm again. Using docker image inspect of current base image on a macos we got:
```
...
"Architecture": "arm64",
"Variant": "v8",
"Os": "linux",
...
```

Remove Darwin and use Linux ARM again

---

assets/js/admin_dashboard_charts.jsx
assets/js/source_log_chart.jsx
assets/package.json

Due to a bad UI element we're reverting to a previous nivo version that worked.
ThemeProvider doesn't seem to behave as expected.

Revert nivo version

---

assets/js/source_log_chart.jsx

Due to a lack of jquery import the source log graph drill down wasn't working.

(fix) Source Log graph drill down

---

lib/logflare_web/live/billingaccount_live/estimate_usage_component.ex
test/logflare_web/live/billingaccount_live/estimate_usage_component_test.exs

Due to our pricings we need way more information to provide this information in a useful manner. Removing the cost estimate for now so we can revisit the approach.

(remove) Remove cost estimate from Billing screen

---

.docker.env
docker-compose.yml

The way we have our settings setup wouldn't work due to a bad hostname and a bad database name.

(fix) Docker environment wasn't properly handlign docker hostname

---

lib/logflare_web/live/search_live/templates/logs_list.html.leex

Some logs seem to be missing the event_message key making the UI break with a non-matching error.
This will avoid the UI breaking but does not fix the underlying issue.

(fix) Avoid missing event_message to fully break the UI

---

lib/logflare_web/controllers/plugs/fetch_resource.ex
lib/logflare_web/controllers/plugs/verify_api_access.ex
lib/logflare_web/controllers/plugs/verify_resource_ownership.ex
lib/logflare_web/router.ex
test/logflare_web/controllers/endpoints_controller_test.exs
test/logflare_web/plugs/verify_api_access_test.exs
test/logflare_web/plugs/verify_resource_ownership_test.exs

adds a new api route `/api/endpoints/query/name/:name` for an endpoint by name. Requires an api key to be provided, and does not apply to endpoints where auth is disabled `enable_auth=false`

feat: query endpoints by name

---

Dockerfile

for cli testing
Replication:
1. build local docker image using `docker-compose build` without the ports exposed.
2. add the following line to the cli logflare service startup [here](https://github.com/supabase/cli/commit/573f69c7baa04bcdb3b11ce42c807ec53ec40850)
```
PortBindings:  nat.PortMap{"4002/tcp": []nat.PortBinding{{HostPort: strconv.FormatUint(4002, 10)}}},
```
3. Run the cli `INTERNAL_IMAGE_REGISTRY=docker.io go run . start`
4. Verify that there is no port mapping `docker-compose ps`. The supposedly exposed port will also not be available on localhost `https://localhost:4002`
5. Repeat steps 1-4 with the expose ports, and it will now bind.
On a separate note, it seems like all images that ports via the cli have an `EXPOSE` in their dockerfiles. Might be an issue with the docker …

chore: expose more ports for cli

---

lib/logflare/sql_v2.ex

SqlV2 module was building dataset id append using env instead of the correct config

fix: use dataset_id_append instead of env for sql query

---

priv/repo/migrations/20210729161959_subscribe_to_postgres.exs
priv/setup.sql

Fixes migration error integrating on cli, due to change in role not permitted. Moving this to external schema setup.
Originally discussed [here](https://supabase.slack.com/archives/C01KSDNKNCW/p1679814598657469) during cli team sync.
In any case, as the username used for the migration is only at compile time, this change would not have a material effect when using a different pg username, and should actually be executed separately by the self-hoster.

fix: remove alter user from migrations, shift it to conditional scope.

---

.github/workflows/mirror.yml

Change the permissions from the GH action to add package write and id-token write.
https://github.com/Logflare/logflare/pull/1423

(fix) Change mirror action to have proper permissions

---

.github/workflows/docker-ci.yml

permissions fix for mirroring docker image
fix for this error: https://github.com/Logflare/logflare/actions/runs/4545211587/workflow
```
The nested job 'mirror' is requesting 'packages: write, id-token: write', but is only allowed 'packages: none, id-token: none'.
```

chore: job-specific permissions for mirror action

---

cloudbuild/staging/cloudbuild.yaml

removes old jar copying from previous parser

chore: remove jar copying from cloudbulid

---

.github/workflows/docker-ci.yml

A change in the name of the job broke the existing file

fix: Docker CI action failing due to badly referenced job

---

cloudbuild/prod/cloudbuild.yaml
docker/secret_setup.Dockerfile

Currently we're still using the inline trigger instead of the file to build the final docker image.
This will allow us to use the file in our repo vs inlined

fix: Cloudbuild script

---

.github/workflows/arm-docker-latest-push.yml
.github/workflows/arm-docker-versioned-push.yml
.github/workflows/docker-ci.yml

So that our docker builds run on self-hosted infra for faster builds. Still retaining current build steps for now.

chore: add self-hosted label for docker building workflows

---

docs/docs.logflare.com/docs/self-hosting/index.md
rel/env.sh.eex
run.sh

Removes `MY_NODE_IP` as a required environment variable. Defaults it to `127.0.0.1` in the release shell script.

chore: rename MY_NODE_IP, make it optional with default value.

---

.github/workflows/docker-ci.yml

Properly set the runs-on tag for Docker CI GH job.

fix - Set Self Hosted to run on Docker CI job

---

.github/workflows/docker-ci.yml

Reverted to use non self hosted runners so we can build docker images for release purposes.

fix - Revert to non self hosted runners

---

lib/logflare_web/router.ex

Moves allow access to all users
This PR does not add this to the dashboard subnav as of yet, as access tokens do not support ingest routes yet. (need to switch over the plug pipeline).

fix: access tokens path scope

---

run.sh

Getting `16:49:49.117 [info]  Protocol 'inet_tcp': register/listen error: econnrefused` on boot sometimes which restarts Erlang in a loop a few times and then boots but this blows up the cluster.

fix: sleep for 15 seconds for networking to be ready

---

rel/env.sh.eex

Fixes: `./logflare: /opt/app/rel/logflare/releases/1.1.0/env.sh: line 18: syntax error: bad substitution`

fix: node name

---

.github/workflows/docker-ci.yml

* Properly call env in gcloud comand
* Checking if missing double quotes impacts env setting ( https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable )

fix - Fixes GH action for Docker CI

---

.github/workflows/docker-ci-amd-and-arm.yml
.github/workflows/docker-ci.yml

Due to some refactors we're not pushing the correct image to docker hub

fix - Define properly the image tag

---

lib/logflare_grpc/opentelemetry/proto/collector/trace/v1/trace_service.pb.ex
lib/logflare_grpc/trace/server.ex
test/logflare_grpc/trace/server_test.exs

Due to a timeout in staging when fetching trailers from a unary request, we'll implement streams to see if this mitigates the issue.
We'll need to improve error handling also since a failed span insert should return a better error to the consumer.
Note: Generated protobufs do not have streams and that change had to be mad by hand

fix - Send grpc trailer headers and change to use streams vs unary requests

---

config/config.exs
priv/repo/migrations/20210729161959_subscribe_to_postgres.exs

This PR fixes superuser requirement for migrations, which makes it possible to run migrations using a postgres user without superuser privilege.
The DB will still need to have `wal_level = 'logical'` and replication enabled for the user, but that should be executed at db setup and not during migrations.

fix: update publication migration to not require superuser

---

lib/logflare/cache_buster.ex

When `DB_SCHEMA` is set, cache buster will not work due to it being hardcoded to the `public` schema. This makes it more flexible for pattern matching.

fix: allow cache busting on non-public schemas

---

.tool-versions

Contributors would need to install the correct otp version with:
```bash
asdf install
```
This fixes the deps bump, which now requires otp 25.

chore: add erlang to asdf deps.

---

.github/workflows/elixir-ci.yml

So that we don't need to run elixir CI on actions changes

chore: exclude ci-related files from elixir ci

---

.github/workflows/trigger-cloudbuild.yml

Fix for cloudbuild triggering, which looks like it is failing due to multi-line json env being set.
Directly using the json credentials in the auth step instead.
🤞 hope this fixes it

chore: fixes cloudbuild trigger

---

.github/workflows/docker-ci-amd-and-arm.yml

This cancels in-progress jobs, so that we don't waste time waiting for multiple jobs to be done when we only need the latest build for staging builds.
should not affect master builds as we do releases separately.

chore: cancel in-progerss jobs for multi-platform build

---

lib/logflare/sql_v2.ex
test/logflare/sql_test.exs
test/support/test_utils.ex

This fixes the fully qualified naming issue where sources with the same naming pattern as bigquery entities were getting disallowed.
This PR changes the logic and takes a different approach. Instead of explicitly checking for disallowed specific patterns  (i.e. disallow-listing), we reverse the checking logic to allow-list certain patterns and treat everything else as an unknown entity. This makes the logic much easier to read and less prone to bugs, since the allow-list conditions are very clear.
I have added in tests for naming patterns that are similar to the bigquery entity naming pattern to ensure we transform everything correctly.
Included in this PR is also additional tests for single tenant mode and fully-quallified names, ensuring that users that set a global bigquery project …

fix: fully qualified names cte fixes

---

assets/js/LogEventsChart.jsx
assets/js/app.js
assets/js/source_lv_hooks.js
lib/logflare_web/live/search_live/templates/logs_search.html.heex

fixes a timestamp parsing bug, where for the user local timestamp was not getting parsed correctly via a `data-` attribute.
Removed the unnecessary data passing around and directly passed timezone in props.
Also a little refactoring for props passing and using `pushEvent` for calling liveview events. 
https://github.com/Logflare/logflare/assets/22714384/d88f1e1d-32b9-4e16-8ff7-b2766db5f1f3

fix: bar chart timestamp parsing bugfix

---

test/logflare_web/controllers/oauth_controller_tests.exs

This PR adds additional test coverage for the Oauth2 bug when cloudflare app redirects. 
Fix is implemented in our fork of PhoenixOauth2Provider, whose tests does not account for Application level configs.
The conn.private phoenix_view format had changed in Phoenix 1.7 and this had resulted in a breakage in behaviour.
the bugfix as implemented  in [this commit](https://github.com/Logflare/phoenix_oauth2_provider/commit/36e757920e54bffa0f603bf985aff91bb8b28f2d) essentially new pattern match for the new phoenix version, while retaining the old match format for older versions.
We can PR to upstream as well, but upstream seems unmaintained at the moment and it would only affect projects >= phoenix 1.7, which is not supported yet on upstream.

fix: oauth2 callback redirect fix

---

lib/logflare/application.ex
lib/logflare/backends/adaptor/postgres/repo.ex
lib/logflare/backends/adaptor/postgres/repo/migrations/add_log_events.ex
test/logflare/backends/adaptor/postgres/repo_test.exs

To properly support users, we need to migrate whatever changes are needed to support postgres backends
On connection, we will run migrations against the URL provided

add - Move from SQL to Migrations

---

run.sh

Adds a new env var to be used in instance groups to override the magic cookie env var in the secrets file

add - Override magic cookie via env var

---

lib/logflare/sources/source.ex
lib/logflare_web/live/search_live/logs_search_lv.ex
lib/logflare_web/templates/source/edit.html.eex
priv/repo/migrations/20230622160150_add_suggested_fields_to_sources.exs
priv/repo/migrations/20230622160250_set_suggested_fields_default.exs
test/logflare_web/live/search_live/logs_search_lv_test.exs

Suggestion fields can now be added to sources so users can define which fields are suggested to achieve the best performance.
This can be bypassed if the user desires.

add - Suggestion field for sources

---

test/test_helper.exs

Noticed that tests were emitting these errors:
```
01:38:12.079 erl_level=error application=finch domain=elixir file=lib/finch/http2/pool.ex function=disconnected/3 line=233 mfa=Finch.HTTP2.Pool.disconnected/3 module=Finch.HTTP2.Pool pid=<0.5735.0> [error] Failed to connect to https://bigquery.googleapis.com:443: timeout
```
This PR will prevent all outgoing requests using the api clients.

chore: prevent api requests during tests

---

lib/logflare_web/controllers/plugs/fetch_resource.ex
test/logflare_web/controllers/endpoints_controller_test.exs

[ticket](https://www.notion.so/supabase/bug-Logflare-endpoint-query-by-name-sometimes-mistakes-a-string-for-a-uuid-0034097613954fafab27ed608e287f70?pvs=4)
Bug relates to endpoint names getting mistaken as raw uuids when using Ecto.cast. By using Ecto.dump, we can more consistently check if a string is a uuid.

fix: prevent name that is raw uuid to be mistaken  as endpoint token

---

run.sh

This PR moves the GCE-related networking sleep to the gce if block so that it does not block self-hosting.

fix: move gce networking specific sleep to gce block

---

lib/logflare/endpoints.ex
lib/logflare/endpoints/query.ex
lib/logflare_web/live/endpoints/actions/index.html.heex
lib/logflare_web/live/endpoints/endpoints_live.ex
test/logflare/endpoints_test.exs
test/logflare_web/live_views/endpoints_live_test.exs

This PR adds cache counts to the Endpoints index page.
This is the first step to live stats for endpoints.
The PR depends on #1541 
[ticket](https://www.notion.so/supabase/feat-display-cache-count-for-each-endpoint-in-index-page-c927581815d74833af62b28110c9f8ee?pvs=4)

feat: cache count endpoints index

---

lib/logflare/endpoints/query.ex
lib/logflare_web/live/endpoints/components/endpoint_form.html.heex
lib/logflare_web/live/endpoints/endpoints_live.ex
test/logflare_web/controllers/api/endpoint_controller_test.exs

* On save, the lack of a default language on Query creation made a changeset fail
* On query test, the input would be deleted since the value was not being set and assigns were being removed
> Note: Endpoints are behaving weirdly due to other reasons in my dev environment so take that into account in the gifs below 😅

fix - Fixes endpoints UI on save and on query run bugs

---

lib/logflare/application.ex
lib/logflare/single_tenant.ex

Avoids schema update when using Postgres as a backend since this makes the CLI fail.

fix - Avoid Schema update when using Postgres as a backend

---

lib/logflare/single_tenant.ex
test/logflare/single_tenant_test.exs

Takes into account that at the moment the Postgres Backend does not use Schemas

fix - Adapt healthcheck for Postgres backend

---

lib/logflare/sql.ex
test/logflare/sql_test.exs

this PR adds in two translation aspects:
- multiple from aliases field referencing, such that the table aliases are considered and omited/added to the json query syntax.
- cast handling, as json cannot be used to cast, hence we need to use LongArrow or HashLongArrow for the syntax

feat: bq-to-pg translation, cte handling and value casting

---

lib/logflare_web/live/endpoints/actions/show.html.heex
lib/logflare_web/live/endpoints/components/endpoint_form.html.heex
priv/repo/migrations/20230727111150_update_endpoint_query_language_default_value.exs
test/logflare_web/live_views/endpoints_live_test.exs

This PR fixes endpoint updating, where the existing field is null.
As an additional measure, I've added in a migration to fill in the default values and enforce not null

fix: endpoints edit ui - nil language update error

---

config/runtime.exs
lib/logflare/backends/adaptor/postgres_adaptor/pg_repo.ex
test/logflare/backends/postgres_adaptor_test.exs

Fix usage of Schemas when using Postgres Backends by:
* Use a new env var to properly setup the schema for Single Tenant mode
* Create schema on connect instead of migrations
* Remove prefix from log insertion since it should not be needed

fix: custom schema postgres backend creates schema correctly

---

lib/logflare/backends/adaptor/postgres_adaptor/pg_repo.ex

When using schemas, we required the prefix to be set on the LogEvent changeset so it knows where to be inserted

fix - Add prefix to log events inserted in Postgres Backend

---

lib/logflare/backends/adaptor/postgres_adaptor/pg_repo.ex
lib/logflare/endpoints.ex
lib/logflare/single_tenant.ex
lib/logflare/sql.ex
priv/supabase/endpoints/logs.all.sql
test/logflare/backends/postgres_adaptor_test.exs
test/logflare/single_tenant_test.exs
test/logflare/sql_test.exs
test/logflare_web/controllers/endpoints_controller_test.exs
test/support/test_utils.ex

Implements BQ sql translation when both supabase mode and postgres backend is enabled.
Fixes the following areas for BQ->PG translation:
- table name translation
- CTE order by translation
- parameter replacement to positional
- CTE table/field referencing behaviour

feat: sql translation supabase mode

---

lib/logflare_web/live/endpoints/components/endpoint_form.html.heex

Increases the size of the Query textarea in the Endpoints UI form.

fix - Increases text area for Queries in Endpoints

---

lib/logflare/backends/adaptor/postgres_adaptor/repo/migrations/add_log_events.ex

`event_message` on LogEvent was using :string types which enforces a limit of 255 chars. Changing it to :text to use a type with no char limit

fix - Use Text instead of String on event_message

---

lib/logflare/sql.ex
test/logflare/sql_test.exs

When global project id is not set, the regex replacement fails.

fix: malformed name translation when global project id is not set

---

priv/supabase/endpoints/logs.all.sql

This PR correctly casts timestamp parameters in the logs.all endpoint.
Note: the endpoint query deviates from  prod due to tight timeline.

fix: correctly cast timestamp parameters

---

lib/logflare/endpoints.ex
lib/logflare/sql.ex
test/logflare/sql_test.exs
test/logflare_web/controllers/endpoints_controller_test.exs
test/support/test_utils.ex

This PR explicitly prefixes a postgres table name with the schema prefix.
This does not prevent issues where the accessing user does not have permissions, but it mitigates search path issues.
```sql
-- before
select id from "log_events_123a_234f_r43fs"
-- after, with a schema called my_schema
select id from "my_schema"."log_events_123a_234f_r43fs"
```

feat: explicit schema prefixing for translated queries

---

lib/logflare/application.ex
lib/logflare/backends/adaptor/postgres_adaptor.ex
lib/logflare/backends/adaptor/postgres_adaptor/pg_repo.ex
test/logflare/backends/postgres_adaptor_test.exs
test/logflare/endpoints_test.exs

Previously PgRepo was changing concurrently multiple times a single module configuration leading to issues when creating tables and migrations for a given source.
To fix this, in a weird, we added more concurrency.
PgRepo now is a GenServer per Repository which means that migrations are handled by a single mailbox that is able to properly coordinate actions.

fix - Move PgRepo to a GenServer to avoid race conditions

---

lib/logflare/sql.ex
lib/logflare_web/views/endpoints_view.ex
test/logflare/sql_test.exs
test/logflare_web/controllers/endpoints_controller_test.exs

This PR retains timestamp selection within the projection ast, so that timestamp rendering behaviour is kept to using unix microseconds.

fix: translation for timestamp field should not convert to iso timestamp

---

lib/logflare/sql.ex
test/logflare/sql_test.exs
test/logflare_web/controllers/endpoints_controller_test.exs

Fix for CTE table alias handling for outside of CTE.
Expected translation behaviour is as so:

fix: cte table alias handling for compound identifier for translations

---

lib/logflare/backends/adaptor/postgres_adaptor.ex
test/logflare/backends/postgres_adaptor_test.exs

This PR adds in array nested to the postgres adaptor to mimic bigquery querying behaviour.
This might change in a future version as we may remove this array nested to standardize payload returning across backends (and follow the ingested json structure as close as possible)

fix: query results should be nested in an array to mimic bigquery behaviour

---

lib/logflare/single_tenant.ex

Due to the way we were checking which backend to load in single tenant mode when we wanted to use BigQuery it was failing.

fix - Using single tenant with BigQuery failing to start

---

lib/logflare_web/live/endpoints/actions/show.html.heex

This PR fixes a typo for querying an endpoint by name.

fix: curl by name typo

---

lib/logflare/application.ex
lib/logflare/erl_sys_mon.ex
lib/logflare/system_metrics/system_metrics_sup.ex
rel/vm.args.eex

I verified on prod this won't create excess log messages in normal ops:
```elixir
iex> :erlang.system_monitor(self(), [:busy_dist_port, :busy_port, {:long_gc, 1_000}, {:long_schedule, 100}])
iex> flush()
```

fix: log dist buffer and increase dist buffer limit

---

lib/logflare/source/slack_hook_server/client.ex
lib/logflare/source/webhook_notification_server/discord_client.ex

This PR removes the "Thanks for using Logflare" footer, as feedbacked by users.

chore: remove footer messages

---

docs/docs.logflare.com/docs/concepts/lql/index.md
lib/logflare/logs/lql/lql_parser.ex
lib/logflare/logs/lql/lql_parser_helpers.ex
test/logflare/lql/lql_parser_test.exs

This PR fixes escaped double quotes parsing behaviour for regexp in LQL search queries.

fix: lql parsing of escaped double quotes for regex

---

docs/docs.logflare.com/docs/concepts/endpoints.md
docs/docs.logflare.com/docs/concepts/ingestion/index.mdx
lib/logflare_web/api_spec.ex
lib/logflare_web/controllers/endpoints_controller.ex
lib/logflare_web/controllers/log_controller.ex
lib/logflare_web/open_api.ex
lib/logflare_web/open_api_schemas.ex

This PR adds in the main `/api/logs` and `/api/endpoints/query` routes.
I have also added in filtering logic to only display routes that begin with the `/api` prefix.
note: the `/api/endpoints/query/name` route is to be removed in separate PR.

feat: OpenAPI routes updating - Ingestion, Querying

---

priv/repo/migrations/20230727111150_update_endpoint_query_language_default_value.exs

This removes the github compilation warning, as shown in this PR [here](https://github.com/Logflare/logflare/pull/1701/files)

chore: remove github compilation warning

---

test/logflare/alerting_test.exs

cron expression validation test was resulting in issues with ci tests.

chore: fix flaky cron validation test

---

lib/logflare_web/live/endpoints/actions/show.html.heex

This removes the duplicate name when viewing a logflare endpoint

chore: remove endpoint name duplication

---

lib/logflare/application.ex

add partitioning for unique Registry.
Adding partition for duplicate key Registry has minimal benefits as all partitions would need to be looked up

perf: add Registry partitioning for v2 ingest pipeline

---

lib/logflare_web/live/endpoints/actions/index.html.heex
lib/logflare_web/live/endpoints/endpoints_live.ex
test/logflare_web/live_views/endpoints_live_test.exs

so that one does not need to check each endpoint individually 
PR also adds in a bug fix for ensuring index page is always refreshed when navigated to.

feat: display whether endpoints auth is enabled on index page

---

lib/logflare/sql.ex
test/logflare/sql_test.exs
test/logflare_web/live_views/alerts_live_test.exs

Errors when saving alerts is not thrown, resulting in a full page refresh instead of feedback to the user. 
occurs only when sql parser cannot parse the query.

fix: sql parser error on save is not returning correct error tuple

---

lib/logflare_web/live/alerts/alerts_live.ex
lib/logflare_web/live/alerts/components/alert_form.html.heex

Alerts ui does not show correct changset data.
Fixes the changeset bug which was referencing Endpoints.

fix: Alerts changeset bug referencing Endpoints instead of AlertQuery

---

config/runtime.exs

fix for otp26 cacert changes
see:
- https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/ssl
- https://elixirforum.com/t/httpoison-error-sending-a-mail-with-brevo-options-incompatible-verify-verify-peer-cacerts-undefined/57129/7

fix: add hostname check for wildcard cacert

---

config/runtime.exs

potential fix for unknown CA error for postgrex:
```
1:23:48.042 [notice] TLS :client: In state :certify at ssl_handshake.erl:2138 generated CLIENT ALERT: Fatal - Unknown CA 
```
I've also separated out ssl changes to only the db connnection, as it is the one that is erroring out.

chore: add depth option for ssl opts

---

.github/workflows/elixir-ci.yml
DEVELOPMENT.md
Makefile
mix.exs

Using `mix cmd` for long running tasks is problematic, as killing such process will later leave zombies running in the background which can affect the ability to retry such commands (especially visible with `mix start`). This instead use `make` to run such commands.
This change also adds dependency tracking to the decryption of the secrets, which mean that we can try to decrypt them on each run and prevent accidentally running application with old secrets.

chore: move task running to Makefile

---

lib/logflare/backends.ex
lib/logflare/backends/adaptor.ex
lib/logflare/backends/adaptor/postgres_adaptor.ex
lib/logflare/backends/adaptor/webhook_adaptor.ex
test/logflare/backends/webhook_adaptor_test.exs

This moves dynamic calls to inside of behaviour module to have coherent view on how behaviour will be used. Additionally this remove the code duplication that happened with template functions and reduce the compilation times (no compile time dependency).

chore: reorganise backend adaptor behaviour

---

config/prod.exs

fix for wrong option:
```
11:56:45.121 [notice] Application logflare exited: Logflare.Application.start(:normal, []) returned an error: shutdown: failed to start child: LogflareWeb.Endpoint
** (EXIT) shutdown: failed to start child: {LogflareWeb.Endpoint, :http}
** (EXIT) an exception was raised:
** (RuntimeError) Unsupported keys(s) in thousand_island_options config: [:max_connections]
(bandit 0.7.7) lib/bandit.ex:382: Bandit.validate_options/3
(bandit 0.7.7) lib/bandit.ex:288: Bandit.start_link/1
(stdlib 5.1.1) supervisor.erl:420: :supervisor.do_start_child_i/3
(stdlib 5.1.1) supervisor.erl:406: :supervisor.do_start_child/2
(stdlib 5.1.1) supervisor.erl:390: anonymous fn/3 in :supervisor.start_children/2
(stdlib 5.1.1) supervisor.erl:1258: :supervisor.children_map/4
(stdlib 5.1.1) …
```

fix: update thousand island options

---

Makefile

Seems like europe-west3 works, but us-central1 doesn't. Very weird, seems like a data center issue.

chore: switch to europe-west3 for staging deploys

---

Makefile

shift staging builds to europe-west2 because internal error bug is popping up again.

chore: update 2nd gen repo location

---

lib/logflare/alerting.ex
lib/logflare/endpoints.ex
lib/logflare/endpoints/query.ex
lib/logflare/sql.ex
test/logflare/alerting_test.exs
test/logflare/endpoints_test.exs
test/logflare/sql_test.exs

Nesting endpoints within endpoints, or endpoints in alerts....

feat: query composition

---

config/runtime.exs
config/test.exs
lib/logflare_web/controllers/plugs/verify_api_access.ex
test/logflare_web/controllers/log_controller_test.exs

This PR fixes a bug in the rate limiter which requires `:sources` key to be preloaded for the User struct

fix: preload sources for VerifyApiAccess plug

---

priv/repo/migrations/20231027221103_revert_sandbox_query_id_column_removal.exs

This PR reverts the non-backwards compatible migration where the `sandbox_query_id` column was removed without backwards compat for rolling updates

chore: revert sandbox query id removal

---

.formatter.exs
lib/logflare_web/live/admin/partner_live.html.heex
lib/logflare_web/live/alerts/actions/edit.html.heex
lib/logflare_web/live/alerts/actions/show.html.heex
lib/logflare_web/live/alerts/components/alert_form.html.heex
lib/logflare_web/live/billingaccount_live/custom_field_component.ex
lib/logflare_web/live/billingaccount_live/payment_method_component.ex
lib/logflare_web/live/billingaccount_live/templates/edit.html.heex
lib/logflare_web/live/endpoints/actions/edit.html.heex
lib/logflare_web/live/endpoints/actions/show.html.heex
lib/logflare_web/live/endpoints/components/endpoint_form.html.heex
lib/logflare_web/live/modal_component.ex
lib/logflare_web/live/search_live/templates/debug.html.heex
lib/logflare_web/live/search_live/templates/logs_list.html.heex
lib/logflare_web/live/search_live/templates/logs_search.html.heex
lib/logflare_web/live/search_live/templates/user_prefs_component.html.heex
lib/logflare_web/live/source_backends_live.ex
lib/logflare_web/templates/layout/inline_live.html.heex
lib/logflare_web/templates/layout/live.html.heex
lib/logflare_web/templates/log/log_event_body.html.heex
lib/logflare_web/templates/shared/bq_schema.html.heex
lib/logflare_web/templates/shared/modal.html.heex

This PR fixes curl formatting for endpoints
Before:
After:

chore: fix curl example formatting

---

lib/logflare/application.ex
lib/logflare/google/bigquery/gen_utils/gen_utils.ex
test/test_helper.exs

Adds in the following Goth tweaks:
- telemetry span for fetch execution
- partitioning, had to hack around Goth's internal use of registry.
- shifted Goth up in the sup children
- reduced retry cap to 10s, added logging as well
- made server startup to be sync so that it fetches token on startup before continuing.

fix: adds goth partitioning, telemetry, adjustment in application children  position, options tweaks

---

lib/logflare/sql.ex
test/logflare/sql_test.exs

This PR fixes postgres translations relating to the `InList` BinaryOp.
Comparisons should be typecasted to text to handle list value comparisons

Fix/postgres translation errors UI filtering for list comparisons

---

config/config.exs
config/prod.exs

tweaks metadata logging, seems like gcp is not receiving the metadata key still

chore: fix logger json backend metadata filtering

---

.github/workflows/docker-ci-amd-and-arm.yml

This adjusts the docker build to ensure that in progress builds are not cancelled.

chore: allow concurrency for docker ci for building on each merge

---

.github/workflows/docker-ci-amd-and-arm.yml

fix for triggering rebuilds of versioned image on workflow dispatch.
Currently we don't have v1.5.4 image built yet on dockerhub, causing downstream cloudbuild workflow to fail.

chore: allow versioned building on workflow dispatch

---

.github/workflows/docker-test.yml
.github/workflows/elixir-ci.yml
cloudbuild/staging/deploy.yaml

e2-standard-8 is quite expensive (almost US$200 per node per month, lets try with e2-standard-4 first before going with higher vcpus.
also adds in some ci improvements

chore: use e2-standard-4 for load test cluster

---

lib/logflare/source/recent_logs_server.ex
test/logflare/source/bigquery/buffer_test.exs
test/logflare_web/controllers/endpoints_controller_test.exs

This error gets thrown when the RLS does not start up fast enough for incoming requests. This change ensures that the startup of the critical genservers are performed in the init and is blocking.

fix: :buffer_counter_not_found bug

---

lib/logflare/source/bigquery/buffer_counter.ex
lib/logflare/source/bigquery/buffer_producer.ex

This bumps up the buffer size, to manage spikes due to large batches better.
It is quite unlikely that source events would hit this level of queuing, but it is not impossible given current growth.
This future proofs broadway buffering while optimizations are being made.

feat: tweak buffer size

---

Makefile

Seems like the error trapping breaks versioned retagging ci
https://github.com/Logflare/logflare/actions/runs/6948416156
might be due to the `-e` option set on GH actions by default, but since it is not really necessary, removing.

chore: remove err trapping

---

lib/logflare/source/bigquery/pipeline.ex
test/logflare/logs/logs_test.exs

This PR doubles the batch size for each streaming insert. It also reduces the batch timeout slightly, so that flushing occurs slightly faster.
On dev, this effectively doubles throughput.
Also adds in a max_restart option, to prolong restart attempts in the event pipeline goes down due to api errors.

feat: tweaks broadway pipeline batch size, batch timeout

---

Makefile

Small typo, accidentally left a trailing single quote.

fix: quoted string bug for retagging GH workflow

---

lib/logflare/logs/processor.ex

Metadata should not include entire structs, as this metadata would eventually get sent to Logflare staging as is.

chore: include only source identifiers  in metadata.

---

lib/logflare/source/bigquery/pipeline.ex

This reverts the broadway max batch size, as discussed. We will add more metrics around this before deciding to increase the batch size as a means for increasing throughput.

fix: revert batch size

---

lib/logflare/cluster/utils.ex
lib/logflare/system_metrics/cluster_size.ex
lib/logflare/system_metrics/system_metrics_sup.ex

This PR moves the cluster warning to a period 10s check, together with a telemetry event.
This reduces log emission on high request load, as cluster warning log was being emitted on each rate limit check

feat: switch cluster warning to telemetry poller

---

lib/logflare_web/live/endpoints/components/run_query_form.heex
lib/logflare_web/live/endpoints/endpoints_live.ex
test/logflare_web/live_views/endpoints_live_test.exs

This persists endpoint query params form values for testing usability.

feat: persist endpoint query params form values

---

lib/logflare/logs/search/logs_search_queries.ex

This fixes case sensitivity in the metadata.level counting, closes #1817

fix: case sensitivity for generated chart queries

---

rel/env.sh.eex

Ensures that the node host value is always set so that the server can start with long node name.
Closes #1807

fix: default node host value

---

Makefile
cloudbuild/prod/pre-deploy.yaml
cloudbuild/shutdown.sh
cloudbuild/staging/deploy.yaml

This PR adds in the shutdown script to CD, and uses env vars instead of hardcoded values.

chore: shutdown script for instance template deployments

---

.github/workflows/docker-ci-amd-and-arm.yml
Makefile

This PR adds two changes to the CI:
- removal of the redundant docker image pushing on the retagging script
- adjusting the intermediate mutli-arch image tags to make it clear that they are dev images.

chore: refactor docker ci

---

.gcloudignore

gcloudignore was ignoring the shutdown script file. This ensures that the entire directory is added to the tarball on run of `gcloud build submit`

fix: gcloud ignore only takes the cloudbuild dir

---

cloudbuild/prod/pre-deploy.yaml
cloudbuild/shutdown.sh
cloudbuild/staging/deploy.yaml

Increase min ready time for staging to let nodes be more stable before shutting down old nodes.
Drop cluster size to allow for 2 node canarying.
fix shutdown script which is breaking the node shutdown.

chore: fix shutdown scripts, drop min cluster size for prod, and increase staging min ready time

---

.gcloudignore

deps folder is not ignored, so triggering the build locally causes issues.

chore: gcloud should ignore deps folder

---

lib/logflare/logs/search/logs_search_operations.ex

Bug: if source schema gets cached incorrectly it can prevent you from querying a field even though the field is present when you view the schema.
This should fix that.

fix: don't hit SourceSchemas cache here

---

lib/logflare/logs/logs.ex
lib/logflare_web/controllers/plugs/rate_limiter.ex
lib/telemetry.ex

This PR adds in telemetry ingestion metrics:
- rate limiter drop rate
- ingest  counts by source
This also tweaks the metrics for batch size counting by adjusting the tags to be by source.

feat: telemetry ingestion api stats

---

lib/logflare/billing.ex
lib/logflare/sources.ex
lib/logflare_web/templates/shared/dashboard_source_metadata.html.eex
lib/logflare_web/templates/source/dashboard.html.eex
lib/logflare_web/views/source_view.ex
test/logflare_web/controllers/source_controller_test.exs

This display source ttl in the dashboard, which would help dx.
This is a result from internal feedback and customer feedback, and should make a source TTL more obvious to the dev managing the source.

feat: display source ttl

---

lib/logflare_web/templates/shared/dashboard_source_metadata.html.eex

This removes the cached count and tweaks the rate metrics display.
Depends on #1872

style: tweak formatting of rate, remove cached.

---

run.sh

Sets kernel.nmi_watchdog=1 so we can see if GCP is soft locking our CPUs.
Context:
- https://blog.railway.app/p/gcp-incidents
- https://stackoverflow.com/questions/49495429/google-cloud-engine-kernelnmi-watchdog-bug-soft-lockup
- https://medium.com/@yildirimabdrhm/nmi-watchdog-on-linux-ae3b4c86e8d8
To test I enabled it on this canary box: 10.156.0.56
Should maybe see logs for:
`kernel: NMI watchdog: BUG: soft lockup`

fix: set kernel.nmi_watchdog=1

---

assets/css/dashboard.scss
lib/logflare/teams.ex
lib/logflare_web/controllers/plugs/set_team.ex
lib/logflare_web/controllers/plugs/set_verify_source.ex
lib/logflare_web/controllers/team_user_controller.ex
lib/logflare_web/templates/error/403_page.html.eex
lib/logflare_web/templates/error/403_page.html.heex
test/logflare/teams_test.exs
test/logflare_web/controllers/api/team_controller_test.exs
test/logflare_web/controllers/source_controller_test.exs
test/support/factory.ex

This PR adds in user prompting to switch teams when encoutering 403, most common when viewing a different team's source.
It also adds redirection to the resource on profile switch, for less clicks needed.
This PR also resolves some bugs found in the Teams context.
https://github.com/Logflare/logflare/assets/22714384/f217defb-0bbb-4a2b-8d4e-9de68218d01a

fix: prompt user to switch teams on 403

---

lib/logflare/account_email.ex
lib/logflare/source/bigquery/schema.ex
test/logflare/source/bigquery/schema_test.exs

Getting lots of errors for:
```
no function clause matching in Logflare.AccountEmail.schema_updated/4 (logflare 1.4.5) lib/logflare/account_email.ex:113: Logflare.AccountEmail.schema_updated(nil, %Logflare.Source{__meta_
```

fix: nil email for team_user

---

lib/logflare_web/controllers/api/partner/user_controller.ex
lib/logflare_web/router.ex
test/logflare_web/controllers/api/partner/user_controller_test.exs
test/support/conn_case.ex

- renames AccountController to UserController to match resource name
- adds GET users metadata filtering, relies on #1879

feat: Partners.UserController metadata filtering

---

cloudbuild/prod/pre-deploy.yaml
cloudbuild/staging/deploy.yaml

This PR adds in auto deploys to canary instance group, as well as adjusts instance templates to terminate on host maintenance.
Cluster cookie is set based on the cluster name substitution.

chore: canary auto deploy

---

lib/logflare/partners.ex
lib/logflare/partners/cache.ex
lib/logflare_web/controllers/plugs/verify_api_access.ex
test/logflare_web/plugs/verify_api_access_test.exs

This PR allows partners to impersonate users when querying the management api. Requires partners to have the user token uuid.
depends on #1878

feat: partner api - allow impersonation of user

---

lib/logflare/google/bigquery/gen_utils/gen_utils.ex
lib/logflare_web/views/source_view.ex
test/logflare_web/controllers/source_controller_test.exs

This PR adjusts the rendering logic for source ttl, the `source.bigquery_table_ttl` field is in days, whereas the plan value is in ms.

fix: ttl dashboard display

---

Makefile
cloudbuild/staging/deploy.yaml

Seems like there are some restrictions with e2 instances, this switches all staging instances to `c2d-standard-2`, and reduces disk size to match prod at 25GB. This brings the per-instance cost to around US$68, so we can spin up a few more for better simulation of prod.

fix: test cluster machine types, disk size

---

lib/logflare/application.ex

This reverts commit 16a5bc146c31b1f0d1d5f22bee5eb8e9322627db.
This is a tenative fix for the max concurrent streams issue that we are facing when deploying

Revert "perf: reduce http2 pools to reduce chance of server throttling."

---

assets/js/app.js
lib/logflare_web.ex
lib/logflare_web/core_components.ex
lib/logflare_web/live/access_tokens_live.ex
lib/logflare_web/templates/source/dashboard.html.eex
test/logflare_web/live/access_tokens_live_test.exs
test/support/factory.ex

This PR improves the access tokens management ui, for transitioning from global ingest tokens.
https://github.com/Logflare/logflare/assets/22714384/4bdb874c-689b-4990-b717-d4288636bae6

feat: access tokens management ui

---

lib/logflare_web/router.ex

This increases the accepted byte length per request, to allow for integration with tooling that default to 10MB batching (vector)

feat: increase accepted byte length

---

lib/logflare/logs/source_parsers/syslog_parser.ex
lib/logflare/logs/source_parsers/syslog_parser_helpers.ex
test/logflare/source_parsers/syslog_parser_test.exs

This PR fixes syslog parser errors due to trailing spaces.

fix: syslog events with trailing spaces are not being parsed correctly

---

cloudbuild/secret_setup.Dockerfile

This fixes installation of tini on cloudbuild
https://github.com/Logflare/logflare/actions/runs/7446084745/job/20256142362

fix: tini installation on cloudbuild

---

cloudbuild/prod/pre-deploy.yaml
cloudbuild/staging/deploy.yaml

apparently it is not a valid option despite being generated in the gcp console.

chore: remove provisioning-model option

---

config/config.exs
config/dev.exs

This PR adds in equivalent cowboy http server options, for high load optimizations.

fix: restore http server options for bandit migration from cowboy

---

lib/logflare/application.ex

This PR adds in a FinchGoth pool that is separate from FinchDefault.
This also drops the FinchDefault count to 50, which is the same as v1.4.4.
The goal of this is to eliminate the possibility that the FinchDefault change to `count: 150` is causing the higher disconnections from the gcp apis, and also isolates the Finch changes since v1.4.4.
As Goth only uses the pool to refresh tokens, it is not needed to have high counts.
We had only customized it as by default it will use http

chore: revert FinchDefault changes, separate FinchGoth pool

---

lib/logflare/logs/rejected_log_events.ex

This should scale a little bit better in case of larger caches as it will compute the values lazily as long as possible.

ft: use stream processing of Cachex stream

---

lib/logflare_web/controllers/plugs/bert_parser.ex
lib/logflare_web/controllers/plugs/json_parser.ex
lib/logflare_web/controllers/plugs/ndjson_parser.ex
lib/logflare_web/controllers/plugs/syslog_parser.ex
lib/logflare_web/router.ex
test/logflare_web/controllers/log_controller_test.exs
test/logflare_web/plugs/bert_parser_test.exs
test/logflare_web/plugs/ndjson_parser_test.exs

This PR adds in a JsonParser. 
It replaces the built in `Plug.Parsers.JSON` module, and adjusts the error handling for when attempting to decode the body, so that errors from the body reader is surfaced correctly in error messages instead of being discarded.
Also does some minor changes in module naming to make it clear that they are not built in modules.

fix: better error handling for JsonParser

---

lib/logflare/source/bigquery/buffer_counter.ex

At 40k buffer length, the ram consumed can balloon to over >1GB.  
This can put the node at risk by consuming all available memory if there is sudden high load across many sources
SS was taken from load test cluster, where sources were at or near max buffer length.

chore: revert max buffer length

---

cloudbuild/prod/pre-deploy.yaml
cloudbuild/staging/deploy.yaml
config/runtime.exs
docs/docs.logflare.com/docs/self-hosting/index.md

This adds cluster names to logs to ensure ability to filter

chore: add LOGFLARE_LOGGER_METADATA_CLUSTER for adding global metadata

---

lib/logflare/source/bigquery/pipeline.ex

This reverts processor concurrency and max_restarts options, which could be the cause of the `:long_schedule` issues

chore: revert pipeline changes for processor concurrency

---

rel/vm.args.eex

https://erlangforums.com/t/vm-tuning-guide/1945/4
as well as [rabbitmq advice](https://www.rabbitmq.com/runtime.html#busy-waiting)
COS is also linux based, which also has CFS since it was merged to linux kernel in 2007.
docker image is on debian, which uses CFS.
Some other discussions backing this up:
- https://stressgrid.com/blog/beam_cpu_usage/
- https://elixirforum.com/t/any-tips-on-tuning-the-beam-vm/51038/4?u=ziinc

fix: disable busy wait

---

config/config.exs
config/dev.exs
config/prod.exs

Reverts bandit usage, so that we can isolate whether it is bandit causing scheduler issues.

fix: revert bandit

---

lib/logflare/sources.ex
lib/logflare_web/controllers/health_check_controller.ex
test/logflare/sources_test.exs
test/logflare_web/controllers/health_check_controller_test.exs

Health check for ETS tables is now needed, due to race conditions in startup time.

fix: health check for ETS ingestion tables

---

lib/telemetry.ex

This PR adds Goth.fetch telemetry metrics to the livedashboard.

chore: add Goth fetch duration to metrics monitoring

---

lib/logflare/team_users.ex
test/logflare/team_users_test.exs

This PR adds in some performance enhancements for `TeamUsers.list_team_users_by_and_preload/1`, which gets called on each dashboard load. It is likely the cause of the transaction spikes on each dashboard page load, as each team user results in another repo call, and scales linearly.
To be merged after feature freeze.

perf: refactor TeamUsers.list_team_users_by_and_preload

---

lib/logflare/cache_buster.ex

This PR does some minor refactor to `:telemetry.execute/3` calls, which are syncronous.
Due to number of messages and changes that cache buster receives, this might adversely affect CacheBuster performance.
I also have half a mind of removing the direct `:telemetry.execute/3` calls within the Logflare.Logs module, as it might be adversely affecting ingestion performance, as it is one of the main additions to the Logflare.Logs module since 1.4.x.
However, as we do not have any heavy syncronous handlers attached to telemetry handling, it should not have much significant impact unless someone has a phx live dashboard openede.

chore: refactor telemetry execution

---

lib/logflare/application.ex
lib/logflare/source/recent_logs_server.ex
lib/logflare/source/supervisor.ex
lib/logflare/source/v1_source_sup.ex
test/logflare/logs/logs_test.exs
test/logflare/source/bigquery/buffer_test.exs
test/logflare/sources_test.exs
test/logflare_web/controllers/log_controller_test.exs

This PR refactors the supervision trees out of the RLS, and uses a DynamicSupervisor + Supervisor to ensure that all processes are started up correctly without conflicts.
The `{:error, :buffer_counter_not_found}` error is a result of the RLS starting up only partially. The supervision trees, both initially within `init/1` and `handle_continue/2` were not starting up correctly due to name registration race conditions. On startup, the supervisor thinks that the processes are closed because the RLS genserver terminates first. However, all linked processes will still be in the shutdown phase while a new GenServer gets spun up. When the RLS calls `Supervisor.start_link/2`, it will error out because Registry still have the names registered as alive. However, when attempting to find the RLS …

fix: Use DynamicSupervisor to prevent race conditions in process startup

---

lib/logflare/source/bigquery/buffer_producer.ex

This reduces the max buffer size to double the hardcoded BufferCounter limit. This accommodates for bursting beyond the limit, but not to the point where the memory usage goes out of hand.

fix: max buffer size for producer

---

lib/logflare/source/bigquery/pipeline.ex

This PR doubles the batcher process counts to match scheduler counts. Additionally, it bumps the batch_size up by 100.
In local testing, this effectively almost triples the effective throughput of a source, to a point where my local machine can't even fill the buffer fast enough using loadfest.
Before:
After:
Bigquery insert error increase are negligible in relation to the batch size increase. Turning batch size all the way up to 500 (as per the max recommended in [BQ docs](https://cloud.google.com/bigquery/quotas#streaming_inserts) results in much higher error rate, likely due to timeouts).
Based on [broadway docs](https://hexdocs.pm/broadway/Broadway.html#module-batcher-concurrency), it would fill up processes in a fifo-like manner, minimizing process use where possible. This will then …

perf: optimize batcher throughput via :concurrency and :batch_size

---

Makefile
cloudbuild/prod/deploy.yaml
cloudbuild/prod/pre-deploy.yaml

Adds instance template generation for prod clusters.
Also separates out instance group deployment to a separate file

chore: add prod instance template generation

---

lib/logflare/source/bigquery/schema.ex
test/logflare/source/bigquery/schema_test.exs
test/logflare_web/live/search_live/logs_search_lv_test.exs
test/support/factory.ex

makes Schema update requests async, and removes a lot of dead or unnecessary code.

perf: move schema updates to GenServer.cast

---

lib/logflare/source/bigquery/pipeline.ex
mix.exs
test/logflare/bigquery/pipeline_test.exs

This PR focuses on optimization tuning of broadway for v1 ingest
Using BencheeAsync, the number to look at is **sample size.**
From benchmarks, the optimal config in perfect world conditions with no latency is x2 scheduler count for both processors and batchers.
Once we introduce latency in the bigquery insert, the max throughput then scales linearly with the batcher count. Hence, using `System.schedulers_online() * 3` and x4 and so on will correspondingly increase the overall max throughput.
```
Name                                                                   minimum        maximum    sample size                     mode
:"test benchmarks defaults"                                          0.0830 μs      788.21 μs         1.25 K                 0.125 μs
Name …
```

perf: increase broadway process concurrency

---

lib/logflare/application.ex

This scales the finch pools dynamically based on available schedulers, to reduce idle memory usage.
On dev with 10 cores, process memory dropped from ~500MB to ~130MB. The connection pools only need to scale based on ingest volume, which is correspondingly limited by the scheduler count. 
This should not result in much difference on production, however it means that the connection pools will increase when we beef up servers in the future.
This change will impact self-hosters and supabase cli users the most, as it will drop idle memory consumption for smaller/local setups.

perf: scale finch pools with schedulers to reduce idle memory consumption

---

lib/logflare/backends/adaptor/bigquery_adaptor.ex
lib/logflare/google/bigquery/bigquery.ex
lib/logflare/source/bigquery/buffer_producer.ex
lib/logflare/source/bigquery/pipeline.ex

This reduces the broadway pipeline context to the bare minimum needed for ingestion.
With the other memory fixes, this has dropped the per-processor/batcher/producer process memory from 14-15MB to 3.5-7.5MB

fix: cut down broadway context size

---

lib/logflare/alerting.ex
lib/logflare/backends/adaptor/slack_adaptor.ex
lib/logflare/backends/adaptor/slack_adaptor/client.ex
lib/logflare_web/live/alerts/actions/show.html.heex
test/logflare/alerting_test.exs
test/logflare_web/live_views/alerts_live_test.exs

Fixes for Alerts
- fixes for sending slack alerts
- fixes for oauth2 callback for slack alert webhook integration
- adds alert name to the outbound message

fix: alerts for slack

---

priv/repo/migrations/20240219101411_alter_alert_queries_table_text_field.exs
test/logflare/alerting_test.exs

Fixes a typing error for the `:query` and `:description` column, where queries cannot be saved if they are beyond 255 characters.

fix: alert_queries should use text column types

---

lib/logflare/source/supervisor.ex

This ensures that when a source is explicitly restarted, the context cache is cleared.

fix: explicit cache busting

---

lib/logflare/google/bigquery/gen_utils/gen_utils.ex
lib/logflare/source/bigquery/pipeline.ex

This PR adds in a custom batch_size splitter for handling large log events, and a timeout reduction for ingest to ensure that we catch rate limiting issues earlier.

fix: bq pipeline max length

---

lib/logflare/source/supervisor.ex

Should also include source schemas in the explicit cache bust.

fix: include source schemas in explicit cache bust

---

cloudbuild/prod/pre-deploy.yaml
config/config.exs
config/runtime.exs
docs/docs.logflare.com/docs/self-hosting/index.md
lib/logflare/alerting.ex
test/logflare/alerting_test.exs

This adds in two env vars, `LOGFLARE_ALERTS_MIN_CLUSTER_SIZE` and `LOGFLARE_ALERTS_ENABLED`.
If current cluster size is below the min, then alerts will not send. Alerts can also be disabled cluster-wide as well.

fix: alerts duplication bug, LOGFLARE_ALERTS_MIN_CLUSTER_SIZE

---

.mailmap

The idea here is to make `git blame` a little bit tidier and to unify emails in `git shortlog`.

chore: add mailmap to unify emails in log

---

lib/logflare_web/templates/source/show.html.eex
test/logflare_web/controllers/source_controller_test.exs

This PR fixes a bug where if no `metadata` key is set, the show recent logs page will not display the `event body` toggle, making it hard to see the received payloads

fix: show recent logs should not require metadata key to display event body

---

lib/logflare_web/live/backends_live.ex
test/logflare_web/live/backends_live_test.exs

fix for situation where user_id is stored in session as string when it is a team user

fix: backends user_id parsing for team users

---

lib/logflare_web/controllers/log_controller.ex

**Stack:**
* https://github.com/Logflare/logflare/pull/2004
---
ft: use CloudEvent timestamp for stored events

ft: use CloudEvent timestamp for stored events

---

lib/logflare/backends.ex
lib/logflare/backends/backend.ex
lib/logflare/sources.ex
lib/logflare/sources/source.ex
lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/router.ex
test/logflare_web/controllers/api/backend_controller_test.exs
test/logflare_web/controllers/api/source_controller_test.exs

This PR adds in the adding/removal of source backends to management api.
It also adds in secrets redaction for postgres url when performing json encoding, to ensure that secrets within connection strings are not leaked.

feat: add/remove of source backends, secrets redaction

---

lib/logflare/application.ex

This PR fixes the application tree for PubSubRates, due to refactoring around the cluster-wide pubsub logic in #2012

fix: PubSubRates application tree for non-test env

---

lib/logflare/alerting.ex
lib/logflare/backends/adaptor/webhook_adaptor.ex
test/logflare/alerting_test.exs
test/logflare/backends/webhook_adaptor_test.exs
test/logflare_web/live_views/alerts_live_test.exs

New implementation supports passing headers values that will be sent
in HTTP requests which will allow reusing the same implementation for
different HTTP-based adaptors.

chore: refactor Webhook adaptor

---

lib/logflare/source/billing_writer.ex
test/logflare/source/billing_writer_test.exs

BillingWriter is failing for v2 pipeline as no `:user` and `:plan` args are passed anymore

fix: BillingWriter should not receive user and plan args

---

lib/logflare/alerting.ex
lib/logflare/endpoints.ex
lib/logflare_web/controllers/api/fallback_controller.ex
lib/logflare_web/live/alert_component.ex
lib/logflare_web/live/alerts/actions/show.html.heex
lib/logflare_web/live/alerts/alerts_live.ex
lib/logflare_web/live/alerts/components/run_query_result.html.heex
lib/logflare_web/templates/layout/flash.html.eex
test/logflare_web/controllers/api/query_controller_test.exs
test/logflare_web/live_views/alerts_live_test.exs
test/support/test_utils.ex

Propagates BQ errors to UI and management API.
- 400 err with the error message when calling `/api/query`
- Adds a `Run Query` button with results shown
- Flash is added when query is run with BQ errors, instead of silent failure.
https://github.com/Logflare/logflare/assets/22714384/531c7bf3-3be5-4490-aa05-e3ca44b185c6

fix: BQ errors propagated to ui and api queries

---

priv/repo/migrations/20240327073534_add_cascade_delete_for_partner_users.exs
test/logflare_web/controllers/user_controller_test.exs

Should be able to delete a partner provisioned user

fix: should be able to delete a partner provisioned user

---

lib/logflare/source/bigquery/schema.ex
test/logflare/source/bigquery/schema_test.exs

Fixes situation where invalid TeamUser ids are stored for notifications but is causing Schema process to error out and die.

fix: invalid team users for notification for AccountEmail

---

lib/logflare/backends/adaptor/slack_adaptor.ex
lib/logflare/source/slack_hook_server/client.ex
test/logflare/backends/slack_adaptor_test.exs

This fixes the invalid_blocks errors that slack webhooks return due to invalid markdown. This affects both Legacy Recent Events Alerts and Query Alerts.
New block formatting will look something like this:
For each row, a new block will be used, allowing for intra-slack linking to specific events.
SlackHookServer is also adjusted to use this new block generation logic, as many events are not getting sent to slack channels due to the invalid formatting.

fix: slack invalid blocks

---

test/logflare/log_event_test.exs

Fixes flaky tests where the key was `m` and expanding to `metadata`

chore: fix flaky test relating to metadata expansion

---

lib/logflare/source/supervisor.ex

- tweaks the busy sources bootup window to reduce time-to-healthy

perf: reduce bootup recent update window

---

lib/logflare/backends.ex
lib/logflare/backends/supervisor.ex

This removes the `:global.set_lock` calls that are now obsolete for the v2 pipeline

chore: remove unused recent logs cache

---

lib/logflare/backends/adaptor/slack_adaptor.ex
lib/logflare/source/slack_hook_server/client.ex
test/logflare/backends/slack_adaptor_test.exs

Fixes slack button link block generation, which affects recent events notifications to slack

fix: slack hooks adaptor alerts and recent alerts uses message with CTA.

---

lib/logflare/backends/adaptor/webhook_adaptor.ex
test/logflare/backends/webhook_adaptor_test.exs

This PR adds in batching for the webhook adaptor, and benchmarks for ingestion
```
Name                ips        average  deviation         median         99th %
batch-1         2052.29        0.49 ms   ±251.86%      0.0153 ms        6.13 ms
batch-10         944.49        1.06 ms   ±172.39%      0.0500 ms        6.90 ms
batch-100        653.64        1.53 ms   ±135.53%       0.152 ms        8.05 ms
batch-250        534.37        1.87 ms   ±121.37%        0.56 ms        8.19 ms
batch-500        524.73        1.91 ms   ±120.30%        0.58 ms        8.57 ms
Comparison: 
batch-1         2052.29
batch-10         944.49 - 2.17x slower +0.57 ms
batch-100        653.64 - 3.14x slower +1.04 ms
batch-250        534.37 - 3.84x slower +1.38 ms
batch-500        524.73 - 3.91x slower +1.42 ms …
```

feat: webhook adaptor batching & benchmarks

---

lib/logflare/logs/log_event.ex
test/logflare/log_event_test.exs

Vercel has started to send float timestamps suddenly.

fix: handle floats in timestamp events

---

config/test.exs
test/logflare/source/bigquery/schema_test.exs

This adds Logger filter, that will silence Finch disconnection errors in tests to reduce amount of pollution in the test log.

test: silence Finch errors

---

docs/docs.logflare.com/docs/concepts/endpoints.md
docs/docs.logflare.com/docs/concepts/querying.md

This PR adds in documentation on management API querying.

docs: api for querying logflare

---

lib/logflare/backends/buffer_producer.ex
lib/logflare/pubsub_rates.ex
lib/logflare/source/rate_counter_server.ex
lib/logflare/source/recent_logs_server.ex
test/logflare/cluster_pubsub_test.exs

This fixes flaky broadcast tests, where topic sharding was causing flaky subscription behaviour. 
Topic sharding is no longer required as the broadcast topics are now appropriately partitioned by the PubSub pool size config.

chore: fix flaky topic sharded broadcasting tests

---

assets/js/app.js
lib/logflare_web.ex
lib/logflare_web/core_components.ex
lib/logflare_web/live/log_event_live/search_log_event_viewer_component.ex
lib/logflare_web/live/search_live/logs_search_lv.ex
lib/logflare_web/live/search_live/templates/logs_list.html.heex
lib/logflare_web/live/search_live/templates/logs_search.html.heex
lib/logflare_web/templates/log/log_event.html.heex
lib/logflare_web/templates/log/log_event_body.html.heex
test/logflare_web/live/search_live/logs_search_lv_test.exs

Depends on #2057 
Adds in a permalink to search results for easy sharing of specific log events, as not many are aware of the log event view page.
https://github.com/Logflare/logflare/assets/22714384/86578204-7dec-4952-8367-c868ae9fb1d5

feat: permalink in search results

---

lib/logflare_web/controllers/api/partner/user_controller.ex

This tweaks the default description of the auto-generated access token

fix: adjust name of auto-generated access token

---

lib/logflare_web/live/search_live/templates/logs_list.html.heex
lib/logflare_web/templates/source/show.html.eex

Customer has feedbacked about handling long multi-line strings. Small styling tweak to make it more readable.

fix: multi-line styling fixes

---

config/test.exs
docker-compose.yml
docs/docs.logflare.com/docs/backends/bigquery/index.md
docs/docs.logflare.com/docs/backends/elastic.mdx
docs/docs.logflare.com/docs/backends/postgres/index.md
docs/docs.logflare.com/docs/backends/webhook.mdx
lib/logflare/application.ex
lib/logflare/backends.ex
lib/logflare/backends/adaptor.ex
lib/logflare/backends/adaptor/datadog_adaptor.ex
lib/logflare/backends/adaptor/elastic_adaptor.ex
lib/logflare/backends/adaptor/webhook_adaptor.ex
lib/logflare/backends/backend.ex
lib/logflare/utils.ex
lib/logflare_web/live/backends/components/backend_form.heex
test/filebeat.yml
test/logflare/backends/adaptor/datadog_adaptor_test.exs
test/logflare/backends/elastic_adaptor_test.exs
test/logflare/backends/webhook_adaptor_test.exs
test/logflare/utils_test.exs

This PR adds in filebeat http handling
It also adds in http1 handling, which the filebeat server requires.
deferred:
- gzip
https://github.com/Logflare/logflare/assets/22714384/0e8ce768-837a-465d-baa6-fd2126d3da80

feat: elastic adaptor

---

lib/logflare_web/controllers/auth/email_controller.ex
test/logflare_web/controllers/email_controller_tests.exs

Fix for empty email login submissions when email is empty

fix: add guard for empty email form submissions on email login

---

config/config.exs
config/runtime.exs

This disables trace exporting by default, and becomes enabled only when an endpoint is provided.

fix: disable otel trace exporting by default

---

lib/logflare/backends/source_sup.ex
lib/logflare/cluster/utils.ex
lib/logflare/sources/rules.ex
lib/logflare/sources/source_routing.ex
test/logflare/rules_test.exs

Fixes log drains that do not have the rule child started at ingest time, for situations such as multi-cluster setups (as we have in prod), where a rule is created on one cluster and the startup does not propagate across the cluster.
This also adds in an `:rpc.multicall/3` to ensure that usage rules are started/stopped across the cluster

fix: rule child is started on source routing at ingest time

---

lib/logflare_web/live/search_live/templates/logs_search.html.heex
lib/logflare_web/live/search_live/user_prefs_component.ex
test/logflare_web/live/search_live/logs_search_lv_test.exs
test/support/factory.ex

This PR fixes a bug where the querystring gets replaced by a hardcoded value when the user changes their preferred timezone

fix: timezone preference query string replacement on change

---

lib/logflare/backends/buffer_producer.ex
test/logflare/backends/buffer_producer_test.exs

Add GenStage custom logging for BufferProducer for discards, to identify the sources/backends

feat: GenStage custom logging for producer

---

lib/logflare/source/bigquery/schema.ex
lib/logflare/source/recent_logs_server.ex

This reduces memory consumption for Schema and RecentLogsServer procs, which consume significant amounts of memory (~800-5GB) on high ingestion traffic. This ensures that GCing occurs frequently. These two modules usually on the top of the list for high memory usage on prod.

perf: add spawn_opts and hibernate_after for better memory management

---

lib/logflare/backends.ex
lib/logflare/backends/buffer_producer.ex
lib/logflare/pubsub_rates/buffers.ex
lib/logflare/pubsub_rates/cache.ex
lib/logflare_web/controllers/plugs/buffer_limiter.ex
lib/logflare_web/live/search_live/user_prefs_component.ex
lib/logflare_web/router.ex
test/logflare/backends/buffer_producer_test.exs
test/logflare_web/live/search_live/logs_search_lv_test.exs
test/logflare_web/plugs/buffer_limiter_test.exs

This reverts commit 70bb8d5 and reworks the buffer limiter code:
1. Max buffer length on producer is now 50k, 10x of 5k soft limit. If buffer count is at or above 5k, it will reject incoming requests. This allows for burst requests that occur within the broadcast time interval when count is still below the 5k limit. On local testing, this results in no buffer producer discards occuring on even extremely high ingest rates (>15k/s) 
2. Broadcast interval reduced to 500ms, to ensure that buffer limiter cache data is always up to date. 
3. It fixes some logic for setting of uninitialized bufer cache, which was resulting in all incoming requests getting rejected. Tests have been updated to cover this situation.
Potential improvements in the future:
- reducing and removing zero buffer length …

feat: Buffer limiter v2

---

lib/logflare/source/bigquery/pipeline.ex

Increase fullsweep_after to reduce scheduler time, should reduce `:long_gc` warnings...

perf: increase fullsweep_after for BigQuery pipeline

---

docs/docs.logflare.com/docs/concepts/ingestion/index.mdx
lib/logflare/pubsub_rates/cache.ex
lib/logflare/source/bigquery/pipeline.ex

Adds in ingestion sampling based on local ingestion rates. This greatly reduces memory usage of the Schema module and prevents message queue buildup. In local testing, reduced memory usage by ~50% and reduced message queue buildup from over >11k messages to 0 messages.

perf: add schema sampling based on local ingestion rates on high ingestion volume

---

lib/logflare/backends/buffer_producer.ex
lib/logflare/source/channel_topics.ex
lib/logflare/source/rate_counter_server.ex
lib/logflare/source/recent_logs_server.ex
test/logflare/backends_test.exs
test/logflare/cluster_pubsub_test.exs
test/logflare_web/controllers/health_check_controller_test.exs

Fix for error logging on node startup where SourceSup performs buffer broadcasting.
Error logs itself are unnecessary as if the endpoint goes down, the whole cluster will go down and requests will not get served in any case.

fix: remove Endpoint not up error logging, switch to error tuple

---

lib/logflare/source/recent_logs_server.ex

Increases broadcast count interval by x3. To reduce cross cluster messages. Should have a very minor effect on ux, and will reduce rate of flashing for sources. Having too much count flashing on the ui isn't good for ux anyway, can get distracting at times.

perf: increase insert count broadcast interval

---

lib/logflare/backends/buffer_producer.ex
lib/logflare/backends/buffer_producer/worker.ex
lib/logflare/pubsub_rates/buffers.ex
test/logflare/backends/buffer_producer_test.exs
test/profiling/buffer_producer.exs

This PR adds in the following optimizations for the BufferProducer:
- direct in process caching, instead of local broadcast -> handle_info -> cache
- discard warning log 5 sec backoff, to prevent bursts of warning logs 
- periodic 2.5s cluster length local broadcast
- active/idle interval switching for global (minus local node) broadcasting of buffer length, and accounting for first/last zeros, to reduce cross cluster chatter.
- also adds a profiling script, with stats from before changes were implemented.

feat: buffer producer broadcasting refactor

---

config/config.exs
config/runtime.exs

fully disable opentelemetry, apparently telemetry signals are still collected unless `sdk_disabled` is set

perf: completely disable opentelemetry sdk unless config is given

---

lib/logflare/backends.ex
test/logflare_web/plugs/buffer_limiter_test.exs

increases the pending buffer length, to account for previous wheel behaviour

perf: increase max pending buffer length

---

lib/logflare/application.ex
lib/logflare/pubsub_rates/cache.ex

This will init the PubSubRates cache early, so that when stuff start getting ingested, it will not log an error (due to schema sampling)

fix: init PubSubRates early

---

lib/logflare/pubsub_rates/buffers.ex
lib/logflare/pubsub_rates/cache.ex
test/logflare/cluster_pubsub_test.exs

This fixes an error when previous version nodes are broadcasting 3-elem buffer msg tuples for PubSubRates

fix: don't handle 3 element tuples of previous format

---

rel/vm.args.eex

https://www.erlang.org/docs/25/man/erl#+sub
load compation leads to spikey scheduler utilization, and given the type of continuous load that we have, does not really make much sense.
This also reduces the scheduler wake up threshold further

perf: load balance on scheduler utilization

---

lib/logflare/backends/ingest_event_queue.ex
lib/logflare/backends/ingest_event_queue/queue_janitor.ex
lib/logflare/sources.ex
test/logflare/backends/ingest_events_queue_test.exs
test/profiling/queue_janitor.exs

Added benchmark scripts and profiling scripts for the QueueJanitor.
- queue purging now uses a new `drop/3` function which is up to 15x faster than `truncate/3` for dropping items from the queue.
- uses a match spec with key selection that provides very slight performance gain for drop & truncate functions
- dynamically schedule QueueJanitor work based on source average rate. For low rates, it will schedule it later, 10 to x10 the interval (10s).
All benchmarking scripts has the results analysis. I had not included the script results as they are very verbose.
Also fixes some noisy tests

perf: improvements to QueueJanitor

---

lib/logflare/backends/buffer_producer.ex
lib/logflare/backends/ingest_event_queue/broadcast_worker.ex
lib/logflare/backends/ingest_event_queue/queue_janitor.ex
test/logflare/backends/bigquery_adaptor_test.exs
test/logflare/backends/ingest_events_queue_test.exs
test/logflare/backends_test.exs

This PR adds in dynamic BufferProducer emit scheduling.
It also adds in a minimum of 1k events to be pulled from the demand worker,
also fixes a float rounding issue in the QueueJanitor scheduling

perf: dynamic BufferProducer scheduling

---

lib/logflare/backends.ex
lib/logflare/backends/adaptor/bigquery_adaptor.ex
lib/logflare/backends/ingest_event_queue/broadcast_worker.ex
lib/logflare/backends/ingest_event_queue/queue_janitor.ex
lib/logflare/pubsub_rates/cache.ex
lib/logflare_web/controllers/plugs/buffer_limiter.ex
test/logflare/backends/bigquery_adaptor_test.exs
test/logflare/backends/ingest_events_queue_test.exs
test/logflare/backends_test.exs
test/logflare_web/plugs/buffer_limiter_test.exs
test/support/conn_case.ex
test/support/data_case.ex

This PR improves the BufferLimiter plug by over ~5899x ips (in worst case 50k queue sizes), by using the PubSubRates cache.

perf: BufferLimiter optimization, use PubSubRates.Cache instead

---

lib/logflare/backends/ingest_event_queue.ex

Reduces chunk size to ensure that events are more spread out across queues.

perf: tweak chunk size for adding to table

---

.github/workflows/elixir-migration-check.yml
lib/logflare/backends.ex
lib/logflare/backends/backend.ex
lib/logflare/sources/rule.ex
lib/logflare/sources/rules.ex
lib/logflare_web/controllers/api/backend_controller.ex
lib/logflare_web/controllers/api/rule_controller.ex
lib/logflare_web/open_api_schemas.ex
lib/logflare_web/router.ex
priv/repo/migrations/20240725033149_add_token_to_rules.exs
priv/repo/migrations/20240725083359_add_metadata_column_to_backends_table.exs
test/logflare/backends_test.exs
test/logflare_web/controllers/api/backend_controller_test.exs
test/logflare_web/controllers/api/rule_controller_test.exs
test/support/factory.ex

management api adjustments for log drains:
1. addition of `/api/rules` for managing rules
2. addition of metadata column for `/api/backends` as well as filtering options for managing backends programmatically

feat: rules management api initial implementation, backends metadata column

---

docs/docs.logflare.com/docs/backends/datadog.mdx
docs/docs.logflare.com/docs/backends/loki.mdx

Adds loki and datadog documentation

docs: Add loki and datadog documentation

---

lib/logflare/backends/backend.ex
test/logflare_web/controllers/api/backend_controller_test.exs

This prevents backend config secrets from being displayed in ui and in API, at the json encoding level.

fix: secrets redaction for backends on encoding

---

lib/logflare_web/live/backends/actions/index.html.heex
lib/logflare_web/live/backends/actions/show.html.heex
test/logflare_web/live/backends_live_test.exs

This PR adds in metadata displaying if set programmatically. Only way to set it is via API.

feat: Logflare UI displays backend metadata

---

lib/logflare/backends/adaptor.ex
lib/logflare/backends/adaptor/datadog_adaptor.ex
lib/logflare/backends/adaptor/elastic_adaptor.ex
lib/logflare/backends/adaptor/webhook_adaptor.ex
test/logflare/backends/webhook_adaptor_test.exs

This PR fixes stale backend configs once a backend is created and updated.

fix: stale backend config in webhook adaptor

---

lib/logflare/backends/source_backend.ex
lib/logflare/backends/source_sup.ex
lib/logflare/backends/source_sup_worker.ex
test/logflare/backends_test.exs

This fix correctly cleans up source-backend procs in the SourceSup tree by adding a periodic cleanup with SourceSupWorker (yea not a very inspired name...).
This will help the issue where procs are still alive even though they are deleted on db.

fix: correctly clean up source backends

---

lib/logflare/backends/adaptor/datadog_adaptor.ex
test/logflare/backends/adaptor/datadog_adaptor_test.exs
test/support/factory.ex

This PR fixes a formatting error for datadog adaptor

fix: event message formatting for datadog adaptor

---

Makefile

This adds in an additional deployment to the `main-saturated` cluster, which is connected to the `main` cluster but will be fully saturated by load balancer.

chore: main cluster deployments to main-saturated cluster

---

lib/logflare_web/controllers/plugs/fetch_resource.ex
test/logflare_web/controllers/log_controller_test.exs

adds in `?collection=` and `?collection_name=` query params for identifying the source to ingest

feat: collection query params for ingestion api

---

lib/logflare/application.ex

This fixes `:protocol` option warnings for our finch pools.

fix: finch :protocol deprecation warning

---

lib/logflare_web/controllers/api/backend_controller.ex
lib/logflare_web/controllers/api/endpoint_controller.ex
lib/logflare_web/controllers/api/rule_controller.ex
lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/open_api.ex
lib/logflare_web/open_api_schemas.ex
test/logflare_web/controllers/api/source_controller_test.exs

This PR fixes http response codes for PUT operations for Sources, Endpoints, Backends

fix: correctly return HTTP response codes for PUT/PATCH operations

---

lib/logflare/application.ex
lib/logflare/backends.ex
lib/logflare/backends/source_sup.ex
lib/logflare/endpoints.ex
lib/logflare/single_tenant.ex
lib/logflare/source/v1_source_sup.ex
lib/logflare/sources.ex
lib/logflare_web/live/query_live.ex
test/logflare/single_tenant_test.exs
test/support/test_utils.ex

This PR fixes a bug where the default backend created for single tenant mode was still bigquery instead of postgres.
Also fixes a bug to allow running queries directly on postgres when using the query UI.
Currently blocks local dev/cli version bump to v1.8.x

fix: default postgres backend

---

lib/logflare/backends.ex
lib/logflare/backends/adaptor/bigquery_adaptor.ex
lib/logflare/backends/dynamic_pipeline.ex
lib/logflare/backends/ingest_event_queue.ex
lib/logflare/backends/ingest_event_queue/queue_janitor.ex
lib/logflare/logs/log_events_cache.ex
lib/logflare/source/bigquery/pipeline.ex
test/logflare/backends/bigquery_adaptor_test.exs

This PR tweaks the spawning logic of dynamic pipelines. This reduces the number of concurrentl pipelines (and thus processes), and also reduces the number of concurrent small requests being made to the BQ api.
Logic now factors in a expected queue length cap (10k), where if any is 75% full, a new pipeline will be created. 
The round robin chunking logic has been bumped to 250 items, so as to emphasize filling up of queues, as opposed to the previous chunking using 10 items which spread events out across all pipelines, resulting in very small batch requests. This would match the batching size of a BQ request.
At avg 15k events per sec, only 3 pipelines are used on local dev

perf: dynamic pipelines tweaks

---

lib/logflare/backends/adaptor/bigquery_adaptor.ex
lib/logflare/utils.ex

This tweaks the pipeline count resolution logic and interval, making it more conservative in pipeline creation, while also reducing the interval check.
also adds in a perf improvment when there is only one target pipeline to round robin to.

perf: tweak pipeline provisioning to be more conservative

---

lib/logflare_web/controllers/api/backend_controller.ex
lib/logflare_web/controllers/api/endpoint_controller.ex
lib/logflare_web/controllers/api/rule_controller.ex
lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/controllers/api/team_controller.ex
test/logflare_web/controllers/api/backend_controller_test.exs
test/logflare_web/controllers/api/endpoint_controller_test.exs
test/logflare_web/controllers/api/source_controller_test.exs
test/logflare_web/controllers/api/team_controller_test.exs

Fixes mgmt API PATCH handling, response body should always be empty.
https://github.com/phoenixframework/phoenix/issues/1131

fix: no reponse body for patch

---

lib/logflare/backends/adaptor/webhook_adaptor/egress_middleware.ex
test/logflare/backends/webhook_adaptor_test.exs

Fixes egress middleware telemetry raise bug when metadata value is not set.

fix: egress middleware metadata default

---

lib/logflare/sources.ex
lib/logflare/sources/source.ex
lib/logflare/users/users.ex
lib/logflare_web/controllers/source_controller.ex
lib/logflare_web/templates/source/dashboard.html.heex
lib/logflare_web/templates/source/edit.html.eex
lib/logflare_web/views/source_view.ex
test/logflare/backends/adaptor/datadog_adaptor_test.exs
test/logflare/backends/buffer_producer_test.exs
test/logflare/backends/dynamic_pipeline_test.exs
test/logflare/backends/elastic_adaptor_test.exs
test/logflare/backends/ingest_events_queue_test.exs
test/logflare/backends/webhook_adaptor_test.exs
test/logflare/cluster_pubsub_test.exs
test/logflare/endpoints_test.exs
test/logflare/logs/rejected_logs_test.exs
test/logflare/source/bigquery/schema_test.exs
test/logflare/sources/sources_cache_test.exs
test/logflare/sources_test.exs
test/logflare/sql_test.exs
test/logflare/users/users_cache_test.exs
test/logflare/users/users_test.exs
test/logflare_grpc/trace/server_test.exs
test/logflare_web/controllers/api/endpoint_controller_test.exs
test/logflare_web/controllers/api/query_controller_test.exs
test/logflare_web/controllers/api/source_controller_test.exs
test/logflare_web/plugs/fetch_resource_test.exs
test/logflare_web/plugs/verify_api_access_test.exs

This refactors the retention days updating to use `retention_days` field to be backend agnostic.
It currently does nothing for non-BQ backends.
Might be moved to backend level in the future.

feat: retention days api refactoring

---

lib/logflare/source_schemas.ex
lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/open_api_schemas.ex
lib/logflare_web/router.ex
test/logflare/sources_schemas_test.exs
test/logflare_web/controllers/api/source_controller_test.exs

This PR adds in source schema APIs.
It adds in dot notation and json schema as variants.
Currently converts directly from the stored BQ schema.
Textual representation of array is done by appending `[]` to the data type.
Over time we will be moving typings to conform with json schema types, so backend-specific typing will become irrelevant and phased out with the transition of v1->v2 schema management.

feat: source schema api

---

lib/logflare/pubsub_rates.ex
lib/logflare/pubsub_rates/buffers.ex
lib/logflare/pubsub_rates/inserts.ex
lib/logflare/pubsub_rates/rates.ex
test/logflare/cluster_pubsub_test.exs

- cleans up Logflare.PubSubRates 
- prevents procs from sending and subscribing to topics which are not partitioned

chore: cleanup PubSubRates mod

---

docs/docs.logflare.com/docs/concepts/ingestion/index.mdx
lib/logflare/source/bigquery/pipeline.ex

This PR reduces the schema sample rate even more, to around ~1 per second for most sources. increased sampling threshold to 10k events per sec.

perf: tweak schema sampling rate

---

lib/logflare/source/recent_logs_server.ex

This PR increases major GC frequency for RLS server, which stores ingestion count metrics.
Longer term solution is to move such metrics to ETS instead

perf: tweak gc-ing of RLS genserver

---

test/logflare/backends/postgres_adaptor_test.exs

```
15:20:28.535 [error] :gen_statem #PID<0.1682.0> terminating
** (RuntimeError) connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
(elixir 1.17.3) lib/keyword.ex:602: Keyword.fetch!/2
(postgrex 0.17.3) lib/postgrex/protocol.ex:163: Postgrex.Protocol.connect_endpoints/6
(db_connection 2.6.0) lib/db_connection/connection.ex:92: DBConnection.Connection.handle_event/4
(stdlib 6.1.2) gen_statem.erl:3737: :gen_statem.loop_state_callback/11
(stdlib 6.1.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Queue: [internal: {:connect, :init}]
Postponed: []
```
This …

chore: silence postgrex errors for database errors

---

lib/logflare/logs/log_events_cache.ex

Reduces size of LogEventsCache further

perf: tweak LogEventsCache size and ttl

---

lib/logflare/logs/search/logs_search_query_executor.ex

This adds more frequent GC-ing to running SearchQueryExecutors

perf: adds fullsweep_after to search query executor

---

docs/docs.logflare.com/docs/concepts/ingestion/index.mdx
lib/logflare/logs/log_event.ex
lib/logflare/logs/logs.ex
lib/logflare/sources/source.ex
lib/logflare_web/templates/source/edit.html.eex
priv/repo/migrations/20241121183147_add_transform_copy_fields_column_to_sources_table.exs
test/logflare/backends_test.exs
test/logflare/log_event_test.exs
test/logflare_web/controllers/api/source_controller_test.exs
test/logflare_web/controllers/source_controller_test.exs

This PR adds in the following ingestion logic:
- Use bq schema spec transformations in v2 pipeline, was missed out.
- pipeline field copying, in a new "transformations" section which will transform the payload at ingest time. Allows for multiple rules.

feat: ingestion time field copying, dashes replacement

---

docs/docs.logflare.com/docs/integrations/open-telemetry/index.mdx
lib/logflare_grpc/trace/server.ex

Adds otel docuemntation, adds accepted source headers `x-source` and `x-source-uuid`

docs: add otel docs, add extra accepted source headers

---

lib/logflare/application.ex
lib/logflare/google/bigquery/gen_utils/gen_utils.ex
lib/logflare/system_metrics/cluster.ex
test/logflare_web/controllers/endpoints_controller_test.exs
test/logflare_web/live/search_live/logs_search_lv_test.exs

This reverts to a previous optimization, splitting out the finch pools used for ingest/query into separate trees, so that we can better isolate issue relating to either.
This is so that we can pin down this issue, has not popped up recently.

perf: split finch pools for ingest

---

cloudbuild/staging/deploy.yaml
lib/logflare/backends/adaptor/postgres_adaptor/pipeline.ex
lib/logflare/backends/adaptor/webhook_adaptor.ex
lib/logflare/backends/buffer_producer.ex
lib/logflare/source/bigquery/pipeline.ex
test/logflare/backends/buffer_producer_test.exs
test/logflare/backends/loki_adaptor_test.exs

Reduces broadway process memory footprint further, as the callback to start the buffer producer is stored in process state.

perf: reduce broadway memory footprint

---

lib/logflare/backends.ex
lib/logflare/backends/adaptor/bigquery_adaptor.ex
lib/logflare/backends/ingest_event_queue.ex
lib/logflare/backends/ingest_event_queue/broadcast_worker.ex
lib/logflare/backends/ingest_event_queue/queue_janitor.ex
lib/logflare/logs/browser_report.ex
lib/logflare/pubsub_rates/cache.ex
test/logflare/backends/buffer_producer_test.exs
test/logflare/backends/ingest_events_queue_test.exs
test/logflare/backends_test.exs
test/logflare_web/plugs/buffer_limiter_test.exs
test/profiling/buffer_limiter.exs
test/profiling/ingest_event_queue_trunc.exs

This PR:
- removes expensive table traversals in hot code paths, and instead uses table size as an estimate for the buffer pending length as it is O(1)
- fixes buffer limiter to be based on the total size of the table as an estimate, which achieves the same intended goal of protecting memory, albeit being more conservative as it includes ingested events as well. However, theoretical total max queue size is currently num of cores * 50k so it would be plenty.
Also added benchmark to verify that `list_pending_counts/1` was very expensive and should be avoided.

perf+fix: remove expensive  table traversal for pending counts, fix buffer limiter

---

rel/vm.args.eex

> If large amounts of named tables are used and `ERL_MAX_ETS_TABLES`
hasn't been increased, the performance of named table lookup will degrade.
> 
https://www.erlang.org/doc/apps/stdlib/ets.html#module-table-traversal

perf: increase max ets tables allocation

---

lib/logflare/backends.ex
lib/logflare/source/data.ex
lib/logflare/source/email_notification_server.ex
lib/logflare/source/recent_logs_server.ex
lib/logflare/source/slack_hook_server/slack_hook_server.ex
lib/logflare/source/text_notification_server.ex
lib/logflare/source/webhook_notification_server/webhook_notification_server.ex

This PR reduces the number of tasks getting spawned unecessarily. Much of these removed are non-critical areas.
Due to SourceSup being initialized across cluster and the number of nodes in cluster, the amount of cross-cluster tasks spawning increases as our cluster size and volume increases. Keeping the comparison local will minimize the number of tasks spawned.
Critical areas preserved for future optimizations are those used in Endpoints.

perf: reduce tasks spawning

---

lib/logflare/backends.ex
lib/logflare/source/recent_logs_server.ex
lib/logflare/sources/counters.ex

This PR moves RLS state updating to ets to help with GC-ing

perf: move RLS state off process heap

---

lib/logflare/backends/ingest_event_queue.ex
lib/logflare/source/bigquery/pipeline.ex
test/logflare/bigquery/pipeline_test.exs
test/profiling/ingest_event_queue_counts.exs

immediately delete events from ets queue if queue if rate is fast enough to recent logs from incoming events

perf: acks delete ingested events from queue

---

config/runtime.exs
lib/logflare_grpc/identity_compressor.ex
lib/logflare_grpc/trace/server.ex

`identity` is set by some opentelemetry SDKs, it should be handled as a passthrough
This PR also fixes a traces exporting bug where `x-source-id` has since been removed.

 grpc-encoding `identity` should be handled, x-source-id removal 

---

cloudbuild/prod/pre-deploy.yaml

Fixes for duplicate logflare alerts getting triggered

fix: duplicate logflare alerts being triggered by increasing alerts cluster size threshold

---

lib/logflare/auth.ex
lib/logflare/auth/cache.ex
lib/logflare/context_cache.ex
lib/logflare/context_cache/supervisor.ex
lib/logflare/system_metrics/cachex/poller.ex
lib/logflare_grpc/trace/server.ex
lib/logflare_web/controllers/plugs/verify_api_access.ex
test/logflare/auth/cache_test.exs
test/logflare/auth_test.exs
test/logflare/context_cache_test.exs
test/logflare/single_tenant_test.exs

This PR removes Cachex from the ContextCache module, which was acting as a reverse index to reference the context MFA and primary id of records.
The original approach has a few limitations:
- setting the cache limit high to 500k results in a prod memory footprint of 25-30GB at max size, however a high cache limit is needed in order to retain the mfa keys to bust. Otherwise, if they are not in the reverse index, they will not get busted and there is risk of stale data.
- setting the cache ttl to a long value results in cache reaching max limit set above, excacerbating the above problem.
- ContextCache does not actually get used as a cache, making the overhead of Cachex redundant.
- high record count results in slow traversals, and can back up the TransactionBuster which is a single local …

feat: remove Cachex from ContextCache, use direct cache busting, list value busting

---

lib/logflare/single_tenant.ex
test/logflare/single_tenant_test.exs

This fixes a bug where stored plan values in a single tenant instance will cause the match to fail when attempting to find the Enterprise plan. 
It should instead upsert the hardcoded plan values, and find by name.

fix: single tenant handling of backup plan values

---

cloudbuild/prod/pre-deploy.yaml
lib/logflare/context_cache/cache_buster.ex
test/profiling/context_cache_bust_keys_bench.exs

This PR partitions the CacheBuster, to account for slow Cachex streaming.
Also added in a benchmark for good measure.
This PR also tweaks the pool_size of the prod instances.
```
```

fix: message queue backing up for CacheBuster

---

lib/logflare/sources/source_routing.ex
test/logflare/logs/logs_test.exs

this fixes a routing bug where backend rules without source sinks result in ingestion errors, causing subsequent payload to get dropped.

fix: source routing without sink, closes ANL-719

---

lib/logflare/application.ex
lib/logflare/backends/buffer_producer.ex
lib/logflare/backends/ingest_event_queue.ex
lib/logflare/backends/ingest_event_queue/queue_janitor.ex
lib/logflare/context_cache/cache_buster.ex
lib/logflare/system_metrics/cluster.ex
test/logflare/backends/buffer_producer_test.exs
test/logflare/backends/ingest_events_queue_test.exs

This PR moves the ingestion to http1, to avoid gotchas experienced in http2 finch pools.
It also implements BufferProducer exit trapping to handle graceful shutdown of events.

fix: http1 finch pools for BQ ingestion, BufferProducer exit handling  

---

lib/logflare/alerting.ex
test/logflare/alerting_test.exs

This PR sets the run strategy for newly created quantum jobs

fix: set jobs to run locally for quantum run strategy

---

lib/logflare/logs/processor.ex
lib/logflare/sources/source_routing.ex

backend rule routing logic should not need the source (that it is ingesting in) to be started, otherwise the ingestion would have already failed.

fix: remove move ensure source sup started from routing logic

---

docs/docs.logflare.com/docs/concepts/ingestion/index.mdx

Adds docs on logpush, seems like we never got around to documenting it.

docs: add logpush ingestion documentation

---

lib/logflare/application.ex
lib/logflare/backends.ex
lib/logflare/backends/buffer_producer.ex
lib/logflare/backends/ingest_event_queue.ex
lib/logflare/backends/ingest_event_queue/queue_janitor.ex
lib/logflare/source/bigquery/pipeline.ex
test/logflare/bigquery/pipeline_test.exs

- doubles processor and batcher counts for BigQuery pipeline, in a real world scenario it would likely be limited by batcher request speed, so there are diminishing returns in increasing processor counts. This will roughly 2.6x output per pipeline, so that we can burn down queues faster. see benchmark for details 
- increases http1 pools to increase overall max http throughput. Likely redundant once we move to Storage Write API
- tweak producer schedule scaling based on avg ingest rate, reducing it significantly for high rate sources. 
- Increase Ingest event queue to 15k, and reduce round robin chunking to 50. This should spread out chunks to more queues now.
- Reduce QueueJanitor purge ratio to 0.05, to account for larger ingest queue permitted.
BencheeAsync benchmark of Pipeline. only …

perf: ingestion tweaking for bigquery

---

.iex.exs
lib/logflare/backends/adaptor/bigquery_adaptor.ex
lib/logflare/backends/dynamic_pipeline.ex
lib/logflare/utils/debugging.ex
test/logflare/backends/bigquery_adaptor_test.exs

This adjusts the dynamic Broadway pipeline creation logic to be threshold based -- if any queue hits a certain threshold, it would add an additional scaled number of pipelines.
It also adjusts the gradual decrease to make it much harder for it to scale down. Scale to zero condition is unchanged.
Threshold chosen is 500 items, which seems to be the eyeballed number in prod that queues are hovering at for busy sources. Most spike to 1-2k even for very busy sources. 
This should help avoid load shedding by the QueueJanitor, as load shedding is still getting triggered due to request spikes on only one pipeline, as previous resolve logic would only create more pipelines when pipeline is at least half of max (7.5k) at point of resolving. What is likely happening is a race condition where:
- the …

feat: threshold-based DynamicPipeline resolving

---

config/config.exs
lib/logflare/backends.ex
lib/logflare/backends/recent_events_touch.ex
lib/logflare/backends/recent_inserts_broadcaster.ex
lib/logflare/backends/source_sup.ex
lib/logflare/context_cache/supervisor.ex
lib/logflare/gen_singleton.ex
lib/logflare/gen_singleton/watcher.ex
lib/logflare/source/v1_source_sup.ex
test/logflare/backends_test.exs
test/logflare/gen_singleton_test.exs
test/support/factory.ex

Generic cluster-wide singleton GenServer, to allow for logic reuse. This has been added to the RecentEventsTouch server to allow for a single genserver cluster-wide to perform the record updated, instead of every node in the cluster performing the update.
This module should only be used for non-critical functions or functions that are not time-sensitive, as it uses a naive interval checking logic.
It is generic enough to be applicable to both syn and global.
importantly, this reduces the total transactions occuring across the cluster, thereby also reducing cainophile messages broadcasted.

feat: GenSingleton

---

lib/logflare/sql.ex
test/logflare/sql_test.exs

Fixes https://linear.app/supabase/issue/ANL-863/logflare-endpoints-fix-union-all-for-2-expressions
Handles multiple union all in sql statements.
Moves tree traversal code from anon function to separate function definition for recursion. I should probably extract this out to a macro soon...

fix: handle multiple union all

---

rel/vm.args.eex

Reverting busy-wait, seems like this will cause an issue with load balancer as gcp load balancer calculates max loading based cpu utilization, causing load to be taken on and off nodes in a non-consistent way, since scheduler utilization (and thusly cpu utilization) jumps a lot when large amounts of load is taken on and off (despite gcp load balancer already having high utilization threshold).
I suspect that this also results in load balancer level pushback on requests resulting in higher latency on our load test cluster.

perf: revert busy wait

---

config/runtime.exs

seems like the direct Postgrex connection did not use ssl before (?) even though the ecto repo requires it

chore: remove ssl option from libcluster postgres

---

config/config.exs
docs/docs.logflare.com/docs/concepts/endpoints.md
lib/logflare/alerting/supervisor.ex
lib/logflare_web/controllers/endpoints_controller.ex
test/logflare_web/controllers/endpoints_controller_test.exs

This PR adds in GET body read support as fallback for very large sql queries. It also increases the max request line length for http1 requests by 10x from the default.

feat: logflare endpoints support large sql queries

---

config/config.exs
lib/logflare/logs/log_events_cache.ex
lib/logflare/source/bigquery/pipeline.ex

Adds minor adjustments for memory. Increasing acceptors is a low hanging fruit for reducing bottleneck chance, still need to add metrics around acceptor idling for further optimizing.
https://linear.app/supabase/issue/ANL-873/minimzing-logeventcache-memory-footprint
https://linear.app/supabase/issue/ANL-883/logflare-ingestion-add-tracing-around-bq-batch-sending
fixes ANL-873 , ANL-883

perf: Compress LogEventCache, adjust acceptors, add batch stream tracing

---

lib/logflare/backends/adaptor/clickhouse_adaptor.ex
lib/logflare/backends/adaptor/webhook_adaptor.ex
lib/logflare/backends/backend.ex
lib/logflare_web/live/backends/components/backend_form.heex
test/logflare/backends/clickhouse_adaptor_test.exs

Super simple/naive approach to doing some basic smoke testing on sinking logs into Clickhouse by fronting the existing webhook adaptor.
Includes just enough UI to configure a Clickhouse backend and some simple tests based off the Loki backend test.
Long-term, we'll want to rework this to be its own first-class adaptor that leverages something like [ch](https://hex.pm/packages/ch) under the hood.
I did have to introduce a _workaround_ for dynamically providing a URL to the webhook adaptor given that configs are merged within that adaptor at runtime - paving over the URL manipulation performed to inject the table name into the querystring. This will go away at a later time when we roll out a more robust implementation.
Worth noting that to use this backend, it does expect the table to exist …

Initial ClickHouse Log Drain Functionality

---

lib/logflare/logs/otel_trace.ex
test/logflare/logs/otel_trace_test.exs
test/logflare_grpc/trace/server_test.exs
test/logflare_web/controllers/log_controller_test.exs
test/support/test_utils_grpc.ex

This PR adds support for otel array attributes, as needed by storage team.

feat: add support for arrays for otel traces

---

lib/logflare/application.ex
lib/logflare/backends/adaptor/clickhouse_adaptor.ex
lib/logflare/backends/adaptor/webhook_adaptor.ex
test/logflare/backends/clickhouse_adaptor_test.exs

The current implementation of the Clickhouse log drain relies on the existing `WebhookAdaptor` and the underlying Finch-based connection pooling.
Due to the way Clickhouse cloud URLs are with dynamic subdomain parts - this makes leveraging traditional Finch pooling a bit tricky without doing some sort of runtime management of pools since the pools are keyed by a `{<scheme>, <host>, <port>}` tuple.
Rather than deal with that extra complexity, this change simply defines a new pool dedicated to Clickhouse for now that is specified for use by leveraging a new config opts in the `WebhookAdaptor`.
Again, this should be temporary to push a bit harder on clickhouse logs draining until a deeper implementation with [`:ch`](https://hex.pm/packages/ch) is finished.

Connection pool workaround for the sake of Clickhouse cloud

---

lib/logflare_web/live/backends/actions/show.html.heex
lib/logflare_web/live/display_helpers.ex
test/logflare_web/live/backends_live_test.exs

As requested, this change adds a new helper module with a function that redacts the values of any attributes in a backend config that are not in the list of `allowed_keys`. This is done to better future proof the functionality rather than relying on a filter.
Includes a simple test to validate the behavior as well.

Redact backend config attributes from the show view

---

lib/logflare_web/core_components.ex
lib/logflare_web/live/access_tokens_live.ex
lib/logflare_web/live/alerts/actions/edit.html.heex
lib/logflare_web/live/alerts/actions/index.html.heex
lib/logflare_web/live/alerts/alerts_live.ex
lib/logflare_web/live/backends/actions/edit.html.heex
lib/logflare_web/live/backends/actions/index.html.heex
lib/logflare_web/live/endpoints/actions/edit.html.heex
lib/logflare_web/live/endpoints/endpoints_live.ex

Fixed docs links that were pointing to pages that no longer exist or were moved.
Additionally, I noticed that `subheader_link` components that point to external URLs (docs) cause an error in the browser console because live view tries to call push state with the external URL. I added an `external` parameter to allow external links to be regular a tags to bypass live view, and added it to all `subheader_link` that point to external urls.

fix: update doc links and properly open external links

---

lib/logflare/backends/adaptor/clickhouse_adaptor.ex
lib/logflare/backends/adaptor/clickhouse_adaptor/query_templates.ex
test/logflare/backends/adaptor/clickhouse_adaptor/query_templates_test.exs
test/logflare/backends/adaptor/clickhouse_adaptor_test.exs

Minor change to create both the key counts table and materialized view with a dynamic suffix based on the `source.token` the same as the log ingress table.
Generated resource names (tables, views, etc) are also checked to ensure their length is in a 'safe' area.
This also adds improved logger messages when a GRANT check fails.

Dynamic suffix on all CH resources based on `source.token`

---

lib/logflare/google/resource_manager.ex

This is necessary if you are using ArtifactRegistry instead of Container Registry. We did this migration recently and deploy would break due to the Cloud Engine service account missing this role.

fix: add artifactregistry.reader role to GCP CE service acc

---

lib/logflare/logs/otel.ex
lib/logflare/logs/otel_metric.ex
lib/logflare/logs/otel_trace.ex
test/logflare/logs/otel_test.exs

This PR does two things:
OTel traces and metrics always have two entities: resource and scope. We are currently merging both of them and putting them in metadata. This is a bit limiting. This PR changes it to keep them separate maps, and moves the data from `metadata` to root (not sure about this part, though).
Before:
```json
{
"metadata": {
"type": "span",
"service": {
"name": "Logflare",
"version": "1.14.2"
},
"name": "opentelemetry_bandit",
"version": "1.2.3",
"asd": "bsd"
},
"event_message": "POST /a/b",
"span_id": 391283921,
"trace_id": 30921803120
}
```
After:
```json
{
"metadata": {
"type": "span"
},
"resource": {
"service": {
"name": "Logflare",
"version": "1.14.2"
}
},
"scope": {
"name": "opentelemetry_bandit",
"version": "1.2.3",
"attributes": {
"asd": "bsd"
}
}, …
```

fix(otel): split scope and resource; project name

---

lib/telemetry.ex

This is a follow up to #2412, and is dependent on it working well. Instead of exporting a selected subset of metrics, we export all of them.
A bunch of metrics had to be converted from summaries to distributions, since the exporter doesn't support summaries (and distributions are generally better anyway). Some of them had wrong types (e.g.: we probably aren't interested in a distribution of memory but in the last value available).

feat: export all metrics through otel

---

lib/logflare_web/live/backends/components/backend_form.heex

Basic auth fields were missing from logflare ui

fix: add basic auth fields to loki ui

---

lib/logflare/endpoints.ex
lib/logflare/endpoints/cache.ex
lib/logflare/endpoints/resolver.ex
test/logflare/endpoints_cache.test.ex
test/logflare/endpoints_test.exs

- fixes tests
- catches cases where Endpoints processes don't always shutdown
- added `hibernate_after: 5_000`

fix: endpoints caches should always shutdown

---

Makefile

This makes it convenient when working on a lot of tests :pray:

chore: add make test.failed to automatically run only the failed tests

---

lib/logflare_web/controllers/log_controller.ex

They return 200, not 201. Noticed this while doing the integration from Supavisor's side.

doc: fix openapi spec for log endpoints

---

test/support/test_utils.ex

This is just for debugging purposes while testing static views (so it is kinda inspired from this [`open_browser/2`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#open_browser/2) utility).

feat: add open_browser/2 for easy debugging controllers testing

---

README.md

I notice we are over 61% and the badge still was showing 60%. The problem was we were pointing to the branch that originally added the coverage badge.

chore: update README coverage badge to show main

---

lib/logflare_web/controllers/api/team_controller.ex
lib/logflare_web/controllers/log_controller.ex
lib/logflare_web/open_api.ex
lib/logflare_web/open_api_schemas.ex
test/logflare_web/controllers/api/team_controller_test.exs
test/support/conn_case.ex

Following up on the work of PR https://github.com/Logflare/logflare/pull/2470, we can now validate the response schemas according to the OpenAPI spec making sure a consistent behavior is enforced for all common operations (not found, unprocessable entity, etc).

test: add missing test for put request in TeamController and validate all schema responses

---

lib/logflare/application.ex
lib/logflare/context_cache/cache_buster.ex
lib/logflare/context_cache/supervisor.ex
lib/logflare/endpoints.ex
lib/logflare/endpoints/cache.ex
lib/logflare/endpoints/resolver.ex
lib/logflare/endpoints/results_cache.ex
lib/logflare_web/controllers/plugs/fetch_resource.ex
test/logflare/endpoints_cache.test.ex
test/logflare/endpoints_cache_test.exs
test/logflare/endpoints_test.exs
test/logflare_web/live_views/endpoints_live_test.exs

This PR adds in Cachex for Logflare Endpoints, allowing us to remove the Query storage in the GenServer, and ensuring that no cross-cluster stale queries are present.
This renames Endpoints.Cache to Endpoints.ResultsCache, and uses the convention Endpoints.Cache module for context caching as per other contexts in the codebase.
This also hashes the params when creating the Endpoint.ResultsCache name, allowing us to reduce the impact of large params on the proc registration tables.

perf: add Cachex for Logflare Endpoints 

---

lib/logflare_web/controllers/api/endpoint_controller.ex
lib/logflare_web/controllers/log_controller.ex
lib/logflare_web/open_api.ex
lib/logflare_web/open_api_schemas.ex
test/logflare_web/controllers/api/endpoint_controller_test.exs
test/support/conn_case.ex

This commit adds missing tests for the put operation (in update endpoint). It also validates the response against the OpenAPI schema format by introducing a new helper function `assert_schema/2` to avoid boilerplate (essentially repeating the api_spec function call).
In the `LogController`, added operation missing definitions to avoid all the warnings from the OpenApiSpex validator.
Start using the `sigil_p` in the testing routes to have a better DX when making a typo.
Also fixed a repeated typo on "endpoint" word.

test: improve test coverage for Api.EndpointController

---

config/runtime.exs
lib/logflare/backends/adaptor/bigquery_adaptor.ex
lib/logflare/google/bigquery/gen_utils/gen_utils.ex
lib/logflare/google/resource_manager.ex
test/logflare/backends/bigquery_adaptor_test.exs
test/test_helper.exs

This PR properly handles managed service accounts when it is disabled (it is disabled by default).

fix: properly handles managed service accounts when disabled

---

test/logflare_web/live/billingaccount_live/edit_test.exs

The setup on this test case was flaky because processing the webhook sometimes took longer than the liveview re-render. Using the retry_assert allows us to retry the test until it passes.

test: use retry_assert on flaky test in BillingAccountLive

---

lib/logflare/application.ex

when running `make start.st.pg` without big query configured the application errors and closes, this PR fixes that

fix: pg local startup

---

DEVELOPMENT.md
Makefile

Some simple QOL improvements while keeping things backwards compatible:
- Adds support for [mise](https://mise.jdx.dev)
- Makefile will use `mise`, if it is installed, otherwise it will use `asdf` as before
- If both binaries are available, defaults to `mise`
- `mise` handles `.tool-versions` files the same as `asdf`
- See the _Why mise??_ section below for more details
- Adds basic checks for other tools used by the Makefile such as `docker`, `git`, and `gcloud`
- Will not error out if these are not available, but will present a warning.
- Adds some basic color support as well as better visual indicators of what is going on - particularly when running `make setup`.
----
If unfamiliar with mise, [this document](https://mise.jdx.dev/dev-tools/comparison-to-asdf.html) provides a comparison …

chore: makefile quality of life additions (mise support, improved messages)

---

lib/logflare/backends/source_sup.ex
lib/logflare/logs/search/logs_search_operation.ex
lib/logflare/logs/search/logs_search_operations.ex
lib/logflare/logs/search/logs_search_query_executor.ex
lib/logflare/source/v1_source_sup.ex
lib/logflare_web/live/search_live/logs_search_lv.ex

Major refactor of SearchQueryExecutor, to minimize memory and cpu impact, as well as to narrow down on cpu leak that we are observing on main cluster.
This starts up the executor on a per search basis, and only allows for one search at a time. It does not deviate too much from existing behaviour, however some additional performance tweaks are put in:
- add in genserver hibernation after 5s
- remove streaming buffer caching and associated task spawning
- reduce chart default query query range for day/hour
- reduce default querying intervals based on ingest rate - high ingest rate sources will now query last minute and this scales based on avg ingestion rate - closes ANL-504

perf: refactor search query executor

---

test/logflare/sql/dialect_transformer/bigquery_test.exs
test/logflare/sql/dialect_transformer/clickhouse_test.exs
test/logflare/sql/dialect_transformer/postgres_test.exs
test/support/factory.ex
test/support/test_utils.ex

Minor adjustments to ensure the dialect transformer tests are asynchronous by using the ex_machina `build` callback rather `insert`.
This did require a minor change to the factory for `Source` as it uses a custom ecto type (`Ecto.UUID.Atom`) for the `token` attribute to ensure that build serializes the value as an atom.

chore: make sql dialect transformer tests async

---

lib/logflare_web/live/alerts/alerts_live.ex
lib/logflare_web/live/alerts/components/alert_form.html.heex
lib/logflare_web/live/endpoints/components/endpoint_form.html.heex
lib/logflare_web/live/endpoints/endpoints_live.ex
lib/logflare_web/live/monaco_editor_component.ex
test/logflare_web/live/monaco_editor_component_test.exs
test/logflare_web/live_views/alerts_live_test.exs
test/logflare_web/live_views/endpoints_live_test.exs

* AlertsLive uses MonacoEditorComponent
* refactor: build completions to MonacoEditorComponent
* refactor: update EndpointsLive with MonacoEditorComponent changes
* add "parse_query" hook test to AlertsLive and EndpointsLive
* remove unused handle_event("parse_query"...) from EndpointsLive (handled in MonacoEditorComponent)

feat: Add Monaco editor to AlertsLive

---

lib/logflare/sql/dialect_translation.ex
test/logflare/sql_test.exs

wrong:
```
"SELECT count(CASE WHEN ((body #> '{metadata,request,method}') IN ('GET', 'POST')) THEN 1 END) AS count FROM \"c.d.e\" AS t"
```
correct:
```
"SELECT count(CASE WHEN ((body #>> '{metadata,request,method}') IN ('GET', 'POST')) THEN 1 END) AS count FROM \"c.d.e\" AS t"
```

fix: bq->pg translation error when field contains

---

lib/logflare/sql/dialect_translation.ex
test/logflare/sql_test.exs

Fixes 3 translation bugs:
- casting of nested field references to numeric
- regexp_contains when field reference is present
- cross join unnest without CTE with a between operator present 
todo:

fix: sql postgres translation

---

lib/logflare/syn_event_handler.ex

Stop the process if a conflict arises. Seems like syn does not handle process conflicts automatically if the handler is defined.
> If implemented, this method MUST return the pid() of the process that you wish to keep. **The other process will not be killed, so you will have to decide what to do with it**. If the custom conflict resolution method does not return one of the two Pids, or if the method crashes, none of the Pids will be killed and the conflicting name will be freed.
Likely the cause of the issue we are seeing with multiple GenSingleton servers getting created still.

fix: syn conflict resolution

---

lib/logflare/gen_singleton/watcher.ex

correctly handles syn resolve kill on Supervisor startup attempt

fix: handle :syn_resolve_kill

---

lib/logflare/backends.ex
lib/logflare/backends/adaptor/postgres_adaptor/pg_repo.ex
lib/logflare/backends/ingest_event_queue.ex
lib/logflare/backends/ingest_event_queue/broadcast_worker.ex
lib/logflare/pubsub_rates.ex
test/logflare/backends/adaptor/postgres_adaptor_test.exs
test/logflare/backends/dynamic_pipeline_test.exs
test/logflare/backends/ingest_event_queue_test.exs
test/logflare/backends_test.exs
test/logflare/bigquery/pipeline_test.exs
test/logflare_web/plugs/buffer_limiter_test.exs
test/profiling/buffer_producer.exs
test/profiling/queue_janitor.exs

The fixes are related to IngestEventQueue.upsert_tid/1 which was incorrectly sometimes passing the source and backend instead of the ids. I added some guards to help me catch these mistakes and I keep them so we avoid making the same errors in the future. This removes some noisy messages that didn't appear all the time (but most of the time).

fix: correctly setup source and backend ids in supervisor

---

lib/logflare_web/controllers/source_controller.ex
lib/logflare_web/templates/source/dashboard.html.heex
test/logflare_web/controllers/source_controller_test.exs

Reuse the code in the dashboard controller when user has a team_user and when it doesn't in the http session.
Moved Routes helper to `sigil_p` in dashboard.html.heex.

refactor: join endpoint for SourceController dashboard

---

lib/logflare/backends/ingest_event_queue/broadcast_worker.ex
lib/logflare/backends/recent_inserts_broadcaster.ex

Adds in scaled broadcast intervals based on cluster sizes. Also spreads out message broadcasting to prevent spikes from fast cluster startups.

perf: add broadcast interval scaling for global broadcasts

---

lib/logflare/gen_singleton/watcher.ex
lib/logflare/syn_event_handler.ex
test/logflare/alerting_test.exs

Only kills conflicting procs on local nodes, and also applies keep_original to all conflicts.

perf: only kill syn conficting procs on local nodes, apply keep_original to all

---

lib/logflare/backends/adaptor/clickhouse_adaptor/pipeline.ex

Bumps the Clickhouse backend ingest batch size from 350 -> 1_000

feat/perf: increase clickhouse pipeline batch size

---

lib/logflare/ecto/bigquery/bq_repo.ex
lib/logflare/logs/search_operations.ex
lib/logflare_web/live/search_live/logs_search_lv.ex
test/logflare_web/live/search_live/logs_search_lv_test.exs

Following on from #2557
⚠️ Query cost is checked and logged but not yet enforced:
https://github.com/Logflare/logflare/pull/2570/files#diff-bef332c925224bac9585297f3254655dd58c669688b52492e2233ba11f75fb0eR47-R48
UI discussion below has been split into a separate PR.

Reduce queries in Search Results page load

---

lib/logflare/backends/adaptor/postgres_adaptor/pg_repo.ex

refactor: extract nested code in lib/logflare/backends/adaptor/postgres_adaptor/pg_repo.ex

---

lib/logflare/billing.ex

refactor: extract nested code in lib/logflare/billing.ex

---

lib/logflare_web/live/source_backends_live.ex

refactor: extract nested code in lib/logflare_web/live/source_backends_live.ex

---

.github/workflows/elixir-ci.yml
.github/workflows/elixir-migration-check.yml
docker-compose.yml

- adds clickhouse docker image to `.github/workflows/elixir-migration-check.yml`
- updates clickhouse server version to `25.6` in `docker-compose.yml` and CI yamls

chore: clickhouse ci improvements

---

test/logflare/backends/adaptor/clickhouse_adaptor/connection_manager_test.exs
test/logflare/backends/adaptor/clickhouse_adaptor/pipeline_test.exs
test/logflare/backends/adaptor/clickhouse_adaptor/provisioner_test.exs
test/support/data_case.ex

Clickhouse tests had a bug that could create an extra free plan which causes issues with `Logflare.Billing.get_plan_by/1`
This moves the plan setup to the responsibility of the test file(s) rather than the datacase helper.

chore/bug: fix issue in `Logflare.DataCase` for clickhouse tests

---

lib/logflare/rules.ex

refactor: extract nested code in lib/logflare/rules.ex

---

lib/logflare/google/bigquery/gen_utils/gen_utils.ex
lib/logflare/google/cloud_resource_manager.ex

The goal is to reactivate the rule in credo config once it is done for all.

refactor: follow Credo.Check.Readability.ParenthesesOnZeroArityDefs in lib/logflare/google*

---

lib/logflare/backends.ex
lib/logflare/backends/adaptor/bigquery_adaptor.ex
lib/logflare/backends/adaptor/clickhouse_adaptor/query_templates.ex
lib/logflare/backends/adaptor/s3_adaptor/pipeline.ex
lib/logflare/backends/backend.ex
lib/logflare/backends/recent_events_touch.ex
lib/logflare/backends/recent_inserts_broadcaster.ex

The goal is to reactivate the rule in credo config once it is done for all.

refactor: follow Credo.Check.Readability.ParenthesesOnZeroArityDefs in lib/logflare/backends

---

lib/logflare_web/controllers/admin_controller.ex
lib/logflare_web/controllers/cloudflare_controller.ex
lib/logflare_web/controllers/cloudflare_controller_v1.ex
lib/logflare_web/controllers/plugs/bert_parser.ex
lib/logflare_web/controllers/source_controller.ex

The goal is to reactivate the rule in credo config once it is done for all.

refactor: follow Credo.Check.Readability.ParenthesesOnZeroArityDefs in lib/logflare_web/controllers/*

---

lib/logflare/lql/parser/combinators.ex
lib/logflare/lql/rules.ex
lib/logflare/lql/rules/chart_rule.ex
lib/logflare/lql/rules/filter_rule.ex
lib/logflare/lql/rules/select_rule.ex

The goal is to reactivate the rule in credo config once it is done for all.

refactor: follow Credo.Check.Readability.ParenthesesOnZeroArityDefs in lib/logflare/lql*

---

assets/tailwind.config.js

Removes unnecessary folders from being scanned when building the Tailwind stylesheet.
All folders in `/assets/` were being included in the `content` configuration, which meant Tailwind was looking for classes used in a large number of files. Only `/assets/js/` needs to be scanned.
After this change the compiled CSS is only marginally smaller but the build time is significantly faster which improves startup  times in development. 
The following classes are no longer included in the generated CSS but I couldn't find them used in the app UI:
* -tw-inset-1
* -tw-top-1
* dark
* tw--inset-1
* tw--top-1
* tw-contain-layout
* tw-contain-paint
* tw-contain-size
* tw-contain-style
* tw-divide-x-reverse
* tw-divide-y-reverse
* tw-ordinal
* tw-ring-inset
* tw-slashed-zero
* tw-space-x-reverse
* …

chore: exclude node_modules from tailwind build

---

lib/logflare/logs/source_parsers/syslog_parser.ex

refactor: extract nested code in lib/logflare/logs/source_parsers/syslog_parser.ex

---

lib/logflare_web/controllers/plugs/set_team_user.ex

refactor: extract nested code in lib/logflare_web/controllers/plugs/set_team_user.ex

---

lib/logflare/endpoints.ex
lib/logflare_web/live/endpoints/endpoints_live.ex
test/logflare_web/live_views/endpoints_live_test.exs

Fixes an issue where running a test query from the Endpoints UI would not include query execution labels.
Labels included in the endpoint allowlist will be sent with the test query.
* a label that references a parameter will use the parameter specified in the test query
* an allowlist key (eg. `session_id`, without a static value) will use `"nil"` for the value
* the label `endpoint_id` will be the id of the endpoint, or `nil` if the endpoint is not yet persisted.
Example output from BigQuery jobs explorer, with labels set to `session_id,user_tag=@user_id`

fix: include labels when running Endpoint test queries

---

lib/logflare_web/live/endpoints/components/endpoint_form.html.heex
lib/logflare_web/live/endpoints/endpoints_live.ex
test/logflare_web/live_views/endpoints_live_test.exs

Fixes an issue in the Endpoints UI where an invalid query could cause unsaved changes in the form to be lost.

fix: Endpoints form changes not tracked when query changes

---

lib/logflare_web/live/search_live/timezone_component.ex

refactor: extract nested code in lib/logflare_web/live/search_live/timezone_component.ex

---

lib/logflare/source/text_notification_server.ex

refactor: extract nested code in lib/logflare/source/text_notification_server.ex

---

lib/logflare/source/data.ex

refactor: extract nested code in lib/logflare/source/data.ex

---

lib/logflare_web/live/endpoints/endpoints_live.ex
lib/logflare_web/live/monaco_editor_component.ex
test/logflare_web/live_views/endpoints_live_test.exs

This ensures that endpoint form is uncontrolled. The approach of keeping input state on the client and only taking the submitted values as source of truth ensures that we don't have race conditions which arises with using a changeset as the source of truth.
The monaco editor now holds the state within the live component, and instead uses the assigns value instead of the form field value. This prevents changeset change propagations from causing a reset of the value.
fyi @msmithstubbs

fix: ensure that form is uncontrolled to avoid race conditions

---

lib/logflare/source/bigquery/schema.ex
lib/logflare_web/channels/lv_socket.ex

This should be the last one before we can enable back the rule [Credo.Check.Refactor.Nesting](https://github.com/Logflare/logflare/blob/1d5760494c345c934fc115efe65541b1086c668c/config/.credo.exs#L178). 
Other than this one, the only one needed to be merged is https://github.com/Logflare/logflare/pull/2671.

refactor: improve nested code in lib/logflare/source/bigquery/schema.ex

---

assets/js/source_lv_hooks.js
assets/package-lock.json
assets/package.json

This was only used by a model type `search-op-debug-modal` and that was removed in [8804c89d94042288281aebe0f38d93d9cf21708b](https://github.com/Logflare/logflare/commit/8804c89d94042288281aebe0f38d93d9cf21708b)

chore: remove unused sql-formatter npm package

---

config/.credo.exs

This activates this Credo rule to enforce a limit on the number of nested blocks in our codebase.
Credo will now warn if a function contains more than 2 nested blocks.

chore: re-activate Credo rule for nested code (Credo.Check.Refactor.Nesting)

---

lib/logflare/backends/adaptor/clickhouse_adaptor.ex
lib/logflare/backends/adaptor/clickhouse_adaptor/pipeline.ex

Noticed my clickhouse pool spun down after inactivity (as it should) - but when I tossed a new batch of logs after that it was not spinning back up.
These changes consolidate the logic so the only way to write data to Clickhouse is through `ClickhouseAdaptor.execute_ch_ingest_query/4` - which handles notifying the `ClickhouseAdaptor.ConnectionManager` to ensure the appropriate pool is alive. The old code was calling `Ch.query` directly and skipping this critical check.

fix: handle CH connection pool restart after spinning down due to inactivity

---

lib/logflare/logs/search_operations.ex
lib/logflare/logs/search_queries.ex
lib/logflare/lql/parser/combinators.ex
test/logflare/logs/search_operations_test.exs
test/logflare/lql_test.exs

This PR fixes LQL aggregate parsing for charts query.
improvements include:
- allow aggregates on non-numeric fields (such as counts on string fields)
- aggregates on top-level fields
- more test coverage

fix: correctly parse lql aggregates

---

lib/logflare_web/live/endpoints/components/endpoint_form.html.heex
lib/logflare_web/live/endpoints/endpoints_live.ex
test/logflare_web/live_views/endpoints_live_test.exs

Covers [this comment](https://github.com/Logflare/logflare/pull/2710#discussion_r2317596236) made on #2710 by adding a "Query Language" display under the backend selection.

chore: minor adjustment to display the query language on the endpoints lv form

---

lib/logflare_web/templates/log/log_event_body.html.heex

fix: add in whitespace rendering to LogEvent modal event body

---

.dialyzer_ignore.exs
lib/logflare/ecto/ecto_term_t.ex
test/logflare/ecto/ecto_term_t_test.exs

I could use `Exception.t()` but I think returning the string error is better in this situation.

fix: correctly fix return error as a string

---

.dialyzer_ignore.exs
lib/logflare/google/bigquery/gen_utils.ex

Fix return type as seen in https://github.com/elixir-tesla/tesla/blob/v1.7.0/lib/tesla/client.ex.

fix: corret type for tesla adapter

---

docs/docs.logflare.com/docs/concepts/endpoints.md
lib/logflare/endpoints.ex
lib/logflare/endpoints/pii_redactor.ex
lib/logflare/endpoints/query.ex
lib/logflare_web/live/endpoints/actions/show.html.heex
lib/logflare_web/live/endpoints/components/endpoint_form.html.heex
priv/repo/migrations/20250902185149_add_redact_pii_to_endpoint_queries.exs
test/logflare/endpoints/pii_redactor_test.exs
test/logflare/endpoints_test.exs
test/logflare_web/controllers/endpoints_controller_test.exs
test/logflare_web/live_views/endpoints_live_test.exs

This PR adds in config flag for ipv4 and ipv6 redaction from endpoints query results.
This PR also fixes some bugs relating to displaying of logflare endpoints configuration in the show page.

feat: endpoints PII redaction

---

.dialyzer_ignore.exs
lib/logflare/endpoints.ex

This extra clause by being remove removes another warning. This is a follow up of https://github.com/Logflare/logflare/pull/2722.

fix: remove unecessary function match

---

lib/logflare/backends/adaptor/clickhouse_adaptor.ex
test/logflare/backends/adaptor/clickhouse_adaptor_test.exs
test/support/data_case.ex

My prior 'fix' was incorrect and evaluating the wrong process (the connection pool itself) and instead should have been evaluating the connection manager process as that is what is directly managed by the `ClickhouseAdaptor`.
Aside from this problem, I was also attempting to pattern match `{:ok, _pid}` for the results of `GenServer.whereis/1` which returns a pid or nil value.
A test has been added to ensure the logic operates as expected going forward.
Within the CH adaptor's `init` callback, you can add `ConnectionManager.child_spec({backend, query_ch_opts})` to the children variable and comment out the dynamic check on line 522 and run `mix test test/logflare/backends/adaptor/clickhouse_adaptor_test.exs` to see the difference.

fix: CH connection manager bug with multiple sources

---

DEVELOPMENT.md
docker-compose.yml

The restart automatically is very annoying since it automatically starts the service clickhouse on (which does not happen to the other services in local development e.g. postgres).

chore: remove restart option in clickhouse container for development

---

.github/workflows/elixir-ci.yml
.github/workflows/elixir-migration-check.yml

This fixes CI builds by using the [Bitnami legacy repository](https://hub.docker.com/u/bitnamilegacy).
Announcement about these changes is here: https://github.com/bitnami/containers/issues/83267

ci: Updates postgresql docker images to bitnamilegacy repo

---

lib/logflare_web/live/dashboard_live/dashboard_components.ex
test/logflare_web/live/dashboard_live_test.exs

Removes the member delete button from Dashboard. Members can still be removed from `/account/edit`

ui: remove member delete button from dashboard

---

lib/logflare/gen_singleton/watcher.ex
test/logflare/gen_singleton_test.exs

In preparation for #2763 
UserMetricsPoller needs to be a singleton GenServer but allowed to exit.

feat: allow restart to be specified for GenSingleton.Watcher

---

config/config.exs

- adds 1M request closure for rotating connections for http1/http2
- adds protocol error logging (we had previously disabled it due to client closures being noisy)

perf: tweak bandit connection handling

---

docs/docs.logflare.com/docs/backends/sentry.mdx
lib/logflare/backends/adaptor/sentry_adaptor.ex
lib/logflare/backends/adaptor/sentry_adaptor/dsn.ex
lib/logflare/backends/backend.ex
test/logflare/backends/adaptor/sentry_adaptor/dsn_test.exs
test/logflare/backends/adaptor/sentry_adaptor_test.exs

This PR adds a backend for [Sentry](https://sentry.io/about/), specifically for Sentry's new [structured logging product](https://docs.sentry.io/product/explore/logs/).
resolves https://github.com/getsentry/sentry/issues/95914
To configure the Sentry backend, you need to add a DSN (data source name), which indicates which sentry instance to send logs to. This was chosen over just a regular URL as most users are familiar with getting a DSN from sentry.
To parse the DSN into an endpoint, we use the same logic as we do with Sentry's Elixir SDK: https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/dsn.ex
The Sentry adapter itself is based on the webhook backend. The only thing that is different is that to send data to Sentry, it needs to be sent as an envelope instead of plain …

feat: Add Sentry Adaptor

---

lib/logflare/backends.ex
lib/logflare/cluster/utils.ex
test/logflare/backends_test.exs

This PR adds in faster backend supervisor syncing when adding sources to backends.
it uses multicast instead as we don't really care about the results
Closes ANL-1100

fix: faster backend syncing

---

lib/logflare_web/live/monaco_editor_component.ex
lib/logflare_web/live/query_live.ex

Adds format button to 
1. query page
2. endpoints edit page
3. alerts edit page
* We use `SqlFmt.format_query/1` for formatting which always returns `{:ok, result}` so no any UI is required.
* Have not included unit tests since most of the actual effects here are in the JS layer.
* Event listeners are now setup before rendering the editor 
https://github.com/user-attachments/assets/46247bd7-1d28-43fd-9cbe-0665ada6d2b4
https://github.com/user-attachments/assets/ec113daa-a9a6-420a-ae55-2c3158854248

feat: add format button for formatting SQL queries
