assets/css/app.scss
assets/js/socket.js
lib/logflare/table.ex
lib/logflare/table_counter.ex
lib/logflare/table_manager.ex
lib/logflare/table_rate_counter.ex
lib/logflare_web/controllers/log_controller.ex
lib/logflare_web/controllers/source_controller.ex
lib/logflare_web/templates/source/dashboard.html.eex

Rate counter

---

lib/logflare/source_data.ex
lib/logflare/source_meta_data.ex
lib/logflare/user.ex
lib/logflare_web/channels/dashboard_channel.ex
lib/logflare_web/controllers/admin_controller.ex
lib/logflare_web/controllers/plugs/check_admin.ex
lib/logflare_web/controllers/source_controller.ex
lib/logflare_web/router.ex
lib/logflare_web/templates/admin/dashboard.html.eex
lib/logflare_web/views/admin_view.ex
priv/repo/migrations/20190313222100_add_admin_to_user.exs

Admin stuff

---

lib/logflare/endpoint/query.ex

Solution: ensure we're not trying to map nil queries
That sends a message not handled by logflare_sql

Problem: /endpoints/new times out

---

lib/logflare/endpoint/cache.ex
lib/logflare_web/controllers/endpoint_controller.ex

Solution: explicitly invalidate it

Problem: editing query doesn't invalidate the cached result

---

lib/logflare/endpoint/cache.ex
sql/src/main/kotlin/app/logflare/sql/Main.kt

Logflare.SQL ignores these settings and uses defaults
Solution: it should translate queries according to user settings
and use user's project id for executing queries if it is set

Problem: queries for users with custom BigQuery projectId/datasetId

---

sql/src/main/kotlin/app/logflare/sql/QueryParseError.kt

It's an out of bounds exception
Solution: ensure we respect strings boundaries
when inserting content for error explanation.

Problem: Logflare.SQL crashing when reporting errors

---

README.md

Target branch is now `staging`.

Update README.md with dev setup instructions

---

.gitignore
README.md
config/dev.exs
docker-compose.yml
priv/repo/seeds.exs

Updates docker-compose file that is in use, and added seed data for stripe plans.
Note dev postgres credentials change.

chore: Update docker-compose to v3, added stripe seed, streamlined setup docs

---

config/prod.exs
lib/logflare/admin.ex
lib/logflare_web/live/admin/cluster_live.ex

Merged in #1117 without doing a `mix format`

chore: Fix formatting

---

lib/logflare/saved_searches/saved_searches.ex
test/logflare/saved_searches_test.exs

refactor will be in separate child PR
Reference ticket: [link](https://www.notion.so/supabase/Code-cleanup-test-coverage-refactoring-documentation-7088e54b06e94963adbc2a141c8f6992#15da7b02d917406f86fadd3764c64c1e)

Chore: SavedSearches code cleanup

---

lib/logflare_web/controllers/stripe_controller.ex
test/logflare/logs/ingest/ingest_typecasting_test.exs
test/logflare/logs/ingest/metadata_cleaner_test.exs
test/logflare/logs/vercel/vercel_lambda_parser_test.exs

Small PR, adds underscoring for large numbers, linting error raised by credo.
Reference ticket: https://www.notion.so/supabase/WIP-Add-in-Logflare-to-Quality-Gate-2ba0d013846f413f97a17ba22e52f06a

chore: fix linting warnings for large numbers underscoring

---

.github/workflows/tests.yml
lib/logflare_web/controllers/admin_controller.ex
lib/logflare_web/controllers/source_controller.ex
lib/logflare_web/controllers/user_controller.ex
lib/sig_term_handler.ex

Turns out, github actions are not running due to indentation error 😠 yaml doing its thing again :shakes_fist: so all PRs are showing up as passing since the checks aren't even runnning
This PR fixes the indentation.

fix: github actions indentation error

---

coveralls.json

add additional files to be skipped by coveralls

chore: add /tests and /lib/mix to coveralls skip files

---

README.md
assets/package.json
assets/yarn.lock
config/dev.exs
lib/logflare/sources.ex
lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/controllers/source_controller.ex
lib/logflare_web/router.ex
mix.exs
mix.lock
test/logflare/source/billing_writer_test.exs
test/logflare/sources_test.exs
test/logflare_web/controllers/api/source_controller_test.exs
test/logflare_web/controllers/source_controller_test.exs
test/support/conn_case.ex

New API endpoints to index sources for logged-in accounts.
* GET `/api/sources`  - Lists all sources for logged in account

Index Sources for Account

---

docs/docs.logflare.com/docs/querying/index.mdx

Add docs for chart aggregations
reference [ticket](https://www.notion.so/supabase/Add-in-aggregates-documentation-into-lql-reference-2c3a7d8688ce4518a9d4d935fd635db7)

docs: add chart aggregation docs

---

lib/logflare/ecto/ecto_uuid_atom_t.ex
lib/logflare/sources.ex
lib/logflare/sources/source.ex
lib/logflare_web/controllers/api/fallback_controller.ex
lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/router.ex
test/logflare/sources_test.exs
test/logflare_web/controllers/api/source_controller_test.exs
test/support/conn_case.ex

Adds multiple operations to an accounts source API 
* GET `/api/sources/:token` - Creates a new source to a given user
* POST `/api/sources` - Creates a new source to a given user
* PATCH `/api/sources/:token` - Updates a given source
* DELETE `/api/sources/:token` - Deletes a given source

Account operations source api

---

lib/logflare/utils/deep_update.ex
test/logflare/utils_test.exs

Adds doctests for EnumDeepUpdate, originally from PR https://github.com/Logflare/logflare/pull/1167

chore: EnumDeepUpdate - add typespecs, docstests

---

config/dev.exs
lib/logflare_web/controllers/api/source_controller.ex
mix.exs
test/logflare_web/controllers/api/source_controller_test.exs

Show endpoint had bad test cases and bad implementation. This PR fixes both and also simplifies tests and applies other refactoring suggestions

Fix Show endpoint ; Apply more refactoring suggestions

---

.github/workflows/pages-build.yml
.github/workflows/pages.yml

this should fix the npm cache errors for the pages build

docs: add cache keys for pages build

---

assets/js/source.js
assets/js/source_lv_hooks.js
lib/logflare_web/live/search_live/templates/logs_search.html.leex
lib/logflare_web/templates/source/show.html.eex

Holy crap I could never get this to work before! Just needed to go in a different spot.

Use IntersectionObserver instead

---

lib/logflare_web/live/search_live/templates/logs_search.html.leex

fixes failing tests on staging.

fix: remove unused phx-update ignore attr

---

lib/logflare/ecto/bigquery/ecto_bq_query_api_udf.ex

Tests pass and manually working through things in the UI works as well. Needs some tests around this probably.

Fix quoted interval

---

.github/workflows/pages-build.yml
.github/workflows/pages.yml
.github/workflows/tests.yml

Fixes github actions migration to newly maintained [project here](https://github.com/erlef/setup-beam). Previous version was using [this](https://github.com/actions/setup-elixir) and has since been archived.
also added another pages deploy fix

chore: update github actions setup

---

lib/sig_term_handler.ex

SIGTERM handler wasn't actually waiting at all.

bug: make sigterm handler actually wait

---

docs/docs.logflare.com/docs/querying/index.mdx

fix: anchor link

---

lib/logflare_web/templates/marketing/pricing.html.eex

I spotted this typo error on the website.

fix: small error on website

---

.github/workflows/pipeline.yml
Dockerfile
cloudbuild/staging/cloudbuild.yaml

* Separate Docker steps to be in two jobs so we can parallelize docker build and push

Improve GH actions pipeline

---

docker/staging.app.Dockerfile
run.sh

* Moved the secrets file to an absolute folder (/tmp)
* Removed unnecessary Docker line
* Changed run script to use the absolute path

Fix run script and Docker image

---

run.sh

Makes the output of the export be silent

Make output from export be silent

---

lib/logflare/release.ex

Ensuring that :ssl application starts since we're still seeing errors of not properly booting up

Ensure ssl application starts

---

Dockerfile

Adding the priv folder so static assets load properly and we have migrations being ran.

Fix lack of priv folder

---

config/dev.exs
config/prod.exs
config/runtime.exs
config/staging.exs
config/test.exs
docker-compose.yml

* Properly load .secrets.env file
* Properly load gcloud.json file
* Fix hostname error where server wasn't starting up properly due to docker short name
* Make Logger configurable

Fix local environment

---

config/prod.exs
config/runtime.exs
config/staging.exs
lib/logflare_web/endpoint.ex

* Used the code_reload flag to set the usage of gzip
* Removed the loading of secrets.exs
* Removed special handle of CORS

Fix gzip option on static assets

---

docker/staging.app.Dockerfile

The location of the gcloud.json file was in the wrong folder

Fix bad path on Staging image build

---

.github/workflows/pipeline.yml
.tool-versions

Changed the way we call the webhook to use curl directly
Also updated Erlang version in local development for a new minor due to some asdf issues on install

Update webhook call

---

.github/workflows/pipeline.yml

No need when fetching secrets and lead to a bad key

Removed the GH mask

---

lib/logflare_web/templates/marketing/index.html.eex

Fix for home page, which is out of sync with pricing page. Was raised by customer.

fix: update home page to match current pricing

---

.github/workflows/pipeline.yml

Trying a new Cloudbuild webhook curl request

Update Cloudbuild Webhook

---

.github/workflows/pipeline.yml

Improve output of webhook call by only receiving the field name but have more output in case of error

Improve webhook call output

---

run.sh

Bad if condition broke the run.sh script breaking the deployment

Fix run.sh script if condition

---

run.sh

Fixes if condition on run.sh script

Fix if statement on run script

---

config/prod.exs

Hotfixing this to get it on prod.

hotfix: update internal IP address for db

---

config/test.exs

chore: update console logging for tests to only show errors.

---

lib/logflare_web/controllers/auth/auth_controller.ex

Add in more logging for unhandled error messages, for debugging sign-in related errors

chore: add logging for sign in errors

---

lib/logflare_web/controllers/log_controller.ex
test/logflare_web/controllers/log_controller_test.exs

We should be able to handle an array of log events as the POST request body.

feat: handle json list as batch

---

config/config.exs
config/prod.exs
lib/logflare_web/router.ex

Set up Swoosh local mailbox for development on route `http://localhost:4000/dev/mailbox`

Add Swoosh Local mailbox

---

.github/workflows/docker-ci.yml
.github/workflows/elixir-ci.yml

Decouples docker and elixir ci to speed up PR checks

chore: decouple image building and elixir ci

---

assets/css/homepage.scss
lib/logflare_web/templates/marketing/index.html.eex

fix: homepage embed styling

---

lib/logflare/google/resource_manager.ex
test/logflare/google/resource_manager_test.exs

Removed wrong role and moved the role to the API SA

Fix Google Resource permissions

---

assets/package.json
assets/yarn.lock

Bump up two dependencies to improve our yarn audit results: Before
`Severity: 3 Low | 1 Moderate | 12 High`
After
`Severity: 1 Moderate | 6 High`

Improve yarn audit results

---

assets/js/formatters.js
assets/js/source_log_chart.jsx

The way we were importing the DateTime object lead to FE issues. This fixes said issue by access the proper object.

(fix) Luxon DateTime import

---

lib/logflare_web/controllers/api/endpoint_controller.ex
lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/open_api_schemas.ex

Added Open API Specs for Source Management endpoint.

(chore) Add Source OAS documentation

---

lib/logflare_web/controllers/api/endpoint_controller.ex
lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/controllers/api/team_controller.ex
lib/logflare_web/open_api_schemas.ex

Added Open API Specs for Team Management endpoint.

(chore) Add Team OAS documentation

---

README.md
config/dev.exs
docker-compose.yml
priv/repo/seeds.exs

Adds Stripe Mock server for dev environment so we can develop billing features easily.

(add) Stripe Mock server for dev environment

---

.github/workflows/docker-ci.yml

Adds ARM64 to docker images so they are compatible with macos

Add ARM64 platform to builded docker image

---

.github/workflows/docker-ci.yml

Currently it's taking a long time, probably due to some error in the approach. Will separate the actions for now and improve later.

Add extra jobs for arm building

---

.github/workflows/docker-ci.yml

For now we want to focus on having the images compatible with macos (darwin)

Change from ARM to Darwin as a platform

---

lib/logflare_web/controllers/api/endpoint_controller.ex
lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/controllers/api/team_controller.ex
lib/logflare_web/open_api.ex
lib/logflare_web/open_api_schemas.ex

* Create a common list schema from a given module with schema
* Create macro to reduce boilerplate for object schemas

Reduce OAS generation boilerplate

---

lib/logflare/billing.ex
lib/logflare/billing/billing_counts.ex
lib/logflare_web/live/billingaccount_live/chart_component.ex
lib/logflare_web/live/billingaccount_live/edit.ex
lib/logflare_web/live/billingaccount_live/estimate_usage_component.ex
lib/logflare_web/live/billingaccount_live/templates/edit.html.leex
test/logflare/billing/billing_counts_test.exs
test/logflare/billing_test.exs
test/logflare_web/live/billingaccount_live/estimate_usage_component_test.exs
test/logflare_web/live_views/logs_search_lv_test.exs
test/support/factory.ex
test/support/test_utils.ex

* Adds element to show usage and cost estimate
* Adds tests to BillingCounts

(add) Table to show estimate price and usage.

---

Dockerfile

fix: alpine version bump

---

assets/package-lock.json
assets/package.json

Error due to the way ESM works with Nivo:
https://github.com/plouc/nivo/issues/1455
Bumping to minimum version where the issue is fixed

(fix) Issue with nivo and ESM

---

.github/workflows/arm-docker-latest-push.yml
.github/workflows/arm-docker-versioned-push.yml
.github/workflows/docker-ci.yml
Dockerfile

Create ARM image to be used on macos.

Build Docker image for ARM platform

---

run.sh

Fixes a syntax error in the run.sh, which i discovered while working on the cli integration

fix: bad if/else conditional

---

docs/docs.logflare.com/docs/concepts.md

docs on schema behaviour as well as workarounds for new schema structure.

docs: additive schema info

---

docs/docs.logflare.com/docs/backends/bigquery/index.md

documentation on streaming insert error.

docs: add streaming insert error docs

---

Dockerfile

Revert "chore: expose more ports for cli"

---

.github/workflows/docker-ci.yml
.github/workflows/mirror.yml

New feature
--- 
After publishing a new docker image to prod, also mirror to ECR and GHCR

chore: add workflow for mirroring images

---

.github/workflows/release-checks.yml

adds checks for whether files are changed for PRs that are staging -> master

chore: add release checks workflow

---

lib/logflare/single_tenant.ex

reference thread: https://supabase.slack.com/archives/C032VRDHPDE/p1680570729763879

fix: update supabase endpoints cache settings

---

lib/logflare_web/api_spec.ex

Sets the type of token expected to use the Management API

add: Set the type of authentication used by Management API

---

DEVELOPMENT.md

ref thread: https://supabase.slack.com/archives/C032VRDHPDE/p1680508083556509

docs: dev docs for release management

---

docs/docs.logflare.com/docs/querying/index.mdx
docs/docs.logflare.com/docs/querying/lql.md
lib/logflare_web/templates/shared/lql_help.html.leex
lib/logflare_web/views/docs_view.ex

consoldiates LQL docs into correct page

docs: remove duplicate lql docs

---

README.md
lib/logflare_web/templates/marketing/homepage_cta.html.eex
lib/logflare_web/templates/shared/logflare_services_list.html.eex
lib/logflare_web/templates/source/no_logs_modal.html.eex

Fixes broken cloudflare links, seems like CF changed their app install link again...

fix: updates cloudflare install links

---

.github/workflows/docker-ci.yml

The way the configuration was set we were not triggering staging cloudbuild properly

fix - Trigger Cloudbuild when we merge staging

---

assets/js/admin_dashboard_charts.jsx
assets/js/source_log_chart.jsx

Fixes the Background color on the tooltips of graphs

fix - Background color for graphs

---

run.sh

fix: echo LOGFLARE_NODE_HOST

---

lib/logflare/release.ex

Removed the line where we were starting the full logflare application which lead to errors when we added a new node to the cluster

fix - Remove unnecessary startup of the full application

---

Dockerfile

Optimizes the builder layers for actions caching.

chore: optimize dockerfile builder layers for caching

---

config/runtime.exs

Change the GRPC server SSL configuration.

change - Modify SSL configuration for GRPC server

---

lib/logflare/sql_v2.ex
test/logflare/sql_test.exs

Adds support for BigQuery fully qualified table names.
This allows users to make LF endpoint queries directly to specific BigQuery tables/views.
Related tickets:
- [daily_stats table migration](https://www.notion.so/supabase/Remove-reliance-on-daily_stats-table-move-to-querying-through-LF-3daa08c6bd514e7dbb0d848dcd4c3c50?pvs=4)
- [query compute runtime hours](https://www.notion.so/supabase/Ability-to-query-compute-runtime-hours-9fe63363978848d09dfe84cea6adadbc?pvs=4)

feat: add support for fully qualified bigquery names

---

cloudbuild/prod/cloudbuild.yaml
cloudbuild/secret_setup.Dockerfile
cloudbuild/staging/cloudbuild.yaml
mix.exs
run.sh

Each new cloudbuild will creates a new magic cookie and stores it in a file to be used by the startup script
Also set a random value if the file isn't present to avoid issues in self hosted

fix - Fix cookie setup

---

cloudbuild/prod/cloudbuild.yaml

Removes Magic Cookie from Cloudbuild file since those will be created upon container creation

fix - Remove Magic Cookie from Cloudbuild file

---

lib/logflare/sql_v2.ex
test/logflare/endpoints_test.exs

fixes the source mapping bug where bugs where non-source names were getting run through the mapping.

fix: source mapping bug for fully qualified names

---

run.sh

Releases this again so that there is an actual fix in the release.

Release v1.3.7 again

---

lib/logflare/endpoints/query.ex

Always enable auth on new endpoints

fix: default to enabling auth for all new endpoints.

---

lib/logflare_web/templates/auth/email/email_login.html.eex

Adds autofocus for email auth, as per customer suggestion.
https://app.hubspot.com/live-messages/19953346/inbox/4682284807#email

feat: add autofocus to email auth

---

lib/telemetry.ex

add in missing caches into telemtry

fix: add in telemetry caches

---

lib/logflare/application.ex
lib/logflare/backends/adaptor/postgres_adaptor.ex
lib/logflare/backends/adaptor/postgres_adaptor/log_event.ex
lib/logflare/backends/adaptor/postgres_adaptor/pipeline.ex
lib/logflare/backends/adaptor/postgres_adaptor/repo.ex
lib/logflare/backends/adaptor/postgres_adaptor/repo/migrations/add_log_events.ex
lib/logflare/backends/adaptor/webhook_adaptor.ex
test/logflare/backends/adaptor/postgres_adaptor/pipeline_test.exs
test/logflare/backends/adaptor/postgres_adaptor/repo_test.exs

Adds a new way to setup table names based on the source id so we can better control where information goes which will simplify querying at the cost of extra dynamic module loading

add - Dynamic table names based on source

---

assets/js/interfaces/ShowEndpoint.jsx
lib/logflare/backends/adaptor/postgres_adaptor/repo.ex
lib/logflare/backends/adaptor/webhook_adaptor.ex
lib/logflare/ecto/bigquery/bq_repo.ex
lib/logflare/endpoints.ex
lib/logflare/endpoints/query.ex
lib/logflare/endpoints/resolver.ex
lib/logflare/sources.ex
lib/logflare/sql_v2.ex
lib/logflare_web/live/endpoints_live.ex
test/logflare/backends/adaptor/postgres_adaptor/pipeline_test.exs
test/logflare/backends/adaptor/postgres_adaptor/repo_test.exs
test/logflare/endpoints_test.exs
test/logflare/sql_test.exs
test/logflare/sql_v2_test.exs

Added the possibility of using Postgres as a backend for Endpoints based on the Source Mappings of a given query

add - Endpoints using Postgres Backend

---

priv/supabase/ingest_samples/gotrue.logs.prod.json

adds in missing schema keys from the gotrue source.
source schema used as reference is [here](https://logflare.app/sources/16129/search?querystring=&tailing%3F=false)

fix: add in more schema keys

---

docs/docs.logflare.com/docs/concepts/ingestion/index.mdx
lib/logflare_web/live/search_live/logs_search_lv.ex
lib/logflare_web/templates/source/edit.html.eex
test/logflare_web/live/search_live/logs_search_lv_test.exs

This PR adds in rendering of the suggested keys to display the keys, for better ux.
This PR also adds in more documentation around the suggested search keys.

feat: add suggested keys to flash message

---

lib/logflare/sql.ex
test/logflare/sql_test.exs

This PR focuses BQ->PG syntax translation for logflare-specific querying.

feat: bq -> pg basic translation part 1

---

config/runtime.exs
lib/logflare/backends.ex
lib/logflare/backends/adaptor/postgres_adaptor.ex
lib/logflare/backends/adaptor/postgres_adaptor/pg_repo.ex
lib/logflare/single_tenant.ex
lib/logflare/sources.ex
lib/logflare/sources/source.ex
lib/logflare_web/live/source_backends_live.ex
test/logflare/backends/postgres_adaptor_test.exs
test/logflare_web/live/source_backends_live_test.exs
test/support/test_utils.ex

Adds Schema support for Postgres Backends as a Backend configuration

Support db schema on pg repo

---

lib/logflare/backends/adaptor/postgres_adaptor.ex

Trying to get around some weird postgres behaviour where it does not set the correct `search_path` after connecting. might be an issue with postgrex, will still need further investigation

fix: explicitly set search path for custom schema for postgres query execution

---

lib/logflare/sql.ex
test/logflare/sql_test.exs
test/logflare_web/controllers/endpoints_controller_test.exs

Add in cross join unnnest translation handling in the outer cte query.

feat: add cross-join unnest handling in cte query translation

---

lib/logflare/sql.ex
test/logflare/sql_test.exs
test/logflare_web/controllers/endpoints_controller_test.exs

fix for jsonb comparison in binary ops.

fix: binary op text comparison jsonb casting

---

docs/docs.logflare.com/docs/integrations/postgres-fdw.md

This PR adds supplementary docs and links to official docs for the Logflare FDW

docs: add documentation for Logflare FDW

---

docs/docs.logflare.com/docs/backends/postgres/index.md
docs/docs.logflare.com/docs/self-hosting/index.md

Adds postgres backend documentation, and updates self-hosting docs

docs: add postgres backend docs, self-hosting docs update

---

lib/logflare/endpoints/query.ex
lib/logflare_web/live/endpoints/actions/index.html.heex
lib/logflare_web/live/endpoints/actions/show.html.heex
lib/logflare_web/live/endpoints/components/endpoint_form.html.heex
priv/repo/migrations/20230807162746_add_endpoint_query_description_column.exs
test/logflare_web/live_views/endpoints_live_test.exs
test/support/factory.ex

Adds a description field for endpoints
https://github.com/Logflare/logflare/assets/22714384/8ca60c13-5ca8-4dc3-ba96-36553e4d56e7

feat: Add description field for endpoints

---

lib/logflare/source/text_notification_server.ex
lib/logflare_web/controllers/source_controller.ex
lib/logflare_web/templates/marketing/pricing.html.eex
lib/logflare_web/templates/source/edit.html.eex
test/logflare/source/text_notification_server_test.exs
test/logflare_web/controllers/source_controller_test.exs
test/test_helper.exs

Free plan should not have the SMS functionality

fix: free plans should not have sms alert functionality

---

lib/logflare_web/live/endpoints/actions/show.html.heex

This PR fixes the curl command example for endpoints.

fix: curl command example

---

mix.exs
test/logflare_web/controllers/endpoints_controller_test.exs
test/support/conn_case.ex

- chore: fix typo in test name
- fix: make version loading more foolproof
- chore: move helper functions to parent module to reduce amount of generated code

test: cleanup tests

---

lib/logflare/alerting.ex
lib/logflare_web/live/alerts/actions/show.html.heex
lib/logflare_web/live/alerts/alerts_live.ex
test/logflare/alerting_test.exs
test/logflare_web/live_views/alerts_live_test.exs

This PR adds in a manual trigger button to allow easy testing of an alert.

feat: manual trigger of alerts

---

lib/logflare_web/templates/source/dashboard.html.eex

Removes dashboard onboarding message for more space on home page.
Part of reorganizing and improving home layout.

chore: remove dashboard onboarding message

---

config/runtime.exs

Passes ssl options to db connection

fix: pass ssl options to db connection

---

test/logflare_grpc/trace/server_test.exs

This will allow running tests while application is up and running.

test: run tests on dynamic port

---

cloudbuild/prod/pre-deploy.yaml

fix: instance template project id name

---

lib/logflare/logs/browser_report.ex
lib/logflare/logs/generic_json.ex
lib/logflare/logs/github.ex
lib/logflare/logs/ingest_typecasting.ex
lib/logflare/logs/netlify.ex
lib/logflare/logs/processor.ex
lib/logflare/logs/raw.ex
lib/logflare/logs/vector.ex
lib/logflare/logs/vercel.ex
lib/logflare_web/controllers/log_controller.ex
lib/telemetry.ex
test/logflare/logs/ingest/ingest_typecasting_test.exs

In addition to the fixed pipeline this commit adds Telemetry metrics to ingestion pipeline. For now it is rather crude approach where there is single metric for everything happening (no detailed view), but that will be added in near future.

ft: refactor ingest processing pipeline

---

lib/logflare/endpoints.ex
lib/logflare/endpoints/query.ex
priv/repo/migrations/20231023174255_remove_sandbox_query_id_column_from_endpoint_queries_table.exs
test/logflare/endpoints_test.exs

remove sandboxed query feature in favour of query composition

chore: remove sandboxed query feature

---

.github/workflows/trigger-cloudbuild.yml
Makefile

Looks like a auto formatting error mangled the ci trigger condition for the auto deploy for versioned.

fix: ci cloudbuild auto deploy

---

.github/workflows/docker-ci-amd-and-arm.yml
.github/workflows/trigger-cloudbuild.yml
Makefile

Fixes for short sha generation, i noticed that it is not uniform across ci vs local

chore: use 7 length short sha

---

lib/logflare_web/controllers/auth/oauth_controller.ex
test/logflare_web/controllers/oauth_controller_tests.exs

string port value should be converted to number.

fix: string port configs

---

lib/logflare_web/controllers/admin_controller.ex
lib/logflare_web/templates/source/dashboard.html.eex
test/logflare_web/controllers/admin_controller_test.exs
test/support/factory.ex

This fixes the admin functionality for taking control of a user account

fix: become user when cookies are set

---

Makefile

switches cloudbuild region to europe-west1

chore: update cloudbuild region

---

lib/logflare_web/router.ex

This PR adds in generalized `/api/events` path so that routing is not logs specific

feat: generalized events path

---

lib/logflare/cache_buster.ex
lib/logflare/context_cache.ex

This change makes `ContextCache.bust_keys` function fetch keys from the cache only once instead repeatedly for each busted key individually.
This is still not perfect implementation, but at least should reduce the problem with `CacheBuster` stalling and making its inbox grow uncontrollably.

fix: fetch cache keys only once

---

.github/workflows/elixir-ci.yml

fixes inclusions and exclusions for elixir ci

chore: add inclusions to ci workflow

---

.github/workflows/docker-ci-amd-and-arm.yml
.github/workflows/docker-retag-versioned.yml
.github/workflows/trigger-cloudbuild.yml
Makefile

Improving the versioned tagging flow for faster versioned deploys.

chore: retagging versioned

---

lib/logflare_web/controllers/plugs/fetch_resource.ex
test/logflare_web/controllers/log_controller_test.exs

This PR adds in uuid checks within plug resource fetching

fix: uuid checks for source fetching

---

run.sh

postgres strategy changes still require gce networking config to be set

chore: fix condition for setting LOGFLARE_NODE_HOST

---

lib/logflare/cluster/postgres_strategy.ex

This adds a channel prefix for the postgres listen/notify channels, as it is possible for certain cookie values to clash with postgres keywords.

fix: add channel prefix for listen/notify channels

---

lib/logflare/logs/logs.ex
lib/telemetry.ex

This PR adds in telemetry around reject rates, drop rates, and buffer full rates.

feat: telemetry around reject rates, drop rates, buffer full

---

lib/logflare/backends/common_ingest_pipeline.ex
lib/logflare/source/bigquery/pipeline.ex
lib/telemetry.ex

Adds telemetry around the batch size for both v1 and v2 pipeline

feat: telemetry batch size

---

docs/docs.logflare.com/docs/self-hosting/index.md

docs: add self-hosting ui auth tips

---

rel/env.sh.eex

fix: unterminated quoted string error

---

Makefile

fix: main cluster deployment shitdown script

---

lib/logflare/partners.ex
lib/logflare/user.ex
lib/logflare/users/users.ex
lib/logflare_web/controllers/api/partner/account_controller.ex
priv/repo/migrations/20231207113137_add_user_metadata_column.exs
test/logflare/partners_test.exs
test/logflare/users/users_test.exs

This PR implements a Users metadata column and adds in dynamic User filtering.

feat: Users metadata

---

lib/logflare_web/controllers/plugs/compressed_body_reader.ex
test/logflare_web/plugs/compressed_body_reader_test.exs

This PR doubles the max chunks inflated limit, for handling much larger batch sizes.

fix: increase max chunks inflation

---

cloudbuild/prod/pre-deploy.yaml
cloudbuild/staging/deploy.yaml
cloudbuild/startup.sh

This adds the `node-problem-detector` service as per milelync suggestions.

chore: add node-problem-detector, bump to cos109, add in provisioning model.

---

cloudbuild/prod/pre-deploy.yaml
cloudbuild/secret_setup.Dockerfile
cloudbuild/staging/deploy.yaml
cloudbuild/startup.sh
docker-compose.yml
run.sh

Startup script via metadata file is async from server startup, so this changes it to be syncronous via a startup.sh file.
Also, added in more debugging echos

fix: startup.sh optional sourcing in run.sh

---

lib/logflare/logs/logs.ex
lib/logflare/source/bigquery/pipeline.ex
lib/logflare/source/bigquery/schema.ex

chore: add more logger metadata

---

lib/logflare/sources/source_routing.ex
lib/logflare_web/controllers/source_controller.ex
lib/logflare_web/templates/rule/source_rules.html.heex
test/logflare/sources/source_routing_test.exs
test/logflare_web/live_views/source_rules_lv_test.exs
test/support/factory.ex

This fixes a bug where number fields were not getting correctly matched for regex filters.
It also fixes a page rendering bug. 
An old failing test has also been removed. Subsequent refactoring of the tests will come later.

fix: source routing bugs

---

lib/logflare/source/bigquery/schema.ex

for debugging supabase log sources.

chore: add more log metadata around schema updates

---

lib/logflare/context_cache.ex

cache value key selection is currently not extensible to other undeclared structs, which is likely interfering with caching.

fix: makes primary key selection extendible for different structs

---

lib/logflare_web/live/alerts/components/alert_form.html.heex

Fixes deletion form submission bug

fix: alerts deletion bug

---

lib/logflare/auth/cache.ex
lib/logflare/billing/cache.ex
lib/logflare/context_cache.ex
lib/logflare/partners/cache.ex
lib/logflare/source_schemas/cache.ex
lib/logflare/sources/cache.ex
lib/logflare/users/cache.ex
lib/logflare/utils.ex

For minimizing risk of stale data.

fix: context cache expirations

---

lib/logflare/backends.ex
lib/logflare/backends/backend.ex
lib/logflare/single_tenant.ex
lib/logflare_web/controllers/api/backend_controller.ex
lib/logflare_web/live/source_backends_live.ex
lib/logflare_web/open_api_schemas.ex
lib/logflare_web/router.ex
priv/repo/migrations/20240223104413_add_token_field_to_backends_table.exs
test/logflare_web/controllers/api/backend_controller_test.exs
test/logflare_web/live/source_backends_live_test.exs

Backends management api controller.
depends on #1976

feat: backends api controller

---

lib/logflare_web/live/plans_live.ex

should be max events within the month

docs: pricing max events

---

lib/logflare/user.ex
test/support/factory.ex

chore: update user factory to UUID

---

lib/logflare/backends/adaptor/postgres_adaptor.ex
test/logflare/backends/postgres_adaptor_test.exs

Fixes a bug with postgres connection string validation

fix: postgres connection string config validation

---

.github/workflows/elixir-ci.yml

chore: split migrations and tests in CI

chore: split migrations and tests in CI

---

lib/logflare/logs/log_event.ex
test/logflare/log_event_test.exs

**Stack:**
* https://github.com/Logflare/logflare/pull/2006
---
ft: support accessing other top-level fields

ft: support accessing other top-level fields

---

.github/workflows/elixir-ci.yml
test/logflare/source/bigquery/schema_test.exs
test/logflare_web/live/search_live/logs_search_lv_test.exs
test/support/test_utils.ex

**Stack:**
* https://github.com/Logflare/logflare/pull/2000
---
test: use better way to retry tests

test: use better way to retry tests

---

lib/logflare/google/bigquery/gen_utils/gen_utils.ex

This PR adds caching to the gen_utils utility functions

perf: gen_utils should use caches

---

lib/logflare_web/templates/source/edit.html.eex
lib/logflare_web/utils.ex

Multi-backends  feature flag was not targeting users.

fix: feature flagging correctly shows features for multi-backends

---

cloudbuild/prod/deploy.yaml
cloudbuild/prod/pre-deploy.yaml
cloudbuild/staging/deploy.yaml
lib/logflare/alerting.ex

- reduce deployment min ready time between node startup
- tweak alerting min cluster nodes, 7 for prod, 3 for staging

chore: tweak deployment configs

---

lib/logflare/logs/vercel/nimble_vercel_parser.ex
test/logflare/logs/vercel/vercel_lambda_parser_test.exs

This fixes vercel request log parsing

fix: vercel request parsing bug

---

lib/logflare/application.ex
lib/logflare/cache_buster.ex
lib/logflare/context_cache.ex
lib/logflare/source/bigquery/schema.ex
lib/logflare/source/email_notification_server.ex
lib/logflare/source/text_notification_server.ex
lib/logflare/team_users/cache.ex

Cache TeamUsers table which is used for Schema update notifications

perf: cache TeamUsers table

---

test/logflare/backends_test.exs

```
Name                                                  ips        average  deviation         median         99th %
SourceSup v2 BQ with Backends.ingest_logs/2       1264.06        0.79 ms    ±34.97%        0.80 ms        1.68 ms
SourceSup v2 BQ with Logs.ingest_logs/2            370.75        2.70 ms    ±61.23%        2.63 ms        5.59 ms
v1SourceSup BQ with Logs.ingest_logs/2             369.72        2.70 ms    ±61.33%        2.67 ms        5.83 ms
Comparison: 
SourceSup v2 BQ with Backends.ingest_logs/2       1264.06
SourceSup v2 BQ with Logs.ingest_logs/2            370.75 - 3.41x slower +1.91 ms
v1SourceSup BQ with Logs.ingest_logs/2             369.72 - 3.42x slower +1.91 ms
Extended statistics: 
Name                                                minimum        maximum …
```

perf: benchmark v2 pipeline Backends.ingest_logs/2

---

lib/logflare/cluster/postgres_strategy.ex

Add more logging around connection failures

chore: add logging around connection failures for Postgres Strategy

---

cloudbuild/prod/pre-deploy.yaml
cloudbuild/staging/deploy.yaml

fix: specify cos 109

---

lib/logflare_web/live/search_live/logs_search_lv.ex

Performs refactoring that cleans up the following:
- remove connected/disconnected differing logic for simplicity sake.
- Remove duplicate searching on mount, as search already gets triggered in the `handle_params/3` callback. This was causing lql query to get parsed 3 times.
- reorganizes assigns and removed duplicates.

chore: refactor logs search liveview

---

lib/logflare_web/live/log_event_live/search_log_event_viewer_component.ex
lib/logflare_web/live/search_live/logs_search_lv.ex
lib/logflare_web/live/search_live/templates/logs_search.html.heex
lib/logflare_web/live/search_live/user_prefs_component.ex
test/logflare_web/live/search_live/logs_search_lv_test.exs
test/support/factory.ex

https://github.com/Logflare/logflare/assets/22714384/63c85c64-0d64-460e-8cd4-09189db3001d
Depends on #2058

feat: timezones in url

---

assets/js/app.js
assets/js/log_event_live_hooks.js
assets/js/source_lv_hooks.js
lib/logflare_web/templates/log/log_event_body.html.heex

Fixes copy to clipboard event modal
https://github.com/Logflare/logflare/assets/22714384/a334137b-8c9e-48fc-ac57-49dce040a006

fix: copy-to-clipboard for log event modal

---

lib/logflare_web/controllers/api/backend_controller.ex
lib/logflare_web/controllers/api/endpoint_controller.ex
lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/controllers/api/team_controller.ex

Fixes response codes for controllers for patch method.

fix: patch backend response code

---

lib/logflare/application.ex
lib/logflare/single_tenant.ex
test/logflare/single_tenant_test.exs
test/support/test_utils.ex

Fixes single tenant mode where config is obtained from the env vars.
https://github.com/supabase/supabase/issues/22605

fix: upsert postgres backend for single tenant mode

---

cloudbuild/prod/pre-deploy.yaml
cloudbuild/staging/deploy.yaml

Fixes instance template config for the named ports

fix: OTEL instance template staging/prod port

---

cloudbuild/prod/build-image.yaml
cloudbuild/staging/build-image.yaml
config/runtime.exs
lib/logflare/application.ex

Reverts origin server configurations for ssl, and removes custom ca cert file and uses public cacerts instead.

fix: revert origin server cert, remove custom ca cert file, use public certs for ssl

---

cloudbuild/secret_setup.Dockerfile
config/runtime.exs

Fixes cacert copying and loading at runtime.

fix: cacert copying in dockerfile

---

lib/logflare_web/controllers/api/query_controller.ex
lib/logflare_web/open_api.ex
lib/logflare_web/open_api_schemas.ex
lib/logflare_web/router.ex
test/logflare_web/controllers/api/query_controller_test.exs

Adds parsing private api route for parsing sql queries.

feat: parse sql queries api endpoint

---

lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/open_api_schemas.ex
lib/logflare_web/router.ex
test/logflare_web/controllers/api/source_controller_test.exs

Adds a private api route for fetching recent logs

feat: recent logs api route

---

config/runtime.exs

To allow disabling of the grpc ssl at instance template level

feat: add LOGFLARE_ENABLE_GRPC_SSL flag

---

lib/logflare/erl_sys_mon.ex

This adds process info to ErlSysMon, starting with process dict

feat: add process info to ErlSysMon

---

lib/logflare/backends.ex
lib/logflare/pubsub_rates/cache.ex
lib/logflare_web/controllers/plugs/buffer_limiter.ex
lib/logflare_web/live/search_live/user_prefs_component.ex
lib/logflare_web/router.ex
test/logflare_web/live/search_live/logs_search_lv_test.exs
test/logflare_web/plugs/buffer_limiter_test.exs

This PR adds a buffer check, if it is above the hardcoded max buffer, it will return 429 to clients.

feat: buffer limiter

---

Makefile

Adds ssl self-signed cert generation target to makefile

feat: add ssl generation commands to makefile

---

test/logflare/backends_test.exs

This PR adds in benchmarking for source rules routing
```
Benchmarking 100 rules ...
Benchmarking with rules ...
Calculating statistics...
Formatting results...
Name                 ips        average  deviation         median         99th %
with rules       78.47 K       12.74 μs    ±48.14%       11.96 μs       34.04 μs
100 rules        77.58 K       12.89 μs    ±50.80%          12 μs       33.54 μs
Comparison: 
with rules       78.47 K
100 rules        77.58 K - 1.01x slower +0.147 μs
Extended statistics: 
Name               minimum        maximum    sample size                     mode
with rules        10.54 μs     1371.83 μs       231.50 K                 11.50 μs
100 rules         10.54 μs     1520.71 μs       229.15 K                 11.75 μs
```

chore: benchmark rules routing

---

lib/logflare/backends.ex
lib/logflare/logs/log_event.ex
lib/logflare/logs/logs.ex
mix.exs
test/profiling/ingest_logs.exs

Adds some minor refactoring to drop ingest time reductions.

perf: initial profling scripts of v1 and v2 ingestion

---

docs/docs.logflare.com/docs/concepts/ingestion/index.mdx
lib/logflare/source/bigquery/pipeline.ex

This PR tweaks the schema sampling to be more aggressive with lower thresholds.

feat: tweak schema sampling

---

lib/logflare/backends/supervisor.ex

Removes unnecessary partitioning

perf: remove backends registry partitioning

---

lib/logflare/source/bigquery/schema.ex
lib/logflare/source/recent_logs_server.ex

perf: tweak fullsweep_after

---

lib/logflare/application.ex

fix: revert to http2 for default finch pool

---

lib/logflare/backends/ingest_event_queue/queue_janitor.ex
test/logflare/backends/ingest_events_queue_test.exs

purges only a portion of the events in queue, defaults to 10%

fix: purge only a portion of events in queue

---

lib/logflare/backends/ingest_event_queue.ex
lib/logflare/backends/ingest_event_queue/queue_janitor.ex
test/logflare/backends/ingest_events_queue_test.exs

This PR adds in optimizations for:
- mark_ingested
- truncate
benchmark scripts are also added.

perf: optimize IngestEventQueue functions

---

cloudbuild/staging/deploy.yaml

adds spot staging instance template

chore: add staging spot instance templates

---

.github/workflows/elixir-ci.yml
.gitignore
Makefile
mix.exs
test/test_helper.exs

This PR adds in Sobelow and Dialyzer to our CI for better code quality. This PR also adjusts the ci to use a matrix for faster checks.
It also adds in plt caching for dialyzer
These checks are commented out temporarily for now.
main change is to split out the ci steps to speed things up.

chore: add soebelow and dialyzer (commented out), split steps

---

lib/logflare/pubsub_rates/cache.ex

Increases TTL, for sources that have sporadic bursts.

fix: longer ttl for rates

---

cloudbuild/staging/deploy.yaml

Fixes a cyclic substitution reference

fix: cyclic spot instance template substitution reference

---

lib/logflare/backends/adaptor/webhook_adaptor.ex
lib/logflare/backends/adaptor/webhook_adaptor/egress_middleware.ex
lib/telemetry.ex

This PR emits egress telemetry for the WebhookAdaptor.

feat: initial implementation of webhook egress telemetry

---

lib/logflare/backends/adaptor/datadog_adaptor.ex

This PR adds in gzipping for datadog adaptor.

feat: gzip datadog adaptor

---

lib/logflare/context_cache/transaction_broadcaster.ex
test/logflare/backends_test.exs

chore: fixes flaky tests, remove dbg

---

lib/logflare/utils.ex
test/logflare/backends/webhook_adaptor_test.exs

Fixes default value setting for gzip field for webhook config

fix: default value for webhook gzipping

---

test/logflare_web/controllers/api/backend_controller_test.exs

Adds minor testing around backends description field

chore: add minor testing around backends.description field

---

lib/logflare/logs/log_event.ex
test/logflare/log_event_test.exs

Fixes ui bug when string metadata key is present

fix: string metadata should not cause errors when mapping

---

lib/logflare/auth.ex
lib/logflare/single_tenant.ex
test/logflare/single_tenant_test.exs

This PR fixes token revoking for single tenant when the env var changes

fix: token revoking on single tenant env var change

---

test/logflare/backends_test.exs
test/logflare/single_tenant_test.exs

chore: add test coverage for rules cascade delete on backend delete

---

lib/logflare_web/controllers/api/rule_controller.ex
test/logflare_web/controllers/api/rule_controller_test.exs

This PR adds in optional batch creation for rules, to allow for single api call when creating many rules at once

feat: batch rules creation

---

lib/logflare/erl_sys_mon.ex

fix: ErlSysMon handling of non-pids

---

lib/logflare/sql.ex
test/logflare/sql_test.exs

fix: block show in sql

---

lib/logflare/backends/adaptor/bigquery_adaptor.ex
lib/logflare/backends/ingest_event_queue/queue_janitor.ex
lib/logflare/source/bigquery/pipeline.ex

perf: use pending counts to resolve pipelines

---

docker-compose.yml
docs/docs.logflare.com/docs/backends/loki.mdx
lib/logflare/backends/adaptor.ex
lib/logflare/backends/adaptor/loki_adaptor.ex
lib/logflare/backends/adaptor/webhook_adaptor.ex
lib/logflare/backends/backend.ex
lib/logflare/utils.ex
lib/logflare_web/live/backends/backends_live.ex
lib/logflare_web/live/backends/components/backend_form.heex
test/logflare/backends/loki_adaptor_test.exs
test/loki.yml

feat: initial implementation of loki backend

---

lib/logflare/sources.ex

perf: remove recent logs fetch on dashboard load

---

cloudbuild/staging/deploy.yaml

Increases resource to 4 vcpus and 8gb ram

chore: tweak c2d instance type for staging

---

lib/logflare/ecto/bigquery/bq_repo.ex
lib/logflare/endpoints/cache.ex
lib/logflare/utils/tasks.ex

- tweaks for better Endpoints.Cache behaviors

fix: endpoint cache tweaks

---

test/logflare_web/controllers/api/query_controller_test.exs

chore: silence some noisy ci errors due to database parsing

---

lib/logflare/backends.ex
test/logflare_web/plugs/buffer_limiter_test.exs

doubles max buffer len to allow saturating cores on load testing.

perf: bump max buffer len

---

lib/logflare/billing.ex
lib/logflare/partners/cache.ex
lib/logflare/source/v1_source_sup.ex
lib/logflare/sources.ex
lib/logflare/sources/source.ex
lib/logflare/users/api.ex
lib/logflare/users/cache.ex
lib/logflare/users/users.ex
lib/logflare_web/controllers/plugs/set_plan.ex
lib/logflare_web/controllers/plugs/set_plan_from_cache.ex
lib/logflare_web/controllers/plugs/verify_api_access.ex
test/logflare/users/users_test.exs
test/logflare_web/controllers/log_controller_test.exs
test/profiling/ingest_http_plugs.exs

Increase Plug.SetPlanFromCache from ~33k ips to ~420k ips.
Preloading sources and setting it on the user results in slow conn copying.
depends on #2095  and #2275

perf: users preloading refactor

---

lib/logflare/backends.ex
test/logflare/backends/bigquery_adaptor_test.exs
test/profiling/ingest_http_api_plugs.exs

restrict each queue to 5k items

perf: queue ingest tweaks, reduce memory footprint

---

lib/logflare/backends.ex

Removes task spawning and uses :erpc.mutlicall/5 instead for better exception handling.
Issue: https://linear.app/supabase/issue/ANL-622/fix-list-recent-logs-task-match-error

fix: removes task spawning for listing recent logs

---

.github/workflows/elixir-ci.yml
README.md
mix.exs

uploads coverage files to coveralls.

chore: add coveralls uploading

---

.github/workflows/pages.yml

Fixes docs pages build and deployment

fix: upload-pages-artifact@v3 bump

---

priv/repo/migrations/20250203131456_create_index_for_users_partners_upgraded.exs

Performance optimization for when checking if tenants are upgraded

perf: add index for partner_users :upgraded field

---

.github/workflows/pages-build.yml
.github/workflows/pages.yml

fix: github pages deployment failure

---

docker-compose.yml
examples/otel-collector/config.yaml

Example of otel collector exporter to logflare

docs: otel collector example

---

Makefile

adds two additional instance templates for clusters d and e in eu-west1

chore: create instance templates for cluster d and e

---

lib/logflare/sql.ex
test/logflare/sql_test.exs

Parser and AST transformation now handles CTEs and union all in sandboxed CTE queries.

feat: add support for UNION ALL and CTEs in sandboxed queries.

---

native/sqlparser_ex/Cargo.lock

chore: update cargo lockfile

---

cloudbuild/prod/pre-deploy.yaml
cloudbuild/staging/deploy.yaml
lib/logflare/backends/source_sup.ex
lib/logflare/sources/source_routing.ex
test/logflare/backends_test.exs

chore: remove external ip address for instance templaces

---

assets/js/source.js
lib/logflare_web/live/search_live/templates/logs_list.html.heex
lib/logflare_web/templates/source/show.html.eex

https://github.com/user-attachments/assets/788c770a-af60-46df-a381-946f4f8a9705

feat: highlight on hover

---

cloudbuild/prod/pre-deploy.yaml
cloudbuild/staging/deploy.yaml

chore: reduce boot disk sizes

---

.github/workflows/elixir-ci.yml

chore: ci on every branch

---

lib/logflare/erl_sys_mon.ex

Closes ANL-798.
Adds runtime debugging option, so that we don't have redundant messages unless we need to do debugging.

feat: Add  net kernel logging to ErlSysMon

---

cloudbuild/prod/pre-deploy.yaml

Reduce prod instance to 32vcpus and 64GB

chore: reduce prod memory

---

rel/vm.args.eex

Reverts load compaction, seems to have adverse effects for scheduling and gc-ing on load test cluster.

perf: revert load compaction

---

lib/logflare/sources/source_routing.ex
test/logflare/backends_test.exs

bugfix for source routing for v2 pipeline

fix: routing bug when checking if source sup is started

---

lib/logflare/endpoints.ex
lib/logflare_web/controllers/api/query_controller.ex
lib/logflare_web/live/endpoints/actions/show.html.heex
lib/logflare_web/live/endpoints/endpoints_live.ex
lib/logflare_web/live/query_live.ex
test/logflare/endpoints_test.exs

This PR fixes Logflare UI to correctly handle nested parameters as well as allowing easy testing of nested parameters within the UI.

feat: add testing ui for checking verifying query expanding for nested fields

---

test/logflare/google/resource_manager_test.exs

test: fix google resource manager test

---

lib/logflare/application.ex
lib/logflare/endpoints/cache.ex
lib/logflare/endpoints/resolver.ex

- uses PartitionSupervisor for Endpoints

perf: use PartitionSupervisor for Endpoints

---

lib/logflare/cluster/postgres_strategy.ex

Only attempt a node connect if node is not already in the node list

fix: reduce cluster connection attemtps

---

lib/logflare_web/live/lql/lql_form_lvc.ex
lib/logflare_web/live/lql/lql_form_lvc.html.heex
lib/logflare_web/live/sources/rules_live.ex
lib/logflare_web/live/sources/rules_live.html.heex
lib/logflare_web/router.ex
lib/logflare_web/templates/source/edit.html.eex
lib/logflare_web/templates/source/show.html.eex
lib/logflare_web/views/lql_view.ex
lib/logflare_web/views/rule_view.ex
test/logflare_web/live/sources/rules_live_test.exs

Fixed a bug introduced in https://github.com/Logflare/logflare/pull/2507.

test: improve coverage on RuleLive

---

lib/logflare_web/live/modal_live_helpers.ex

Looks to be leftover from earlier refactor.

refactor: remove redundant code

---

test/logflare_web/live_views/log_event_live_test.exs

Addresses feedback in https://github.com/Logflare/logflare/pull/2492

test: use retry_assert instead of sleep in tests

---

lib/logflare_grpc/endpoint.ex

removes info level logging for grpc server

perf: remove info level logging

---

lib/logflare/alerting.ex
test/logflare/alerting_test.exs

Should have been a with/do match, fell through the cracks.

chore: fix flaky test

---

lib/logflare/google/bigquery/bigquery.ex
lib/logflare/sources.ex
lib/logflare/sources/source.ex
lib/logflare_web/templates/source/edit.html.eex
priv/repo/migrations/20250702081228_add_bigquery_clustering_fieldsto_sources_table.exs

This PR adds in BQ clustering management
closes ANL-950
Depends on #2488

perf: bq clustering

---

lib/logflare/syn_event_handler.ex
lib/logflare_web/controllers/auth/auth_controller.ex
lib/logflare_web/controllers/plugs/check_admin.ex
lib/logflare_web/controllers/plugs/set_verify_source.ex
lib/logflare_web/controllers/team_user_controller.ex
lib/logflare_web/templates/error/403_page.html.heex
test/logflare_web/controllers/auth/auth_controller_test.exs
test/logflare_web/controllers/team_user_controller_test.exs

fix for storing last team info on swithcing teams, and fixes 403 team list

fix: dashboard storing last team info, 403 team list

---

docs/docs.logflare.com/docs/concepts/endpoints.md

add docs about subquery expansion

docs: subquery expansion

---

lib/logflare_web/views/elixir_logger_view.ex

The controller this was related was removed in commit d7ef73619be102125f0a4af40b512cb7ba9a713e.

chore: deleted unused logger view

---

lib/logflare/account_email.ex
lib/logflare/logs/search/logs_search_operations.ex
lib/logflare/source/bigquery/schema.ex
lib/logflare/source/supervisor.ex
lib/logflare/sources.ex
lib/logflare_web/controllers/api/source_controller.ex
lib/logflare_web/live/sources/bq_schema_component.ex
lib/logflare_web/live/sources/rules_live.ex

perf: remove schema updated with no new fields  logs

---

lib/logflare/application.ex

perf: reduce DD connection counts

---

lib/logflare/backends/adaptor/webhook_adaptor/egress_middleware.ex
lib/logflare/source/bigquery/pipeline.ex

Otel nil attributes getting stringified and rejected by BQ
closes ANL-986

fix: nil OTEL attributes

---

lib/logflare_web/live/search_live/logs_search_lv.ex
lib/logflare_web/live/search_live/logs_search_lv_utils.ex

There were a number of calls to functions that had commented out log messages.
Please reject if they are actually required 😀

chore: remove unused log messages

---

lib/logflare_web/core_components.ex
lib/logflare_web/live/log_event_live/search_log_event_viewer_component.ex
lib/logflare_web/live/search_live/log_event_components.ex
lib/logflare_web/templates/log/log_event_body.html.heex
lib/logflare_web/views/log_view.ex
test/logflare_web/live_views/log_event_live_test.exs

* add log event permalink component
* ensure lql query is passed to log event view component
https://github.com/user-attachments/assets/4455a2af-60fc-4fa2-8586-eecd0ff2e92a

fix: log event view permalink

---

lib/logflare/alerting.ex

refactor: extract nested code in lib/logflare/alerting.ex

---

lib/logflare/sources.ex
lib/logflare_web/controllers/endpoints_controller.ex
lib/logflare_web/open_api_schemas.ex
lib/logflare_web/views/endpoints_view.ex
test/logflare/endpoints_test.exs
test/logflare_web/controllers/endpoints_controller_test.exs
test/support/test_utils.ex

Fixes a bug on the error response view :heavy_check_mark:

test: improve coverage on EndpointsController

---

lib/logflare/logs/search_operations.ex
lib/logflare/rules.ex
lib/logflare/source/bigquery/schema.ex
lib/logflare/source/data.ex
lib/logflare/sources.ex
lib/logflare/sources/source.ex
lib/logflare_web/live/search_live/logs_search_lv.ex
lib/logflare_web/open_api_schemas.ex
test/logflare/logs/search_operations_test.exs
test/logflare/single_tenant_test.exs
test/logflare_web/live/search_live/logs_search_lv_test.exs

fixes schema message queue issues, as search pages were continuously fetching from the schema.
closes ANL-999

perf: fix schema message queue issues

---

lib/logflare/logs/vercel/vercel_parser.ex

refactor: extract nested code in lib/logflare/logs/vercel/vercel_parser.ex

---

Makefile
cloudbuild/prod/pre-deploy.yaml

This PR ensures that only the query cluster has alerts enabled

chore: only enable alerts for query cluster

---

lib/logflare/logs/search_operations.ex

refactor: extract nested code in lib/logflare/logs/search_operations.ex

---

lib/logflare/context_cache.ex

refactor: extract nested code in lib/logflare/context_cache.ex

---

lib/logflare/endpoints/cache.ex

reduces the cache time significantly

perf: Endpoints.Cache tweaks

---

lib/logflare/backends/adaptor/datadog_adaptor.ex

Customer request, related to ANL-1044

feat: support ap2 datadog

---

lib/logflare/sql.ex
test/logflare/sql_test.exs

Some improvements to the logic around handling AST for sandboxed queries. At least to get us a better understanding of the source queries causing issues.

fix: endpoint query / sql ast bugs

---

lib/logflare/backends/adaptor/bigquery_adaptor/google_api_client.ex
test/logflare/backends/bigquery_adaptor_test.exs

- do not stream append rows messages
- add warning when batch messages are higher than one
- improve test case for inserting logs with bq write

bq writer storage improvements

---

test/logflare_web/live/search_live/logs_search_lv_test.exs

Removes unnecessary process dependencies to speed up tests and make them less flaky

chore: remove unnecessary process setup

---

lib/logflare/backends/adaptor.ex
lib/logflare/backends/adaptor/clickhouse_adaptor.ex
lib/logflare/backends/adaptor/datadog_adaptor.ex
lib/logflare/backends/adaptor/elastic_adaptor.ex
lib/logflare/backends/adaptor/incidentio_adaptor.ex
lib/logflare/backends/adaptor/loki_adaptor.ex
lib/logflare/backends/adaptor/postgres_adaptor.ex
lib/logflare/backends/adaptor/s3_adaptor.ex
lib/logflare/backends/adaptor/sentry_adaptor.ex
lib/logflare/backends/adaptor/webhook_adaptor.ex
lib/logflare/backends/backend.ex
test/logflare/backends/adaptor/clickhouse_adaptor_test.exs
test/logflare/backends/adaptor/datadog_adaptor_test.exs
test/logflare/backends/adaptor/elastic_adaptor_test.exs
test/logflare/backends/adaptor/incidentio_adaptor_test.exs
test/logflare/backends/adaptor/loki_adaptor_test.exs
test/logflare/backends/adaptor/postgres_adaptor_test.exs
test/logflare/backends/adaptor/s3_adaptor_test.exs
test/logflare/backends/adaptor/sentry_adaptor_test.exs
test/logflare/backends/adaptor/webhook_adaptor_test.exs
test/logflare_web/controllers/api/backend_controller_test.exs

Adds in secrets redaction for backends. ensures that secrets are not leaked even in Backend GET.
Each backend adaptor is responsible for ensuring the redaction

feat: comprehensive secrets redaction for backends

---

lib/logflare/backends.ex
lib/logflare_web/live/endpoints/actions/show.html.heex
lib/logflare_web/live/endpoints/endpoints_live.ex

perf: use list comparison
